package com.aiprovider.quant.risk.pretrade;

public enum PreTradeRiskViolationCode {
    ENTRY_POSITION_ALREADY_OPEN,
    EXIT_POSITION_NOT_OPEN,
    EXIT_QUANTITY_EXCEEDS_POSITION,
    AVAILABLE_CAPITAL_INSUFFICIENT,
    ORDER_NOTIONAL_LIMIT_EXCEEDED,
    TOTAL_EXPOSURE_LIMIT_EXCEEDED,
    REMAINING_CAPITAL_LIMIT_BREACHED,
    DAILY_LOSS_LIMIT_BREACHED,
    CONSECUTIVE_LOSS_LIMIT_BREACHED
}
