package com.aiprovider.service;

import com.aiprovider.mapper.AsrRecordMapper;
import com.aiprovider.model.vo.*;
import com.aiprovider.repository.AsrRecordRepository;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.FileSystemResource;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.*;
import java.sql.Timestamp;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class AsrTranscriptionService {
    private static final Logger log=LogManager.getLogger(AsrTranscriptionService.class);
    private static final Set<String> FORMATS=new HashSet<>(Arrays.asList("webm","wav","mp3","m4a","ogg"));
    private static final Set<String> STATUSES=new HashSet<>(Arrays.asList("SUCCESS","FAILED"));
    private final AsrRecordRepository repository;private final AsrProviderClient providerClient;private final Path storageRoot;private final String provider;private final String model;private final long maxAudioBytes;private final long hourlyAudioLimitSeconds;private final long dailyAudioLimitSeconds;
    public AsrTranscriptionService(AsrRecordRepository repository,AsrProviderClient providerClient,@Value("${asr.storage-directory:/opt/aiprovider/asr}") String storageDirectory,@Value("${asr.provider:groq}") String provider,@Value("${asr.model:whisper-large-v3}") String model,@Value("${asr.max-audio-bytes:26214400}") long maxAudioBytes,@Value("${asr.hourly-audio-limit-seconds:7200}") long hourlyAudioLimitSeconds,@Value("${asr.daily-audio-limit-seconds:28800}") long dailyAudioLimitSeconds){this.repository=repository;this.providerClient=providerClient;this.storageRoot=Paths.get(storageDirectory).toAbsolutePath().normalize();this.provider=required(provider,"ASR Provider",64);this.model=required(model,"ASR 模型",128);this.maxAudioBytes=maxAudioBytes;if(hourlyAudioLimitSeconds<=0||dailyAudioLimitSeconds<=0)throw new IllegalArgumentException("ASR 音频额度配置必须大于 0");this.hourlyAudioLimitSeconds=hourlyAudioLimitSeconds;this.dailyAudioLimitSeconds=dailyAudioLimitSeconds;}

    public AsrRecordVO transcribe(MultipartFile audio,String characterId,String sessionId,String language,String requestId) {
        String normalizedRequest=required(requestId,"requestId",128);String normalizedCharacter=optionalIdentifier(characterId,"characterId",96);String normalizedSession=optionalIdentifier(sessionId,"sessionId",128);String normalizedLanguage=language(language);validateAudio(audio);
        Map<String,Object> existing=repository.findByRequestId(normalizedRequest);if(existing!=null)return replay(existing);
        String format=extension(audio.getOriginalFilename());Path target=saveAudio(audio,format,normalizedRequest,normalizedCharacter);
        AsrRecordMapper.Record row=new AsrRecordMapper.Record();row.setRequestId(normalizedRequest);row.setCharacterId(normalizedCharacter);String name=normalizedCharacter==null?null:repository.findCharacterName(normalizedCharacter);row.setCharacterNameSnapshot(name==null||name.trim().isEmpty()?normalizedCharacter:name.trim());row.setSessionId(normalizedSession);row.setAudioPath(target.toString());row.setAudioFormat(format);row.setAudioSize(audio.getSize());row.setProvider(provider);row.setModel(model);row.setLanguage(normalizedLanguage);
        try{if(repository.insert(row)!=1||row.getId()==null)throw new IllegalStateException("ASR 记录新增影响行数不一致");}
        catch(DuplicateKeyException e){try{Files.deleteIfExists(target);}catch(IOException cleanupError){log.warn("operation=asr.audio.cleanup requestId={} characterId={} requestedCount=1 affectedRows=0 resultStatus=FAILED errorType={}",normalizedRequest,normalizedCharacter,cleanupError.getClass().getSimpleName());}Map<String,Object> duplicate=repository.findByRequestId(normalizedRequest);if(duplicate==null)throw e;return replay(duplicate);}
        String recordId="asr_"+LocalDate.now(ZoneId.of("Asia/Shanghai")).format(DateTimeFormatter.BASIC_ISO_DATE)+"_"+String.format(Locale.ROOT,"%06d",row.getId());
        if(repository.assignRecordId(row.getId(),recordId)!=1)throw new IllegalStateException("ASR 记录编号更新影响行数不一致");
        long started=System.nanoTime();
        try{AsrProviderClient.Result result=providerClient.transcribe(target,model,normalizedLanguage);long processing=elapsed(started);int affected=repository.markSuccess(row.getId(),result.getText(),result.getDurationMs(),processing,result.getRequestLimit(),result.getRequestsRemaining(),result.getRequestsResetAfter());if(affected!=1){log.warn("operation=asr.transcribe requestId={} recordId={} characterId={} requestedCount=1 affectedRows={} resultStatus=FAILED reason=ROW_COUNT_MISMATCH",normalizedRequest,recordId,normalizedCharacter,affected);throw new IllegalStateException("ASR 成功记录影响行数不一致");}log.info("operation=asr.transcribe requestId={} recordId={} characterId={} requestedCount=1 affectedRows=1 provider={} model={} audioSize={} processingTimeMs={} quotaCaptured={} resultStatus=SUCCESS",normalizedRequest,recordId,normalizedCharacter,provider,model,audio.getSize(),processing,result.getRequestLimit()!=null&&result.getRequestsRemaining()!=null);return get(recordId);}
        catch(AsrProviderException e){long processing=elapsed(started);int affected=repository.markFailed(row.getId(),processing,e.getCode(),"语音识别失败");if(affected!=1)log.warn("operation=asr.transcribe requestId={} recordId={} characterId={} requestedCount=1 affectedRows={} resultStatus=FAILED reason=ROW_COUNT_MISMATCH",normalizedRequest,recordId,normalizedCharacter,affected);log.error("operation=asr.transcribe requestId={} recordId={} characterId={} requestedCount=1 affectedRows={} provider={} model={} processingTimeMs={} resultStatus=FAILED errorCode={} upstreamError={}",normalizedRequest,recordId,normalizedCharacter,affected,provider,model,processing,e.getCode(),e.getMessage());throw new AsrTranscriptionException("ASR_TRANSCRIPTION_FAILED",normalizedRequest);}
    }

    public AsrRecordPageVO page(int page,int pageSize,String characterId,String status,String providerFilter,String modelFilter,String keyword,String startTime,String endTime){int p=Math.max(1,page);int size=Math.max(1,Math.min(100,pageSize));String state=upper(status);if(state!=null&&!STATUSES.contains(state))throw new IllegalArgumentException("status 只允许 SUCCESS 或 FAILED");String character=trim(characterId);String providerValue=trim(providerFilter);String modelValue=trim(modelFilter);String word=limit(trim(keyword),200);LocalDateTime start=parseTime(startTime);LocalDateTime end=parseTime(endTime);if(start!=null&&end!=null&&start.isAfter(end))throw new IllegalArgumentException("开始时间不能晚于结束时间");List<AsrRecordVO> items=repository.findPage(character,state,providerValue,modelValue,word,start,end,(p-1)*size,size).stream().map(this::vo).collect(Collectors.toList());long total=repository.count(character,state,providerValue,modelValue,word,start,end);log.info("operation=asr.records.query requestedCount={} affectedRows={} page={} characterId={} status={} provider={} model={}",size,items.size(),p,character,state,providerValue,modelValue);return new AsrRecordPageVO(items,total,p,size);}
    public AsrRecordVO get(String recordId){Map<String,Object> row=repository.findByRecordId(required(recordId,"recordId",40));if(row==null)throw new IllegalArgumentException("ASR_RECORD_NOT_FOUND");return vo(row);}
    public void correct(String recordId,String correctedText){String id=required(recordId,"recordId",40);String text=limit(trimToEmpty(correctedText),20000);int affected=repository.updateCorrection(id,text.isEmpty()?null:text);if(affected!=1){log.warn("operation=asr.correction.update recordId={} requestedCount=1 affectedRows={} resultStatus=FAILED",id,affected);throw new IllegalArgumentException("ASR_RECORD_NOT_FOUND");}log.info("operation=asr.correction.update recordId={} requestedCount=1 affectedRows=1 correctedCharacters={} resultStatus=SUCCESS",id,text.length());}
    public AsrAudioContent audio(String recordId){Map<String,Object> row=repository.findByRecordId(required(recordId,"recordId",40));if(row==null)throw new IllegalArgumentException("ASR_RECORD_NOT_FOUND");Path path=Paths.get(String.valueOf(row.get("audioPath"))).toAbsolutePath().normalize();if(!path.startsWith(storageRoot)||!Files.isRegularFile(path))throw new IllegalArgumentException("ASR_AUDIO_NOT_FOUND");String format=String.valueOf(row.get("audioFormat"));try{return new AsrAudioContent(new FileSystemResource(path.toFile()),mime(format),Files.size(path),recordId+"."+format);}catch(IOException e){throw new IllegalStateException("ASR 音频读取失败");}}
    public Map<String,Object> filters(){Map<String,Object> value=new LinkedHashMap<>();value.put("characters",repository.findCharacters());value.put("providerModels",repository.findProviderModels());return value;}
    public AsrQuotaVO quota(){LocalDateTime[] window=quotaWindows(Instant.now());long hourlyUsed=seconds(repository.sumAudioDurationMs(provider,model,window[0],window[2]));long dailyUsed=seconds(repository.sumAudioDurationMs(provider,model,window[1],window[2]));Map<String,Object> snapshot=repository.findLatestQuotaSnapshot(provider,model);AsrQuotaVO value=new AsrQuotaVO();value.setProvider(provider);value.setModel(model);value.setHourlyAudioLimitSeconds(hourlyAudioLimitSeconds);value.setHourlyAudioUsedSeconds(hourlyUsed);value.setHourlyAudioRemainingSeconds(Math.max(0,hourlyAudioLimitSeconds-hourlyUsed));value.setDailyAudioLimitSeconds(dailyAudioLimitSeconds);value.setDailyAudioUsedSeconds(dailyUsed);value.setDailyAudioRemainingSeconds(Math.max(0,dailyAudioLimitSeconds-dailyUsed));value.setAudioUsageScope("AIPROVIDER_RECORDED");if(snapshot!=null){value.setDailyRequestLimit(nullableNumber(snapshot.get("requestLimit")));value.setDailyRequestsRemaining(nullableNumber(snapshot.get("requestsRemaining")));value.setRequestsResetAfter(text(snapshot.get("requestsResetAfter")));value.setProviderSnapshotAt(localDateTime(snapshot.get("capturedAt")));}log.info("operation=asr.quota.query provider={} model={} requestedCount=1 affectedRows={} hourlyAudioUsedSeconds={} dailyAudioUsedSeconds={} resultStatus=SUCCESS",provider,model,snapshot==null?0:1,hourlyUsed,dailyUsed);return value;}
    static LocalDateTime[] quotaWindows(Instant instant){ZoneId shanghai=ZoneId.of("Asia/Shanghai");LocalDateTime end=LocalDateTime.ofInstant(instant,ZoneOffset.UTC);LocalDateTime dayStart=instant.atZone(shanghai).toLocalDate().atStartOfDay(shanghai).withZoneSameInstant(ZoneOffset.UTC).toLocalDateTime();return new LocalDateTime[]{end.minusHours(1),dayStart,end};}

    private AsrRecordVO replay(Map<String,Object> row){String status=String.valueOf(row.get("status"));String requestId=String.valueOf(row.get("requestId"));if("SUCCESS".equals(status)){log.info("operation=asr.transcribe.idempotent requestId={} recordId={} requestedCount=1 affectedRows=0 resultStatus=SUCCESS",requestId,row.get("recordId"));return vo(row);}if("FAILED".equals(status))throw new AsrTranscriptionException("ASR_TRANSCRIPTION_FAILED",requestId);throw new AsrTranscriptionException("ASR_REQUEST_IN_PROGRESS",requestId);}
    private Path saveAudio(MultipartFile audio,String format,String requestId,String characterId){try{Files.createDirectories(storageRoot);Path target=storageRoot.resolve(UUID.randomUUID().toString()+"."+format).normalize();if(!target.startsWith(storageRoot))throw new SecurityException("音频存储路径非法");try(InputStream input=audio.getInputStream()){Files.copy(input,target,StandardCopyOption.REPLACE_EXISTING);}return target;}catch(IOException e){log.error("operation=asr.audio.save requestId={} characterId={} requestedCount=1 affectedRows=0 audioSize={} resultStatus=FAILED errorType={}",requestId,characterId,audio.getSize(),e.getClass().getSimpleName());throw new AsrTranscriptionException("ASR_STORAGE_FAILED",requestId);}}
    private AsrRecordVO vo(Map<String,Object> row){AsrRecordVO v=new AsrRecordVO();v.setRecordId(text(row.get("recordId")));v.setRequestId(text(row.get("requestId")));v.setCharacterId(text(row.get("characterId")));v.setCharacterNameSnapshot(text(row.get("characterNameSnapshot")));v.setSessionId(text(row.get("sessionId")));v.setAudioUrl(v.getRecordId()==null?null:"/api/admin/asr/records/"+v.getRecordId()+"/audio");v.setAudioFormat(text(row.get("audioFormat")));v.setAudioSize(number(row.get("audioSize"),0L));v.setAudioDurationMs(nullableNumber(row.get("audioDurationMs")));v.setRecognizedText(text(row.get("recognizedText")));v.setCorrectedText(text(row.get("correctedText")));v.setProvider(text(row.get("provider")));v.setModel(text(row.get("model")));v.setLanguage(text(row.get("language")));v.setProcessingTimeMs(nullableNumber(row.get("processingTimeMs")));v.setStatus(text(row.get("status")));v.setErrorCode(text(row.get("errorCode")));v.setErrorMessage(text(row.get("errorMessage")));v.setCreatedAt(localDateTime(row.get("createdAt")));return v;}
    private void validateAudio(MultipartFile audio){if(audio==null||audio.isEmpty())throw new IllegalArgumentException("audio 不能为空");if(audio.getSize()>maxAudioBytes)throw new IllegalArgumentException("音频文件不能超过 "+maxAudioBytes+" 字节");extension(audio.getOriginalFilename());}
    private String extension(String name){String value=trim(name);int dot=value==null?-1:value.lastIndexOf('.');String ext=dot<0?"":value.substring(dot+1).toLowerCase(Locale.ROOT);if(!FORMATS.contains(ext))throw new IllegalArgumentException("仅支持 webm、wav、mp3、m4a、ogg 音频");return ext;}
    private String language(String value){String result=trim(value);if(result==null)result="zh";if(!result.matches("[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})?"))throw new IllegalArgumentException("language 格式不正确");return result;}
    private String identifier(String value,String label,int max){String result=required(value,label,max);if(!result.matches("[A-Za-z0-9_-]{1,"+max+"}"))throw new IllegalArgumentException(label+" 格式不正确");return result;}
    private String optionalIdentifier(String value,String label,int max){String result=trim(value);return result==null?null:identifier(result,label,max);}
    private String required(String value,String label,int max){String result=trim(value);if(result==null)throw new IllegalArgumentException(label+" 不能为空");return limit(result,max);}
    private String limit(String value,int max){if(value!=null&&value.length()>max)throw new IllegalArgumentException("字段长度不能超过 "+max);return value;}
    private String trim(String value){if(value==null)return null;String v=value.trim();return v.isEmpty()?null:v;}private String trimToEmpty(String value){return value==null?"":value.trim();}private String upper(String value){String v=trim(value);return v==null?null:v.toUpperCase(Locale.ROOT);}private long elapsed(long start){return Math.max(0L,(System.nanoTime()-start)/1_000_000L);}private String text(Object v){return v==null?null:String.valueOf(v);}private long number(Object v,long fallback){return v instanceof Number?((Number)v).longValue():v==null?fallback:Long.parseLong(String.valueOf(v));}private Long nullableNumber(Object v){return v==null?null:number(v,0L);}private LocalDateTime localDateTime(Object v){if(v instanceof LocalDateTime)return (LocalDateTime)v;if(v instanceof Timestamp)return ((Timestamp)v).toLocalDateTime();return v==null?null:LocalDateTime.parse(String.valueOf(v).replace(' ','T'));}
    private LocalDateTime parseTime(String value){String v=trim(value);if(v==null)return null;try{return OffsetDateTime.parse(v).atZoneSameInstant(ZoneId.of("Asia/Shanghai")).toLocalDateTime();}catch(Exception ignored){try{return LocalDateTime.parse(v);}catch(Exception e){throw new IllegalArgumentException("时间格式不正确");}}}
    private String mime(String format){if("wav".equals(format))return "audio/wav";if("mp3".equals(format))return "audio/mpeg";if("m4a".equals(format))return "audio/mp4";if("ogg".equals(format))return "audio/ogg";return "audio/webm";}
    private long seconds(long milliseconds){return Math.max(0L,(milliseconds+999L)/1000L);}
}
