package com.aiprovider.service;

import com.aiprovider.mapper.ContentOperationsMapper;
import com.aiprovider.model.vo.*;
import com.aiprovider.repository.ContentOperationsRepository;
import org.springframework.stereotype.Service;
import java.util.*;

@Service
public class ContentPipelineService {
    private final ContentOperationsRepository repository;private final ContentSourceService sources;private final ContentRelevanceService relevance;private final ContentDraftService drafts;private final XiaohongshuPublicationService publisher;
    public ContentPipelineService(ContentOperationsRepository repository,ContentSourceService sources,ContentRelevanceService relevance,ContentDraftService drafts,XiaohongshuPublicationService publisher){this.repository=repository;this.sources=sources;this.relevance=relevance;this.drafts=drafts;this.publisher=publisher;}
    public List<ContentPipelineTestVO> testAccount(long accountId){
        com.aiprovider.logging.BusinessOperationLogger.start("service.ContentPipelineService.testAccount", new String[] { "accountId" }, new Object[] { accountId });
        Map<String,Object> account=repository.findAccount(accountId);if(account==null)throw new IllegalArgumentException("小红书账号不存在");List<Long> sourceIds=repository.findAccountSourceIds(accountId);if(sourceIds.isEmpty())throw new IllegalArgumentException("该小红书账号尚未绑定内容源");List<ContentPipelineTestVO> result=new ArrayList<>();for(Long sourceId:sourceIds)result.add(testOne(accountId,sourceId,account));return com.aiprovider.logging.BusinessOperationLogger.success("service.ContentPipelineService.testAccount", result);}
    public ContentPipelineTestVO processBoundSource(long accountId,long sourceId){
        com.aiprovider.logging.BusinessOperationLogger.start("service.ContentPipelineService.processBoundSource", new String[] { "accountId", "sourceId" }, new Object[] { accountId, sourceId });
        Map<String,Object> account=repository.findAccount(accountId);if(account==null)throw new IllegalArgumentException("小红书账号不存在");if(!repository.findAccountSourceIds(accountId).contains(sourceId))throw new IllegalArgumentException("内容源未绑定到该小红书账号");return com.aiprovider.logging.BusinessOperationLogger.success("service.ContentPipelineService.processBoundSource", testOne(accountId,sourceId,account));}
    public ContentPipelineTestVO processStoredSource(long accountId,long sourceId){
        com.aiprovider.logging.BusinessOperationLogger.start("service.ContentPipelineService.processStoredSource", new String[] { "accountId", "sourceId" }, new Object[] { accountId, sourceId });
        Map<String,Object> account=repository.findAccount(accountId);if(account==null)throw new IllegalArgumentException("小红书账号不存在");if(!repository.findAccountSourceIds(accountId).contains(sourceId))throw new IllegalArgumentException("内容源未绑定到该小红书账号");ContentItemVO item=sources.latestUndispatched(accountId,sourceId);if(item==null)return com.aiprovider.logging.BusinessOperationLogger.success("service.ContentPipelineService.processStoredSource", new ContentPipelineTestVO(accountId,sourceId,null,"NO_CONTENT","当前没有尚未发送的新内容",null,null));return com.aiprovider.logging.BusinessOperationLogger.success("service.ContentPipelineService.processStoredSource", processItem(accountId,sourceId,account,item));}
    private ContentPipelineTestVO testOne(long accountId,long sourceId,Map<String,Object> account){ContentSourceTestVO fetched=sources.testFetch(sourceId);if(fetched.getItems().isEmpty())return new ContentPipelineTestVO(accountId,sourceId,null,"NO_CONTENT","没有拉到可处理内容",null,null);return processItem(accountId,sourceId,account,fetched.getItems().get(0));}
    private ContentPipelineTestVO processItem(long accountId,long sourceId,Map<String,Object> account,ContentItemVO item){boolean relevant;if("RELEVANT".equals(item.getRelevanceStatus()))relevant=true;else if("IRRELEVANT".equals(item.getRelevanceStatus()))relevant=false;else relevant=relevance.classify(item.getId()).isRelevant();if(!relevant)return new ContentPipelineTestVO(accountId,sourceId,item.getId(),"FILTERED","Gemini 判定为非 AI 内容，已停止流转",null,null);ContentDraftVO draft=drafts.createXiaohongshuDraft(item.getId());Long publicationId=repository.findPublicationId(draft.getId(),accountId);if(publicationId!=null){Map<String,Object> existing=repository.findPublicationDetails(publicationId);String existingStatus=existing==null?null:text(existing.get("status"));if("PUBLISHED".equals(existingStatus))return new ContentPipelineTestVO(accountId,sourceId,item.getId(),"ALREADY_EXISTS","该内容已经为此账号发布过，禁止重复发送",draft,publicationId);if("UNKNOWN".equals(existingStatus)||"PROCESSING".equals(existingStatus))return new ContentPipelineTestVO(accountId,sourceId,item.getId(),"UNCERTAIN","此前任务结果待人工确认，系统不会自动重试",draft,publicationId);publisher.publish(publicationId);return new ContentPipelineTestVO(accountId,sourceId,item.getId(),"PUBLISHED","已重新执行未成功的任务并发布到小红书",draft,publicationId);}ContentOperationsMapper.PublicationRecord record=new ContentOperationsMapper.PublicationRecord();record.setDraftId(draft.getId());record.setAccountId(accountId);record.setPublishMode(text(account.get("publishMode")));record.setStatus("PENDING");repository.insertPublication(record);publicationId=repository.findPublicationId(draft.getId(),accountId);if(publicationId==null)throw new IllegalStateException("发布任务创建失败");publisher.publish(publicationId);return new ContentPipelineTestVO(accountId,sourceId,item.getId(),"PUBLISHED","已生成文字卡并发布到小红书",draft,publicationId);}
    private String text(Object value){return value==null?null:String.valueOf(value);}
}
