package com.aiprovider.service;

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.BoundingBox;
import org.slf4j.Logger;import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Component;
import javax.annotation.PreDestroy;
import java.util.*;import java.util.concurrent.ConcurrentHashMap;

@Component
public class DouyinWebAdapter {
    private static final Logger log=LoggerFactory.getLogger(DouyinWebAdapter.class);
    private final boolean headless;private final long timeoutMs;private final long sessionTtlMs;private final String executable;
    private final Map<String,LoginSession> sessions=new ConcurrentHashMap<>();
    public DouyinWebAdapter(@Value("${douyin.headless:true}")boolean headless,@Value("${douyin.navigation-timeout-ms:60000}")long timeoutMs,@Value("${douyin.login-session-ttl-ms:300000}")long sessionTtlMs,@Value("${douyin.browser-executable-path:}")String executable){this.headless=headless;this.timeoutMs=timeoutMs;this.sessionTtlMs=sessionTtlMs;this.executable=executable==null?"":executable.trim();}

    public LoginSnapshot startLogin(long accountId){
        com.aiprovider.logging.BusinessOperationLogger.start("service.DouyinWebAdapter.startLogin", new String[] { "accountId" }, new Object[] { accountId });
        closeAccountSessions(accountId);Playwright playwright=null;Browser browser=null;BrowserContext context=null;try{playwright=Playwright.create();browser=launch(playwright);context=browser.newContext(new Browser.NewContextOptions().setViewportSize(1280,760));context.setDefaultTimeout(timeoutMs);Page page=context.newPage();String initial=context.storageState();page.navigate("https://creator.douyin.com/",new Page.NavigateOptions().setTimeout(timeoutMs));page.waitForTimeout(1500);if(isAuthenticated(context,page.url())){String state=context.storageState();close(context,browser,playwright);return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.startLogin", new LoginSnapshot(null,"CONNECTED",null,"抖音创作者账号已登录",state));}String risk=riskMessage(page);if(risk!=null)throw new IllegalStateException("PLATFORM_RISK_CONTROL");String qr=qrImage(page);String id=UUID.randomUUID().toString();sessions.put(id,new LoginSession(id,accountId,playwright,browser,context,page,initial));log.info("operation=douyin.login-start platform=DOUYIN accountId={} requestedCount=1 affectedRows=1 resultStatus=SUCCESS",accountId);return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.startLogin", new LoginSnapshot(id,"WAITING_SCAN",qr,"请使用抖音 App 扫码登录"));}catch(RuntimeException e){close(context,browser,playwright);if("PLATFORM_RISK_CONTROL".equals(e.getMessage()))throw e;throw new IllegalStateException("ADAPTER_UNAVAILABLE",e);}}
    public LoginSnapshot poll(long accountId,String sessionId){
        com.aiprovider.logging.BusinessOperationLogger.start("service.DouyinWebAdapter.poll", new String[] { "accountId", "sessionId" }, new Object[] { accountId, sessionId });
        LoginSession session=sessions.get(sessionId);if(session==null||session.accountId!=accountId)throw new IllegalArgumentException("LOGIN_TIMEOUT");synchronized(session){if(System.currentTimeMillis()-session.createdAt>sessionTtlMs){sessions.remove(sessionId);session.close();return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.poll", new LoginSnapshot(sessionId,"LOGIN_TIMEOUT",null,"抖音扫码登录已超时"));}try{String risk=riskMessage(session.page);if(risk!=null){sessions.remove(sessionId);session.close();return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.poll", new LoginSnapshot(sessionId,"PLATFORM_RISK_CONTROL",null,risk));}if(isAuthenticated(session.context,session.page.url())&&!session.initialState.equals(session.context.storageState())){String state=session.context.storageState();sessions.remove(sessionId);session.close();return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.poll", new LoginSnapshot(sessionId,"CONNECTED",null,"抖音扫码登录成功",state));}return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.poll", new LoginSnapshot(sessionId,"WAITING_SCAN",null,"等待扫码确认"));}catch(RuntimeException e){sessions.remove(sessionId);session.close();throw new IllegalStateException("ADAPTER_UNAVAILABLE",e);}}}
    public boolean validate(String storageState){
        com.aiprovider.logging.BusinessOperationLogger.start("service.DouyinWebAdapter.validate", new String[] { "storageState" }, new Object[] { storageState });
        try(Playwright playwright=Playwright.create();Browser browser=launch(playwright);BrowserContext context=browser.newContext(new Browser.NewContextOptions().setStorageState(storageState))){Page page=context.newPage();page.navigate("https://creator.douyin.com/creator-micro/content/manage",new Page.NavigateOptions().setTimeout(timeoutMs));return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.validate", isAuthenticated(context,page.url()));}catch(RuntimeException e){return com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.validate", false);}}
    static boolean isAuthenticatedUrl(String url){return url!=null&&url.startsWith("https://creator.douyin.com/creator-micro/")&&!url.contains("/login");}
    static boolean isAuthenticatedCookieName(String name){return "sessionid".equals(name)||"sessionid_ss".equals(name)||"sid_guard".equals(name)||"passport_auth_status".equals(name);}
    private boolean isAuthenticated(BrowserContext context,String url){return isAuthenticatedUrl(url)&&context.cookies().stream().anyMatch(c->isAuthenticatedCookieName(c.name)&&c.value!=null&&!c.value.isEmpty());}
    private String qrImage(Page page){List<Locator> candidates=Arrays.asList(page.locator("canvas"),page.locator("img[src^='data:image']"),page.locator("img[src*='qrcode'],img[class*='qrcode'],img[class*='qr-code']"));Locator found=null;for(Locator list:candidates)for(int i=0;i<list.count();i++){Locator item=list.nth(i);BoundingBox box=item.boundingBox();if(item.isVisible()&&box!=null&&box.width>=120&&box.height>=120&&box.width<=420&&box.height<=420){if(found!=null&&!found.equals(item))continue;found=item;}}if(found==null)throw new IllegalStateException("ADAPTER_UNAVAILABLE");String src=found.getAttribute("src");if(src!=null&&src.startsWith("data:image"))return src;return "data:image/png;base64,"+Base64.getEncoder().encodeToString(found.screenshot());}
    private String riskMessage(Page page){String[] messages={"访问频繁","操作频繁","安全验证","验证码","环境异常","账号存在风险"};for(String message:messages)try{Locator item=page.getByText(message,new Page.GetByTextOptions().setExact(false)).first();if(item.count()>0&&item.isVisible())return message;}catch(PlaywrightException ignored){}return null;}
    private Browser launch(Playwright playwright){BrowserType.LaunchOptions options=new BrowserType.LaunchOptions().setHeadless(headless).setArgs(Arrays.asList("--disable-dev-shm-usage","--no-sandbox"));if(!executable.isEmpty())options.setExecutablePath(java.nio.file.Paths.get(executable));return playwright.chromium().launch(options);}
    private void closeAccountSessions(long accountId){for(LoginSession session:new ArrayList<>(sessions.values()))if(session.accountId==accountId&&sessions.remove(session.id,session))session.close();}
    private void close(BrowserContext context,Browser browser,Playwright playwright){if(context!=null)try{context.close();}catch(Exception ignored){}if(browser!=null)try{browser.close();}catch(Exception ignored){}if(playwright!=null)try{playwright.close();}catch(Exception ignored){}}
    @PreDestroy public void close(){
        com.aiprovider.logging.BusinessOperationLogger.start("service.DouyinWebAdapter.close", new String[] {}, new Object[] {});
        for(LoginSession session:sessions.values())session.close();sessions.clear();com.aiprovider.logging.BusinessOperationLogger.success("service.DouyinWebAdapter.close", null);
}
    static class LoginSnapshot{final String sessionId,status,image,message,storageState;LoginSnapshot(String sessionId,String status,String image,String message){this(sessionId,status,image,message,null);}LoginSnapshot(String sessionId,String status,String image,String message,String storageState){this.sessionId=sessionId;this.status=status;this.image=image;this.message=message;this.storageState=storageState;}}
    private class LoginSession{final String id;final long accountId,createdAt=System.currentTimeMillis();final Playwright playwright;final Browser browser;final BrowserContext context;final Page page;final String initialState;LoginSession(String id,long accountId,Playwright playwright,Browser browser,BrowserContext context,Page page,String initialState){this.id=id;this.accountId=accountId;this.playwright=playwright;this.browser=browser;this.context=context;this.page=page;this.initialState=initialState;}void close(){DouyinWebAdapter.this.close(context,browser,playwright);}}
}
