package com.aiprovider.service;

import com.aiprovider.mapper.PlatformAccountMapper;
import com.aiprovider.repository.PlatformAccountRepository;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Service;
import java.util.*;

@Service
@Order(20)
public class PlatformAccountLegacyMigrationService implements ApplicationRunner {
    private static final Logger log=LogManager.getLogger(PlatformAccountLegacyMigrationService.class);
    private final PlatformAccountRepository repository;private final ContentPlatformSecretCipher platformCipher;private final TwitterSessionCipher twitterCipher;private final ContentAiSecretCipher aiCipher;
    public PlatformAccountLegacyMigrationService(PlatformAccountRepository repository,ContentPlatformSecretCipher platformCipher,TwitterSessionCipher twitterCipher,ContentAiSecretCipher aiCipher){this.repository=repository;this.platformCipher=platformCipher;this.twitterCipher=twitterCipher;this.aiCipher=aiCipher;}
    @Override public void run(ApplicationArguments args){int requested=0,affected=0;for(Map<String,Object> row:repository.findLegacyTwitterAccounts()){requested++;migrate("TWITTER_ACCOUNT",row,"X","SOCIAL","TWITTER_WEB_PUBLISHER","STORAGE_STATE",twitterCipher,text(row.get("encryptedStorageState")),"浏览器会话");affected++;}for(Map<String,Object> row:repository.findLegacyCollectionAccounts()){requested++;String adapter=text(row.get("adapterType"));String type="TWITTER_API".equals(adapter)?"BEARER_TOKEN":"COOKIE";migrate("CONTENT_COLLECTION_ACCOUNT",row,"X","SOCIAL",adapter,type,null,text(row.get("credentialEncrypted")),text(row.get("credentialHint")));affected++;}for(Map<String,Object> row:repository.findLegacyContentAccounts()){requested++;migrate("CONTENT_ACCOUNT",row,"XIAOHONGSHU","SOCIAL",text(row.get("adapterType")),"STORAGE_STATE",null,text(row.get("sessionEncrypted")),text(row.get("sessionHint")));affected++;}for(Map<String,Object> row:repository.findLegacyGeminiConfigs()){if(text(row.get("apiKeyEncrypted"))==null)continue;requested++;migrate("CONTENT_GEMINI",row,"GEMINI","API_SERVICE","GEMINI_API","API_KEY",aiCipher,text(row.get("apiKeyEncrypted")),text(row.get("apiKeyHint")));affected++;}if(requested!=affected){log.warn("operation=platform-account.legacy-migrate requestedCount={} affectedRows={} resultStatus=FAILED errorCode=AFFECTED_ROWS_MISMATCH",requested,affected);throw new IllegalStateException("AFFECTED_ROWS_MISMATCH");}log.info("operation=platform-account.legacy-migrate requestedCount={} affectedRows={} resultStatus=SUCCESS",requested,affected);}
    private void migrate(String legacyType,Map<String,Object> row,String platform,String kind,String adapter,String secretType,Object legacyCipher,String legacyEncrypted,String hint){long legacyId=number(row.get("id"));Map<String,Object> existing=repository.findByLegacy(legacyType,legacyId);long accountId;if(existing==null){PlatformAccountMapper.AccountRecord record=new PlatformAccountMapper.AccountRecord();record.setPlatform(platform);record.setAccountKind(kind);record.setDisplayName(displayName(row,platform));record.setAccountHandle(text(row.get("username"))!=null?text(row.get("username")):text(row.get("accountHandle")));record.setAdapterType(adapter==null?platform+"_WEB":adapter);record.setPublicConfigJson("CONTENT_GEMINI".equals(legacyType)?"{\"apiBaseUrl\":\""+jsonEscape(text(row.get("apiBaseUrl")))+"\"}":null);record.setEnabled(row.get("enabled")==null||truth(row.get("enabled")));record.setConnectionStatus(connection(row,legacyEncrypted));record.setCredentialHint(hint);record.setLegacySourceType(legacyType);record.setLegacySourceId(legacyId);accountId=repository.insertAccount(record);if(legacyEncrypted!=null){String plain=legacyCipher instanceof TwitterSessionCipher?((TwitterSessionCipher)legacyCipher).decrypt(legacyEncrypted):legacyCipher instanceof ContentAiSecretCipher?((ContentAiSecretCipher)legacyCipher).decrypt(legacyEncrypted):platformCipher.decrypt(legacyEncrypted);repository.upsertSecret(accountId,secretType,platformCipher.encrypt(plain),hint==null?secretType:hint);}}else accountId=number(existing.get("id"));repository.linkLegacyConsumer(legacyType,legacyId,accountId);}
    private String connection(Map<String,Object> row,String encrypted){String status=text(row.get("connectionStatus"));if(status==null)status=text(row.get("sessionStatus"));if("CONNECTED".equals(status)&&encrypted!=null)return"CONNECTED";return encrypted==null?"NOT_CONFIGURED":"NOT_CONFIGURED";}private String displayName(Map<String,Object> row,String platform){String name=text(row.get("displayName"));if(name==null)name=text(row.get("username"));return name==null?platform+" 账号":name;}private String jsonEscape(String v){return v==null?"":v.replace("\\","\\\\").replace("\"","\\\"");}private String text(Object v){return v==null?null:String.valueOf(v);}private long number(Object v){return v instanceof Number?((Number)v).longValue():Long.parseLong(String.valueOf(v));}private boolean truth(Object v){return v instanceof Boolean?(Boolean)v:Boolean.parseBoolean(String.valueOf(v));}
}
