package com.aiprovider.service;

import com.aiprovider.model.vo.PlatformAccountVO;import com.aiprovider.repository.PlatformAccountRepository;import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.logging.log4j.LogManager;import org.apache.logging.log4j.Logger;import org.springframework.stereotype.Service;
import java.util.*;

@Service
public class PlatformAccountValidationService {
    private static final Logger log=LogManager.getLogger(PlatformAccountValidationService.class);
    private final PlatformAccountRepository repository;private final PlatformAccountCredentialService credentials;private final TwitterWebPublisher twitterWeb;private final TwitterPublicWebClient twitterPublic;private final TwitterTimelineClient twitterApi;private final XiaohongshuWebAdapter xhs;private final DouyinWebAdapter douyin;private final GeminiContentClient gemini;private final ObjectMapper json;
    public PlatformAccountValidationService(PlatformAccountRepository repository,PlatformAccountCredentialService credentials,TwitterWebPublisher twitterWeb,TwitterPublicWebClient twitterPublic,TwitterTimelineClient twitterApi,XiaohongshuWebAdapter xhs,DouyinWebAdapter douyin,GeminiContentClient gemini,ObjectMapper json){this.repository=repository;this.credentials=credentials;this.twitterWeb=twitterWeb;this.twitterPublic=twitterPublic;this.twitterApi=twitterApi;this.xhs=xhs;this.douyin=douyin;this.gemini=gemini;this.json=json;}
    public PlatformAccountVO validate(long id){Map<String,Object> row=repository.findAccount(id);if(row==null)throw new IllegalArgumentException("ACCOUNT_NOT_FOUND");String platform=text(row.get("platform"));if(!truth(row.get("enabled")))throw new IllegalStateException("ACCOUNT_DISABLED");String adapter=text(row.get("adapterType"));boolean valid;try{if("GEMINI".equals(platform)){String key=credentials.requireSecret(id,"GEMINI","API_KEY");valid=gemini.validateApiKey(apiBase(row),key);}else if("XIAOHONGSHU".equals(platform)){valid=xhs.validate(credentials.requireSecret(id,"XIAOHONGSHU","STORAGE_STATE"));}else if("DOUYIN".equals(platform)){valid=douyin.validate(credentials.requireSecret(id,"DOUYIN","STORAGE_STATE"));}else if("X".equals(platform)&&"TWITTER_WEB_PUBLISHER".equals(adapter)){valid=twitterWeb.validateSession(credentials.requireSecret(id,"X","STORAGE_STATE"));}else if("X".equals(platform)&&"TWITTER_WEB".equals(adapter)){String handle=text(row.get("accountHandle"));if(handle==null)throw new IllegalStateException("ACCOUNT_HANDLE_MISSING");twitterPublic.fetchLatest(handle.replaceFirst("^@",""),credentials.requireSecret(id,"X","COOKIE"));valid=true;}else if("X".equals(platform)&&"TWITTER_API".equals(adapter)){String uid=text(row.get("accountHandle"));if(uid==null||!uid.matches("[0-9]+"))throw new IllegalStateException("ACCOUNT_HANDLE_MISSING");twitterApi.fetch(uid,credentials.requireSecret(id,"X","BEARER_TOKEN"),1);valid=true;}else throw new IllegalStateException("ADAPTER_UNAVAILABLE");if(!valid)throw new IllegalStateException("CREDENTIAL_EXPIRED");repository.updateStatus(id,"CONNECTED",null,true,null,null);log.info("operation=platform-account.validate platform={} accountId={} requestedCount=1 affectedRows=1 resultStatus=SUCCESS",platform,id);return account(row,id);}catch(RuntimeException e){String code=e.getMessage()==null?"ADAPTER_UNAVAILABLE":e.getMessage();repository.updateStatus(id,"ERROR",null,true,limit(code,80),limit(code,1000));log.warn("operation=platform-account.validate platform={} accountId={} requestedCount=1 affectedRows=1 resultStatus=FAILED errorCode={}",platform,id,limit(code,80));throw e;}}
    private PlatformAccountVO account(Map<String,Object> row,long id){PlatformAccountVO vo=new PlatformAccountVO();vo.setId(id);vo.setPlatform(text(row.get("platform")));vo.setDisplayName(text(row.get("displayName")));vo.setConnectionStatus("CONNECTED");return vo;}
    private String apiBase(Map<String,Object> row){String raw=text(row.get("publicConfigJson"));if(raw==null)return "https://generativelanguage.googleapis.com";try{JsonNode node=json.readTree(raw);String value=node.path("apiBaseUrl").asText();return value.isEmpty()?"https://generativelanguage.googleapis.com":value.replaceAll("/+$","");}catch(Exception e){throw new IllegalStateException("PUBLIC_CONFIG_INVALID");}}
    private String text(Object v){return v==null?null:String.valueOf(v);}private boolean truth(Object value){return value instanceof Boolean?(Boolean)value:value!=null&&Boolean.parseBoolean(String.valueOf(value));}private String limit(String value,int max){if(value==null)return "UNKNOWN";return value.length()<=max?value:value.substring(0,max);}
}
