package com.aiprovider.service;

import com.aiprovider.mapper.PlatformAccountMapper;
import com.aiprovider.model.dto.*;
import com.aiprovider.model.vo.*;
import com.aiprovider.repository.PlatformAccountRepository;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.stereotype.Service;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class PlatformAccountService {
    private static final Logger log=LogManager.getLogger(PlatformAccountService.class);
    private static final Set<String> SOCIAL=new HashSet<>(Arrays.asList("X","XIAOHONGSHU","DOUYIN"));
    private static final Set<String> API=new HashSet<>(Collections.singletonList("GEMINI"));
    private static final Map<String,Set<String>> SECRET_TYPES=new HashMap<>();
    static{SECRET_TYPES.put("X",new HashSet<>(Arrays.asList("COOKIE","STORAGE_STATE","BEARER_TOKEN","PROXY")));SECRET_TYPES.put("XIAOHONGSHU",new HashSet<>(Arrays.asList("STORAGE_STATE","PROXY")));SECRET_TYPES.put("DOUYIN",new HashSet<>(Arrays.asList("STORAGE_STATE","PROXY")));SECRET_TYPES.put("GEMINI",new HashSet<>(Arrays.asList("API_KEY","PROXY")));}
    private final PlatformAccountRepository repository;private final ContentPlatformSecretCipher cipher;
    public PlatformAccountService(PlatformAccountRepository repository,ContentPlatformSecretCipher cipher){this.repository=repository;this.cipher=cipher;}
    public PlatformAccountVO create(PlatformAccountCreateDTO dto){if(dto==null)throw new IllegalArgumentException("账号不能为空");String platform=platform(dto.getPlatform());PlatformAccountMapper.AccountRecord record=new PlatformAccountMapper.AccountRecord();record.setPlatform(platform);record.setAccountKind(SOCIAL.contains(platform)?"SOCIAL":"API_SERVICE");record.setDisplayName(required(dto.getDisplayName(),"账号名称",100));record.setAccountHandle(limit(trim(dto.getAccountHandle()),200));record.setAdapterType(required(dto.getAdapterType(),"适配器",64));record.setPublicConfigJson(limit(trim(dto.getPublicConfigJson()),4000));record.setEnabled(dto.getEnabled()==null||dto.getEnabled());long id=repository.insertAccount(record);log.info("operation=platform-account.create platform={} accountId={} requestedCount=1 affectedRows=1 resultStatus=SUCCESS",platform,id);return get(id);}
    public PlatformAccountVO update(long id,PlatformAccountUpdateDTO dto){if(dto==null)throw new IllegalArgumentException("账号不能为空");Map<String,Object> current=repository.findAccount(id);if(current==null)throw new IllegalArgumentException("ACCOUNT_NOT_FOUND");PlatformAccountMapper.AccountRecord record=new PlatformAccountMapper.AccountRecord();record.setId(id);record.setPlatform(text(current.get("platform")));record.setAccountKind(text(current.get("accountKind")));record.setDisplayName(required(dto.getDisplayName(),"账号名称",100));record.setAccountHandle(limit(trim(dto.getAccountHandle()),200));record.setAdapterType(required(dto.getAdapterType(),"适配器",64));record.setPublicConfigJson(limit(trim(dto.getPublicConfigJson()),4000));record.setEnabled(dto.getEnabled()==null||dto.getEnabled());repository.updateAccount(record);log.info("operation=platform-account.update platform={} accountId={} requestedCount=1 affectedRows=1 resultStatus=SUCCESS",record.getPlatform(),id);return get(id);}
    public PlatformAccountVO get(long id){Map<String,Object> row=repository.findAccount(id);if(row==null)throw new IllegalArgumentException("ACCOUNT_NOT_FOUND");return vo(row);}
    public PlatformAccountPageVO page(String query,String platform,String kind,String status,int page,int size){int safePage=Math.max(1,page),safeSize=Math.max(1,Math.min(size,100));String q=empty(query)?null:query.trim(),p=empty(platform)?null:platform.trim().toUpperCase(Locale.ROOT),k=empty(kind)?null:kind.trim().toUpperCase(Locale.ROOT),s=empty(status)?null:status.trim().toUpperCase(Locale.ROOT);long total=repository.countAccounts(q,p,k,s);List<PlatformAccountVO> items=new ArrayList<>();for(Map<String,Object> row:repository.findAccounts(q,p,k,s,(safePage-1)*safeSize,safeSize))items.add(vo(row));return new PlatformAccountPageVO(items,total,safePage,safeSize);}
    public PlatformAccountVO updateSecret(long id,String type,PlatformSecretUpdateDTO dto){Map<String,Object> account=repository.findAccount(id);if(account==null)throw new IllegalArgumentException("ACCOUNT_NOT_FOUND");String platform=text(account.get("platform"));String secretType=required(type,"凭据类型",32).toUpperCase(Locale.ROOT);if(!SECRET_TYPES.getOrDefault(platform,Collections.emptySet()).contains(secretType))throw new IllegalArgumentException("PLATFORM_MISMATCH");String value=required(dto==null?null:dto.getValue(),"凭据",200000);String hint=empty(dto.getHint())?defaultHint(secretType):limit(dto.getHint().trim(),100);repository.upsertSecret(id,secretType,cipher.encrypt(value),hint);repository.updateStatus(id,"NOT_CONFIGURED",hint,false,null,null);log.info("operation=platform-account.secret-update platform={} accountId={} secretType={} requestedCount=1 affectedRows=1 resultStatus=SUCCESS",platform,id,secretType);return get(id);}
    public List<PlatformAccountUsageVO> usages(long id){if(repository.findAccount(id)==null)throw new IllegalArgumentException("ACCOUNT_NOT_FOUND");List<PlatformAccountUsageVO> result=new ArrayList<>();for(Map<String,Object> row:repository.findUsages(id))result.add(new PlatformAccountUsageVO(text(row.get("consumerType")),number(row.get("consumerId")),text(row.get("consumerName"))));return result;}
    public void archive(long id){Map<String,Object> account=repository.findAccount(id);if(account==null)throw new IllegalArgumentException("ACCOUNT_NOT_FOUND");repository.archiveAccount(id);log.info("operation=platform-account.archive platform={} accountId={} requestedCount=1 affectedRows=1 resultStatus=SUCCESS",account.get("platform"),id);}
    private PlatformAccountVO vo(Map<String,Object> row){PlatformAccountVO result=new PlatformAccountVO();long id=number(row.get("id"));result.setId(id);result.setPlatform(text(row.get("platform")));result.setAccountKind(text(row.get("accountKind")));result.setDisplayName(text(row.get("displayName")));result.setAccountHandle(text(row.get("accountHandle")));result.setAdapterType(text(row.get("adapterType")));result.setPublicConfigJson(text(row.get("publicConfigJson")));result.setEnabled(truth(row.get("enabled")));result.setConnectionStatus(text(row.get("connectionStatus")));result.setCredentialHint(text(row.get("credentialHint")));result.setLastValidatedAt(time(row.get("lastValidatedAt")));result.setLastConnectedAt(time(row.get("lastConnectedAt")));result.setLastErrorCode(text(row.get("lastErrorCode")));result.setLastErrorMessage(text(row.get("lastErrorMessage")));List<String> types=new ArrayList<>(),hints=new ArrayList<>();for(Map<String,Object> secret:repository.findSecretSummaries(id)){types.add(text(secret.get("secretType")));hints.add(text(secret.get("secretHint")));}result.setCredentialTypes(types);result.setCredentialHints(hints);return result;}
    private String platform(String value){String p=required(value,"平台",32).toUpperCase(Locale.ROOT);if(!SOCIAL.contains(p)&&!API.contains(p))throw new IllegalArgumentException("不支持的平台");return p;}private String required(String v,String name,int max){if(v==null||v.trim().isEmpty())throw new IllegalArgumentException(name+"不能为空");return limit(v.trim(),max);}private String defaultHint(String t){return "API_KEY".equals(t)?"API Key":"BEARER_TOKEN".equals(t)?"Bearer Token":"COOKIE".equals(t)?"Cookie 会话":"STORAGE_STATE".equals(t)?"浏览器会话":"代理凭据";}private String trim(String v){return v==null?null:v.trim();}private boolean empty(String v){return v==null||v.trim().isEmpty();}private String limit(String v,int max){return v==null?null:v.length()<=max?v:v.substring(0,max);}private String text(Object v){return v==null?null:String.valueOf(v);}private long number(Object v){return v instanceof Number?((Number)v).longValue():Long.parseLong(String.valueOf(v));}private boolean truth(Object v){return v instanceof Boolean?(Boolean)v:Boolean.parseBoolean(String.valueOf(v));}private LocalDateTime time(Object v){if(v==null)return null;if(v instanceof LocalDateTime)return(LocalDateTime)v;if(v instanceof Timestamp)return((Timestamp)v).toLocalDateTime();return LocalDateTime.parse(String.valueOf(v).replace(' ','T'));}
}
