package com.aiprovider.mapper;

import com.aiprovider.mapper.row.BacktestExperimentRow;
import org.apache.ibatis.annotations.*;
import java.time.Instant;
import java.util.Collection;
import java.util.List;

@Mapper
public interface BacktestExperimentMapper {
    String COLUMNS="Id,ExperimentId,DatasetId,Provider,MarketType,DataType,Symbol,IntervalCode,StrategyCode,StrategyVersion,ParameterGridJson,CandidateCount,TrainingStartOpenTimeMs,TrainingEndOpenTimeMs,ValidationStartOpenTimeMs,ValidationEndOpenTimeMs,OrderAmount,FeeRate,ForceCloseAtEnd,Status,ErrorCode,ErrorMessage,CreatedAt,UpdatedAt,StartedAt,FinishedAt";
    @Results(id="backtestExperimentRow",value={
        @Result(column="Id",property="id"),@Result(column="ExperimentId",property="experimentId"),@Result(column="DatasetId",property="datasetId"),@Result(column="Provider",property="provider"),@Result(column="MarketType",property="marketType"),@Result(column="DataType",property="dataType"),@Result(column="Symbol",property="symbol"),@Result(column="IntervalCode",property="intervalCode"),@Result(column="StrategyCode",property="strategyCode"),@Result(column="StrategyVersion",property="strategyVersion"),@Result(column="ParameterGridJson",property="parameterGridJson"),@Result(column="CandidateCount",property="candidateCount"),@Result(column="TrainingStartOpenTimeMs",property="trainingStartOpenTimeMs"),@Result(column="TrainingEndOpenTimeMs",property="trainingEndOpenTimeMs"),@Result(column="ValidationStartOpenTimeMs",property="validationStartOpenTimeMs"),@Result(column="ValidationEndOpenTimeMs",property="validationEndOpenTimeMs"),@Result(column="OrderAmount",property="orderAmount"),@Result(column="FeeRate",property="feeRate"),@Result(column="ForceCloseAtEnd",property="forceCloseAtEnd"),@Result(column="Status",property="status"),@Result(column="ErrorCode",property="errorCode"),@Result(column="ErrorMessage",property="errorMessage"),@Result(column="CreatedAt",property="createdAt"),@Result(column="UpdatedAt",property="updatedAt"),@Result(column="StartedAt",property="startedAt"),@Result(column="FinishedAt",property="finishedAt")})
    @Select("SELECT "+COLUMNS+" FROM q_backtest_experiment WHERE ExperimentId=#{id}") BacktestExperimentRow findByExperimentId(@Param("id") String id);
    @ResultMap("backtestExperimentRow") @Select("<script>SELECT "+COLUMNS+" FROM q_backtest_experiment WHERE ExperimentId IN <foreach collection='experimentIds' item='experimentId' open='(' separator=',' close=')'>#{experimentId}</foreach></script>") List<BacktestExperimentRow> findByExperimentIds(@Param("experimentIds") Collection<String> experimentIds);
    @Insert("INSERT INTO q_backtest_experiment(ExperimentId,DatasetId,Provider,MarketType,DataType,Symbol,IntervalCode,StrategyCode,StrategyVersion,ParameterGridJson,CandidateCount,TrainingStartOpenTimeMs,TrainingEndOpenTimeMs,ValidationStartOpenTimeMs,ValidationEndOpenTimeMs,OrderAmount,FeeRate,ForceCloseAtEnd,Status,CreatedAt,UpdatedAt) VALUES(#{experimentId},#{datasetId},#{provider},#{marketType},#{dataType},#{symbol},#{intervalCode},#{strategyCode},#{strategyVersion},#{parameterGridJson},#{candidateCount},#{trainingStartOpenTimeMs},#{trainingEndOpenTimeMs},#{validationStartOpenTimeMs},#{validationEndOpenTimeMs},#{orderAmount},#{feeRate},#{forceCloseAtEnd},'QUEUED',#{createdAt},#{updatedAt})") int insert(BacktestExperimentRow row);
    @ResultMap("backtestExperimentRow") @Select("<script>SELECT "+COLUMNS+" FROM q_backtest_experiment WHERE 1=1 <if test='status != null'>AND Status=#{status}</if><if test='symbol != null'>AND Symbol=#{symbol}</if><if test='strategyCode != null'>AND StrategyCode=#{strategyCode}</if> ORDER BY CreatedAt DESC, Id DESC LIMIT #{limit} OFFSET #{offset}</script>") List<BacktestExperimentRow> findPage(@Param("status")String status,@Param("symbol")String symbol,@Param("strategyCode")String strategyCode,@Param("limit")int limit,@Param("offset")long offset);
    @Select("<script>SELECT COUNT(*) FROM q_backtest_experiment WHERE 1=1 <if test='status != null'>AND Status=#{status}</if><if test='symbol != null'>AND Symbol=#{symbol}</if><if test='strategyCode != null'>AND StrategyCode=#{strategyCode}</if></script>") long count(@Param("status")String status,@Param("symbol")String symbol,@Param("strategyCode")String strategyCode);
    @ResultMap("backtestExperimentRow") @Select("SELECT "+COLUMNS+" FROM q_backtest_experiment WHERE Status IN ('QUEUED','RUNNING') ORDER BY CreatedAt ASC, Id ASC") List<BacktestExperimentRow> findNonTerminal();
    @Update("UPDATE q_backtest_experiment SET Status='RUNNING',StartedAt=COALESCE(StartedAt,#{now}),UpdatedAt=#{now} WHERE ExperimentId=#{experimentId} AND Status='QUEUED'") int markRunning(@Param("experimentId")String experimentId,@Param("now")Instant now);
    @Update("UPDATE q_backtest_experiment SET Status=#{status},FinishedAt=#{finishedAt},UpdatedAt=#{now} WHERE ExperimentId=#{experimentId} AND Status='RUNNING'") int complete(@Param("experimentId")String experimentId,@Param("status")String status,@Param("finishedAt")Instant finishedAt,@Param("now")Instant now);
    @Update("UPDATE q_backtest_experiment SET Status='FAILED',ErrorCode=#{code},ErrorMessage=#{message},FinishedAt=#{now},UpdatedAt=#{now} WHERE ExperimentId=#{experimentId} AND Status IN ('QUEUED','RUNNING')") int fail(@Param("experimentId")String experimentId,@Param("code")String code,@Param("message")String message,@Param("now")Instant now);
    @Update("UPDATE q_backtest_experiment SET UpdatedAt=#{now} WHERE ExperimentId=#{experimentId} AND Status IN ('QUEUED','RUNNING')") int touchUpdatedAt(@Param("experimentId")String experimentId,@Param("now")Instant now);
    @Update("UPDATE q_backtest_experiment SET Status=#{status},StartedAt=IF(#{status}='RUNNING',COALESCE(StartedAt,#{now}),StartedAt),FinishedAt=#{finishedAt},ErrorCode=#{errorCode},ErrorMessage=#{errorMessage},UpdatedAt=#{now} WHERE ExperimentId=#{experimentId} AND Status IN ('QUEUED','RUNNING')") int updateAggregate(@Param("experimentId")String experimentId,@Param("status")String status,@Param("finishedAt")Instant finishedAt,@Param("errorCode")String errorCode,@Param("errorMessage")String errorMessage,@Param("now")Instant now);
}
