package com.aiprovider.mapper;

import com.aiprovider.mapper.row.BacktestRunRow;
import org.apache.ibatis.annotations.*;
import java.math.BigDecimal; import java.time.Instant; import java.util.List;

@Mapper public interface BacktestRunMapper {
    String COLUMNS = "Id,RunId,DatasetId,DatasetLastValidatedAt,DatasetLastSyncTaskId,Provider,MarketType,DataType,Symbol,IntervalCode,StartOpenTimeMs,EndOpenTimeExclusiveMs,StrategyCode,StrategyVersion,RequestedParametersJson,ResolvedParametersJson,OrderAmount,FeeRate,ForceCloseAtEnd,Status,ProgressPercent,BarCount,TradeCount,WinningTradeCount,LosingTradeCount,BreakEvenTradeCount,WinRate,GrossProfit,GrossLoss,NetProfit,TotalReturnRatio,MaximumDrawdownRatio,ProfitFactor,AverageTradeReturnRatio,BuyAndHoldReturnRatio,TotalFees,ExecutionModel,WarningsJson,EquityPointCount,ErrorCode,ErrorMessage,QueuedAt,StartedAt,FinishedAt,UpdatedAt";
    @Results(id="backtestRunRow", value={
        @Result(column="Id",property="id"),@Result(column="RunId",property="runId"),@Result(column="DatasetId",property="datasetId"),@Result(column="DatasetLastValidatedAt",property="datasetLastValidatedAt"),@Result(column="DatasetLastSyncTaskId",property="datasetLastSyncTaskId"),@Result(column="Provider",property="provider"),@Result(column="MarketType",property="marketType"),@Result(column="DataType",property="dataType"),@Result(column="Symbol",property="symbol"),@Result(column="IntervalCode",property="intervalCode"),@Result(column="StartOpenTimeMs",property="startOpenTimeMs"),@Result(column="EndOpenTimeExclusiveMs",property="endOpenTimeExclusiveMs"),@Result(column="StrategyCode",property="strategyCode"),@Result(column="StrategyVersion",property="strategyVersion"),@Result(column="RequestedParametersJson",property="requestedParametersJson"),@Result(column="ResolvedParametersJson",property="resolvedParametersJson"),@Result(column="OrderAmount",property="orderAmount"),@Result(column="FeeRate",property="feeRate"),@Result(column="ForceCloseAtEnd",property="forceCloseAtEnd"),@Result(column="Status",property="status"),@Result(column="ProgressPercent",property="progressPercent"),@Result(column="BarCount",property="barCount"),@Result(column="TradeCount",property="tradeCount"),@Result(column="WinningTradeCount",property="winningTradeCount"),@Result(column="LosingTradeCount",property="losingTradeCount"),@Result(column="BreakEvenTradeCount",property="breakEvenTradeCount"),@Result(column="WinRate",property="winRate"),@Result(column="GrossProfit",property="grossProfit"),@Result(column="GrossLoss",property="grossLoss"),@Result(column="NetProfit",property="netProfit"),@Result(column="TotalReturnRatio",property="totalReturnRatio"),@Result(column="MaximumDrawdownRatio",property="maximumDrawdownRatio"),@Result(column="ProfitFactor",property="profitFactor"),@Result(column="AverageTradeReturnRatio",property="averageTradeReturnRatio"),@Result(column="BuyAndHoldReturnRatio",property="buyAndHoldReturnRatio"),@Result(column="TotalFees",property="totalFees"),@Result(column="ExecutionModel",property="executionModel"),@Result(column="WarningsJson",property="warningsJson"),@Result(column="EquityPointCount",property="equityPointCount"),@Result(column="ErrorCode",property="errorCode"),@Result(column="ErrorMessage",property="errorMessage"),@Result(column="QueuedAt",property="queuedAt"),@Result(column="StartedAt",property="startedAt"),@Result(column="FinishedAt",property="finishedAt"),@Result(column="UpdatedAt",property="updatedAt")})
    @Select("SELECT " + COLUMNS + " FROM q_backtest_run WHERE RunId=#{runId}") BacktestRunRow findByRunId(@Param("runId") String runId);
    @Insert("INSERT INTO q_backtest_run(RunId,DatasetId,Provider,MarketType,DataType,Symbol,IntervalCode,StartOpenTimeMs,EndOpenTimeExclusiveMs,StrategyCode,StrategyVersion,RequestedParametersJson,OrderAmount,FeeRate,ForceCloseAtEnd,Status,ProgressPercent,QueuedAt,UpdatedAt) VALUES(#{runId},#{datasetId},#{provider},#{marketType},#{dataType},#{symbol},#{intervalCode},#{startOpenTimeMs},#{endOpenTimeExclusiveMs},#{strategyCode},#{strategyVersion},#{requestedParametersJson},#{orderAmount},#{feeRate},#{forceCloseAtEnd},'QUEUED',0,#{queuedAt},#{updatedAt})") int insert(BacktestRunRow row);
    @ResultMap("backtestRunRow") @Select("<script>SELECT " + COLUMNS + " FROM q_backtest_run WHERE 1=1 <if test='status != null'>AND Status=#{status}</if><if test='symbol != null'>AND Symbol=#{symbol}</if><if test='strategyCode != null'>AND StrategyCode=#{strategyCode}</if> ORDER BY QueuedAt DESC, Id DESC LIMIT #{limit} OFFSET #{offset}</script>") List<BacktestRunRow> findPage(@Param("status") String status,@Param("symbol") String symbol,@Param("strategyCode") String strategyCode,@Param("limit") int limit,@Param("offset") int offset);
    @Select("<script>SELECT COUNT(*) FROM q_backtest_run WHERE 1=1 <if test='status != null'>AND Status=#{status}</if><if test='symbol != null'>AND Symbol=#{symbol}</if><if test='strategyCode != null'>AND StrategyCode=#{strategyCode}</if></script>") long count(@Param("status") String status,@Param("symbol") String symbol,@Param("strategyCode") String strategyCode);
    @ResultMap("backtestRunRow") @Select("SELECT " + COLUMNS + " FROM q_backtest_run WHERE Status IN ('QUEUED','LOADING_SNAPSHOT','RUNNING_ENGINE','PERSISTING') ORDER BY QueuedAt ASC, Id ASC") List<BacktestRunRow> findNonTerminal();
    @Update("UPDATE q_backtest_run SET Status=#{toStatus},ProgressPercent=#{progress},UpdatedAt=#{now},StartedAt=IF(#{toStatus}='LOADING_SNAPSHOT',#{now},StartedAt) WHERE RunId=#{runId} AND Status=#{fromStatus}") int transition(@Param("runId") String runId,@Param("fromStatus") String fromStatus,@Param("toStatus") String toStatus,@Param("progress") BigDecimal progress,@Param("now") Instant now);
    @Update("UPDATE q_backtest_run SET DatasetLastValidatedAt=#{datasetLastValidatedAt},DatasetLastSyncTaskId=#{datasetLastSyncTaskId},Provider=#{provider},MarketType=#{marketType},DataType=#{dataType},Symbol=#{symbol},IntervalCode=#{intervalCode},BarCount=#{barCount},UpdatedAt=#{updatedAt} WHERE RunId=#{runId}") int updateSnapshot(BacktestRunRow row);
    @Update("UPDATE q_backtest_run SET ResolvedParametersJson=#{resolvedParametersJson},BarCount=#{barCount},TradeCount=#{tradeCount},WinningTradeCount=#{winningTradeCount},LosingTradeCount=#{losingTradeCount},BreakEvenTradeCount=#{breakEvenTradeCount},WinRate=#{winRate},GrossProfit=#{grossProfit},GrossLoss=#{grossLoss},NetProfit=#{netProfit},TotalReturnRatio=#{totalReturnRatio},MaximumDrawdownRatio=#{maximumDrawdownRatio},ProfitFactor=#{profitFactor},AverageTradeReturnRatio=#{averageTradeReturnRatio},BuyAndHoldReturnRatio=#{buyAndHoldReturnRatio},TotalFees=#{totalFees},ExecutionModel=#{executionModel},WarningsJson=#{warningsJson},EquityPointCount=#{equityPointCount},Status='COMPLETED',ProgressPercent=100,FinishedAt=#{finishedAt},UpdatedAt=#{updatedAt} WHERE RunId=#{runId} AND Status='PERSISTING'") int complete(BacktestRunRow row);
    @Update("UPDATE q_backtest_run SET Status='FAILED',ErrorCode=#{code},ErrorMessage=#{message},FinishedAt=#{now},UpdatedAt=#{now} WHERE RunId=#{runId} AND Status NOT IN ('COMPLETED','FAILED')") int fail(@Param("runId") String runId,@Param("code") String code,@Param("message") String message,@Param("now") Instant now);
}
