package com.aiprovider.mapper;
import com.aiprovider.mapper.row.BacktestTradeRow; import org.apache.ibatis.annotations.*; import java.util.List;
@Mapper public interface BacktestTradeMapper {
 String COLUMNS="Id,RunId,TradeNo,EntrySignalIndex,EntryIndex,EntryTimeMs,EntryPrice,ExitSignalIndex,ExitIndex,ExitTimeMs,ExitPrice,Amount,GrossProfit,Fee,NetProfit,ReturnRatio,BarsHeld,ForcedExit,ExitReason";
 @Results(id="backtestTradeRow",value={@Result(column="Id",property="id"),@Result(column="RunId",property="runId"),@Result(column="TradeNo",property="tradeNo"),@Result(column="EntrySignalIndex",property="entrySignalIndex"),@Result(column="EntryIndex",property="entryIndex"),@Result(column="EntryTimeMs",property="entryTimeMs"),@Result(column="EntryPrice",property="entryPrice"),@Result(column="ExitSignalIndex",property="exitSignalIndex"),@Result(column="ExitIndex",property="exitIndex"),@Result(column="ExitTimeMs",property="exitTimeMs"),@Result(column="ExitPrice",property="exitPrice"),@Result(column="Amount",property="amount"),@Result(column="GrossProfit",property="grossProfit"),@Result(column="Fee",property="fee"),@Result(column="NetProfit",property="netProfit"),@Result(column="ReturnRatio",property="returnRatio"),@Result(column="BarsHeld",property="barsHeld"),@Result(column="ForcedExit",property="forcedExit"),@Result(column="ExitReason",property="exitReason")})
 @Insert("<script>INSERT INTO q_backtest_trade(RunId,TradeNo,EntrySignalIndex,EntryIndex,EntryTimeMs,EntryPrice,ExitSignalIndex,ExitIndex,ExitTimeMs,ExitPrice,Amount,GrossProfit,Fee,NetProfit,ReturnRatio,BarsHeld,ForcedExit,ExitReason) VALUES <foreach collection='rows' item='r' separator=','>(#{r.runId},#{r.tradeNo},#{r.entrySignalIndex},#{r.entryIndex},#{r.entryTimeMs},#{r.entryPrice},#{r.exitSignalIndex},#{r.exitIndex},#{r.exitTimeMs},#{r.exitPrice},#{r.amount},#{r.grossProfit},#{r.fee},#{r.netProfit},#{r.returnRatio},#{r.barsHeld},#{r.forcedExit},#{r.exitReason})</foreach></script>") int insertBatch(@Param("rows") List<BacktestTradeRow> rows);
 @ResultMap("backtestTradeRow") @Select("SELECT " + COLUMNS + " FROM q_backtest_trade WHERE RunId=#{runId} ORDER BY TradeNo ASC LIMIT #{limit} OFFSET #{offset}") List<BacktestTradeRow> findPage(@Param("runId") String runId,@Param("limit") int limit,@Param("offset") long offset);
 @Select("SELECT COUNT(*) FROM q_backtest_trade WHERE RunId=#{runId}") long count(@Param("runId") String runId);
 @Delete("DELETE FROM q_backtest_trade WHERE RunId=#{runId}") int deleteByRunId(@Param("runId") String runId);
}
