import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowClockwise, CaretLeft, CaretRight, CheckCircle, CircleNotch, Gauge, MicrophoneStage, PencilSimple, WarningCircle, X } from "@phosphor-icons/react";
import UiSearchField from "./UiSearchField";
import UiToast from "./UiToast";
import { readJsonResponse } from "./apiResponse";
import "./AsrRecords.css";

const emptyFilters={keyword:"",status:"",provider:"",model:"",startTime:"",endTime:""};
const VALID_STATUSES=new Set(["PROCESSING","SUCCESS","FAILED"]);
const numberFormatter=new Intl.NumberFormat("zh-CN");
const numericRecordFields=["audioSize","audioDurationMs","processingTimeMs"];
const numericQuotaFields=["dailyRequestCount","dailyRequestLimit","dailyRequestsRemaining","hourlyAudioLimitSeconds","hourlyAudioUsedSeconds","hourlyAudioRemainingSeconds","dailyAudioLimitSeconds","dailyAudioUsedSeconds","dailyAudioRemainingSeconds"];
const finiteNumber=(value,label,{nullable=false}={})=>{if(value==null||value===""){if(nullable)return null;throw new Error(`${label} 数值异常`);}const result=Number(value);if(!Number.isFinite(result))throw new Error(`${label} 数值异常`);return result;};
const formatNumber=(value,label)=>numberFormatter.format(finiteNumber(value,label));
const normalizeStatus=(value)=>{const status=String(value??"").trim().toUpperCase();if(!VALID_STATUSES.has(status))throw new Error("语音识别记录状态异常");return status;};
const normalizeRecord=(value,label="语音识别记录")=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label}响应异常`);const record={...value,status:normalizeStatus(value.status)};numericRecordFields.forEach((field)=>{record[field]=finiteNumber(value[field],`${label}.${field}`,{nullable:field!=="audioSize"});});return record;};
const normalizePage=(value)=>{if(!value||typeof value!=="object"||Array.isArray(value)||!Array.isArray(value.items))throw new Error("语音识别记录列表响应异常");const data={...value};["total","page","pages","pageSize"].forEach((field)=>{data[field]=finiteNumber(value[field],`语音识别记录.${field}`);});if(data.total<0||data.page<1||data.pages<1||data.pageSize<1)throw new Error("语音识别记录分页数据异常");data.items=data.items.map((item)=>normalizeRecord(item));return data;};
const normalizeQuota=(value)=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("语音识别配额响应异常");const quota={...value};numericQuotaFields.forEach((field)=>{quota[field]=finiteNumber(value[field],`语音识别配额.${field}`,{nullable:field==="dailyRequestLimit"||field==="dailyRequestsRemaining"});});if((quota.dailyRequestLimit==null)!==(quota.dailyRequestsRemaining==null))throw new Error("语音识别配额请求快照异常");return quota;};
const normalizeFilters=(value)=>{if(!value||typeof value!=="object"||Array.isArray(value)||!Array.isArray(value.providerModels))throw new Error("语音识别筛选响应异常");return {...value,providerModels:value.providerModels.map((item)=>{if(!item||typeof item!=="object"||Array.isArray(item)||typeof item.provider!=="string"||typeof item.model!=="string")throw new Error("语音识别筛选项响应异常");return item;})};};
async function api(path,options,normalize){const response=await fetch(path,options);const body=await readJsonResponse(response,"语音识别记录响应异常");if(!response.ok||body.code!==200)throw new Error(body.message||`请求失败 · ${response.status}`);if(normalize===null)return body.data;if(body.data==null)throw new Error("语音识别记录响应缺少数据");return normalize(body.data);}
const duration=(value,label)=>value==null?"—":value<1000?`${formatNumber(value,label)} ms`:`${numberFormatter.format(Number((value/1000).toFixed(1)))} 秒`;
const size=(value)=>{const bytes=finiteNumber(value,"音频大小");if(bytes<1024)return `${formatNumber(bytes,"音频大小")} B`;if(bytes<1024*1024)return `${numberFormatter.format(Number((bytes/1024).toFixed(1)))} KB`;return `${numberFormatter.format(Number((bytes/1024/1024).toFixed(2)))} MB`;};
const dateTime=(value)=>value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"—";
const timeAmount=(seconds,label)=>{if(seconds==null)return "—";const value=Math.max(0,finiteNumber(seconds,label));const hours=Math.floor(value/3600);const minutes=Math.floor((value%3600)/60);const rest=Math.floor(value%60);return [hours&&`${formatNumber(hours,label)} 小时`,minutes&&`${formatNumber(minutes,label)} 分`,(!hours&&!minutes||rest)&&`${formatNumber(rest,label)} 秒`].filter(Boolean).join(" ");};
const percent=(used,limit)=>limit>0?Math.min(100,Math.max(0,finiteNumber(used,"已用额度")/finiteNumber(limit,"额度")*100)):0;

export default function AsrRecords(){
  const [filters,setFilters]=useState(emptyFilters);const [page,setPage]=useState(1);const [data,setData]=useState({items:[],total:0,pages:1,pageSize:20});const [quota,setQuota]=useState(null);const [options,setOptions]=useState({providerModels:[]});const [selected,setSelected]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const query=useMemo(()=>{const params=new URLSearchParams({page:String(page),pageSize:"20"});Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key,key.endsWith("Time")?new Date(value).toISOString():value);});return params.toString();},[filters,page]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [records,currentQuota]=await Promise.all([api(`/api/admin/asr/records?${query}`,undefined,normalizePage),api("/api/admin/asr/records/quota",undefined,normalizeQuota)]);setData(records);setQuota(currentQuota);}catch(e){setError(e.message);}finally{setLoading(false);}},[query]);
  useEffect(()=>{load();},[load]);useEffect(()=>{api("/api/admin/asr/records/filters",undefined,normalizeFilters).then(setOptions).catch((e)=>setError(e.message));},[]);
  const updateFilter=(key,value)=>{setPage(1);setFilters((current)=>({...current,[key]:value,...(key==="provider"?{model:""}:{})}));};
  const models=useMemo(()=>[...new Set(options.providerModels.filter((item)=>!filters.provider||item.provider===filters.provider).map((item)=>item.model))],[options.providerModels,filters.provider]);
  const open=async(recordId)=>{if(!recordId)return;setError("");try{setSelected(await api(`/api/admin/asr/records/${recordId}`,undefined,(value)=>normalizeRecord(value,"语音识别详情")));}catch(e){setError(e.message);}};
  const saveCorrection=async()=>{try{await api(`/api/admin/asr/records/${selected.recordId}/correction`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({correctedText:selected.correctedText||""})},null);setNotice("人工修正文字已保存");setSelected(await api(`/api/admin/asr/records/${selected.recordId}`,undefined,(value)=>normalizeRecord(value,"语音识别详情")));load();}catch(e){setError(e.message);}};
  const statusLabel={PROCESSING:"处理中",SUCCESS:"成功",FAILED:"失败"};const statusClass={PROCESSING:"processing",SUCCESS:"success",FAILED:"failed"};
  return <section className="asr-records-page">
    <header className="asr-head"><div><span><MicrophoneStage weight="fill"/>云服务</span><h1>语音识别记录</h1><p>逐条播放 AIMaid 录音，核对识别结果并保存人工修正。</p></div><button type="button" onClick={load} disabled={loading}><ArrowClockwise className={loading?"is-spinning":""}/>{loading?"加载中":"刷新"}</button></header>
    {quota&&<section className="asr-quota-card" aria-label="Groq 语音识别额度"><header><div><span><Gauge weight="fill"/>Groq 额度</span><strong>{quota.model}</strong></div><small>{quota.providerSnapshotAt?`Groq 快照 ${dateTime(quota.providerSnapshotAt)}`:"完成一次真实转写后获取 Groq 请求额度"}</small></header><div className="asr-quota-grid">
      <article><span>今日识别请求</span><strong>{formatNumber(quota.dailyRequestCount,"今日识别请求")} 次</strong><small>{quota.dailyRequestLimit==null?"Groq 当前额度暂无快照":`Groq 当前剩余 ${formatNumber(quota.dailyRequestsRemaining,"Groq 当前请求剩余")} / ${formatNumber(quota.dailyRequestLimit,"Groq 请求总额")}${quota.requestsResetAfter?` · ${quota.requestsResetAfter} 后恢复对应额度`:""}`}</small></article>
      <article><span>近 1 小时音频剩余</span><strong>{timeAmount(quota.hourlyAudioRemainingSeconds,"近一小时音频剩余")}</strong><small>本站已用 {timeAmount(quota.hourlyAudioUsedSeconds,"近一小时音频已用")} / {timeAmount(quota.hourlyAudioLimitSeconds,"近一小时音频额度")}</small><progress aria-label="近一小时音频已用比例" max="100" value={percent(quota.hourlyAudioUsedSeconds,quota.hourlyAudioLimitSeconds)}/></article>
      <article><span>今日音频剩余</span><strong>{timeAmount(quota.dailyAudioRemainingSeconds,"今日音频剩余")}</strong><small>本站已用 {timeAmount(quota.dailyAudioUsedSeconds,"今日音频已用")} / {timeAmount(quota.dailyAudioLimitSeconds,"今日音频额度")}</small><progress aria-label="今日音频已用比例" max="100" value={percent(quota.dailyAudioUsedSeconds,quota.dailyAudioLimitSeconds)}/></article>
    </div><p>今日请求按上海自然日统计 AIProvider 数据库记录；Groq 当前剩余来自组织级滚动额度响应头，不代表今日累计请求数。音频用量只统计经 AIProvider 成功转写的记录。</p></section>}
    <div className="asr-filter-card" aria-label="语音识别记录筛选"><UiSearchField aria-label="搜索识别文字" placeholder="搜索识别文字" value={filters.keyword} onChange={(e)=>updateFilter("keyword",e.target.value)}/><label><span>状态</span><select aria-label="按状态筛选" value={filters.status} onChange={(e)=>updateFilter("status",e.target.value)}><option value="">全部状态</option><option value="PROCESSING">处理中</option><option value="SUCCESS">成功</option><option value="FAILED">失败</option></select></label><label><span>Provider</span><select aria-label="按 Provider 筛选" value={filters.provider} onChange={(e)=>updateFilter("provider",e.target.value)}><option value="">全部 Provider</option>{[...new Set(options.providerModels.map((item)=>item.provider))].map((item)=><option key={item}>{item}</option>)}</select></label><label><span>模型</span><select aria-label="按模型筛选" value={filters.model} onChange={(e)=>updateFilter("model",e.target.value)}><option value="">全部模型</option>{models.map((item)=><option key={item}>{item}</option>)}</select></label><label><span>开始时间</span><input aria-label="开始时间" type="datetime-local" value={filters.startTime} onChange={(e)=>updateFilter("startTime",e.target.value)}/></label><label><span>结束时间</span><input aria-label="结束时间" type="datetime-local" value={filters.endTime} onChange={(e)=>updateFilter("endTime",e.target.value)}/></label></div>
    <div className="asr-table-card"><div className="asr-table-meta"><strong>{formatNumber(data.total,"记录总数")} 条记录</strong><span>第 {formatNumber(page,"当前页")} / {formatNumber(Math.max(1,data.pages),"总页数")} 页</span></div><div className="asr-table-wrap"><table><thead><tr><th>创建时间</th><th>音频</th><th>Provider / 模型</th><th>识别文字</th><th>处理耗时</th><th>状态</th><th>操作</th></tr></thead><tbody>
      {!loading&&data.items.map((item)=><tr key={item.recordId||`${item.requestId}-${item.createdAt}`}><td>{dateTime(item.createdAt)}</td><td>{duration(item.audioDurationMs,"音频时长")}<small>{size(item.audioSize)}</small></td><td>{item.provider}<small>{item.model}</small></td><td className="asr-text-preview">{item.recognizedText||item.errorMessage||"—"}</td><td>{duration(item.processingTimeMs,"处理耗时")}</td><td><span className={`asr-status is-${statusClass[item.status]}`}>{item.status==="SUCCESS"?<CheckCircle/>:item.status==="PROCESSING"?<CircleNotch className="is-spinning"/>:<WarningCircle/>}{statusLabel[item.status]}</span></td><td><button type="button" className="asr-detail-button" disabled={!item.recordId} onClick={()=>open(item.recordId)}>查看详情</button></td></tr>)}
      {!loading&&!data.items.length&&<tr><td colSpan="7" className="asr-empty">没有符合条件的语音识别记录</td></tr>}{loading&&<tr><td colSpan="7" className="asr-empty">正在加载记录…</td></tr>}
    </tbody></table></div><footer className="asr-pagination"><button type="button" aria-label="上一页" disabled={page<=1||loading} onClick={()=>setPage((value)=>value-1)}><CaretLeft/></button><span>{formatNumber(page,"当前页")} / {formatNumber(Math.max(1,data.pages),"总页数")}</span><button type="button" aria-label="下一页" disabled={page>=data.pages||loading} onClick={()=>setPage((value)=>value+1)}><CaretRight/></button></footer></div>
    {selected&&<div className="asr-dialog-backdrop"><section className="asr-dialog" role="dialog" aria-modal="true" aria-label={`语音识别详情 ${selected.recordId}`}><header><div><span>{selected.recordId}</span><h2>语音识别记录</h2></div><button type="button" aria-label="关闭语音识别详情" onClick={()=>setSelected(null)}><X/></button></header><audio controls preload="metadata" src={selected.audioUrl}>当前浏览器不支持音频播放。</audio><dl className="asr-detail-meta"><div><dt>记录 ID</dt><dd>{selected.recordId}</dd></div><div><dt>请求 ID</dt><dd>{selected.requestId}</dd></div><div><dt>会话 ID</dt><dd>{selected.sessionId||"无会话 ID"}</dd></div><div><dt>Provider / 模型</dt><dd>{selected.provider}<small>{selected.model}</small></dd></div><div><dt>音频格式、大小、时长</dt><dd>{selected.audioFormat}<small>{size(selected.audioSize)} · {duration(selected.audioDurationMs,"音频时长")}</small></dd></div><div><dt>语言</dt><dd>{selected.language||"—"}</dd></div><div><dt>处理耗时 / 创建时间</dt><dd>{duration(selected.processingTimeMs,"处理耗时")}<small>{dateTime(selected.createdAt)}</small></dd></div><div><dt>状态</dt><dd>{statusLabel[selected.status]}</dd></div></dl>{selected.status==="FAILED"&&<div className="asr-detail-error"><WarningCircle/><div><strong>{selected.errorCode||"ASR_TRANSCRIPTION_FAILED"}</strong><span>{selected.errorMessage||"语音识别失败"}</span></div></div>}<div className="asr-copy-compare"><article><h3>识别文字</h3><p>{selected.recognizedText||"暂无识别文字"}</p></article><article><label htmlFor="asr-correction"><PencilSimple/>人工修正文字</label><textarea id="asr-correction" value={selected.correctedText||""} onChange={(e)=>setSelected((current)=>({...current,correctedText:e.target.value}))} placeholder="听取原始音频后填写确认文字"/></article></div><footer><button type="button" onClick={()=>setSelected(null)}>取消</button><button type="button" className="asr-primary" onClick={saveCorrection} disabled={selected.status!=="SUCCESS"}>保存人工修正</button></footer></section></div>}
    <UiToast message={error||notice} tone={error?"error":"success"} onDismiss={()=>{setError("");setNotice("");}}/>
  </section>;
}
