// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import AsrRecords from "./AsrRecords";

const record={recordId:"asr_20260722_000001",requestId:"request_001",characterId:"character_001",characterNameSnapshot:"小爱",sessionId:"session_001",audioUrl:"/api/admin/asr/records/asr_20260722_000001/audio",audioFormat:"webm",audioSize:2048,audioDurationMs:8420,recognizedText:"今天天气很好",correctedText:"",provider:"groq",model:"whisper-large-v3",language:"zh",processingTimeMs:1260,status:"SUCCESS",createdAt:"2026-07-22T12:00:00+08:00"};
const quota={provider:"groq",model:"whisper-large-v3",dailyRequestCount:8,dailyRequestLimit:2000,dailyRequestsRemaining:1997,requestsResetAfter:"3h",providerSnapshotAt:"2026-07-22T12:00:00+08:00",hourlyAudioLimitSeconds:7200,hourlyAudioUsedSeconds:5,hourlyAudioRemainingSeconds:7195,dailyAudioLimitSeconds:28800,dailyAudioUsedSeconds:13,dailyAudioRemainingSeconds:28787,audioUsageScope:"AIPROVIDER_RECORDED"};
const json=(data)=>Promise.resolve({ok:true,status:200,json:async()=>({code:200,message:"success",data})});

describe("AsrRecords",()=>{
  beforeEach(()=>{global.fetch=vi.fn((url,options)=>{if(url.endsWith("/filters"))return json({characters:[{characterId:"character_001",characterName:"小爱"}],providerModels:[{provider:"groq",model:"whisper-large-v3"}]});if(url.endsWith("/quota"))return json(quota);if(options?.method==="PUT")return json(null);if(url.includes("asr_20260722_000001"))return json(record);return json({items:[record],total:1,page:1,pageSize:20,pages:1});});});
  afterEach(()=>{cleanup();vi.restoreAllMocks();});
  it("shows recorded daily requests separately from the rolling Groq snapshot",async()=>{render(<AsrRecords/>);expect(await screen.findByRole("region",{name:"Groq 语音识别额度"})).toBeTruthy();expect(screen.getByText("8 次")).toBeTruthy();expect(screen.getByText(/Groq 当前剩余 1,997 \/ 2,000/)).toBeTruthy();expect(screen.getByText(/本站已用 5 秒/)).toBeTruthy();expect(screen.getByText(/不代表今日累计请求数/)).toBeTruthy();});
  it("filters records and opens playable detail with correction",async()=>{render(<AsrRecords/>);expect(await screen.findByText("今天天气很好")).toBeTruthy();fireEvent.change(screen.getByLabelText("按角色筛选"),{target:{value:"character_001"}});await waitFor(()=>expect(global.fetch).toHaveBeenCalledWith(expect.stringContaining("characterId=character_001"),undefined));fireEvent.click(screen.getByRole("button",{name:"查看详情"}));expect(await screen.findByRole("dialog",{name:/语音识别详情/})).toBeTruthy();expect(document.querySelector("audio")?.getAttribute("src")).toContain("/audio");fireEvent.change(screen.getByLabelText("人工修正文字"),{target:{value:"今天天气真好"}});fireEvent.click(screen.getByRole("button",{name:"保存人工修正"}));await waitFor(()=>expect(global.fetch).toHaveBeenCalledWith(expect.stringContaining("/correction"),expect.objectContaining({method:"PUT",body:JSON.stringify({correctedText:"今天天气真好"})})));});
});
