import { useEffect, useMemo, useState } from "react";
import { Broadcast, CheckCircle, Clock, GearSix, Plus, Robot, XCircle } from "@phosphor-icons/react";
import UiSearchField from "./UiSearchField";
import UiToast from "./UiToast";
import { readJsonResponse } from "./apiResponse";
import "./ContentOperationsCenter.css";

const EMPTY = { settings: {}, counters: {}, accounts: [], collectionAccounts: [], sources: [], recentPublications: [] };
const tabs = [["overview","总览"],["accounts","账号"],["sources","采集源"],["publishing","发布队列"],["comments","评论维护"],["settings","自动化设置"]];

async function request(path, options) {
  const response = await fetch(`/api/content-operations${path}`, { headers: { "Content-Type": "application/json" }, ...options });
  const result = await readJsonResponse(response, "内容运营服务响应异常");
  if (!response.ok || result.code !== 200) throw new Error(result.message || `请求失败 · ${response.status}`);
  return result.data;
}

const statusLabel = (value) => ({ NOT_CONFIGURED:"未配置", PENDING:"待执行", PROCESSING:"执行中", UNKNOWN:"待人工确认", RELEVANT:"AI 相关", IRRELEVANT:"非 AI 内容", PUBLISHED:"已发布", FAILED:"失败", SUCCEEDED:"完成", SUCCESS:"正常", READY:"就绪" }[value] || value || "—");
const runMessage=(run)=>{if(run.errorMessage)return run.errorMessage;try{const metrics=JSON.parse(run.metricsJson||"{}");return ({NO_CONTENT:"未采集到新内容",FILTERED:"采集内容被判定为非 AI",ALREADY_EXISTS:"内容已处理，未重复生成",UNCERTAIN:"此前发布结果待人工确认",PUBLISHED:"已生成并发布"})[metrics.result]||metrics.result||"运行完成";}catch{return "运行完成";}};

export default function ContentOperationsCenter() {
  const [data, setData] = useState(EMPTY), [tab, setTab] = useState("overview"), [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice,setNotice]=useState(""), [dialog, setDialog] = useState("");
  const [selectedPublication,setSelectedPublication]=useState(null);
  const [sourceResult,setSourceResult]=useState(null),[testingSourceId,setTestingSourceId]=useState(null);
  const [historyQuery,setHistoryQuery]=useState(""),[historySource,setHistorySource]=useState(""),[history,setHistory]=useState([]),[selectedHistory,setSelectedHistory]=useState(null);
  const [automationRuns,setAutomationRuns]=useState([]);
  const load = async () => { setLoading(true); setError(""); try { setData(await request("/overview")); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(()=>{if(tab!=="sources")return;const timer=setTimeout(()=>request(`/items?limit=100${historySource?`&sourceId=${historySource}`:""}${historyQuery.trim()?`&query=${encodeURIComponent(historyQuery.trim())}`:""}`).then(setHistory).catch(e=>setError(e.message)),200);return()=>clearTimeout(timer);},[tab,historyQuery,historySource]);
  useEffect(()=>{if(tab!=="settings")return;request("/automation-runs?limit=20").then(setAutomationRuns).catch(e=>setError(e.message));},[tab]);
  const accounts = useMemo(() => data.accounts.filter((x) => `${x.displayName} ${x.accountHandle || ""}`.toLowerCase().includes(query.toLowerCase())), [data.accounts, query]);

  const updateAccount = async (account, patch) => { try { await request(`/accounts/${account.id}`, { method:"PATCH", body:JSON.stringify(patch) }); await load(); } catch (e) { setError(e.message); } };
  const save = async (event, kind) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget));
    if (kind === "account") values.publishMode = values.publishMode || "AUTO";
    const path=kind === "account" ? "/accounts" : kind === "collector" ? "/collection-accounts" : "/sources";
    try { await request(path, { method:"POST", body:JSON.stringify(values) }); setDialog(""); setNotice("配置已保存"); await load(); }
    catch (e) { setError(e.message); }
  };
  const withDecision=(current,item,decision)=>({...current,items:current.items.map(x=>x.id===item.id?{...x,relevanceStatus:decision.relevant?"RELEVANT":"IRRELEVANT",relevanceScore:decision.score,relevanceReason:decision.reason,relevanceCheckedAt:decision.checkedAt}:x)});
  const applyDecision=(item,decision)=>setSourceResult(current=>withDecision(current,item,decision));
  const classifyItem=async item=>{setError("");try{applyDecision(item,await request(`/items/${item.id}/classify`,{method:"POST"}));}catch(e){setError(e.message);}};
  const testSource=async source=>{setTestingSourceId(source.id);setError("");try{const result=await request(`/sources/${source.id}/test-fetch`,{method:"POST"});setSourceResult(result);if(result.items?.[0])setSourceResult(withDecision(result,result.items[0],await request(`/items/${result.items[0].id}/classify`,{method:"POST"})));await load();}catch(e){setError(e.message);}finally{setTestingSourceId(null);}};
  const openPublication=async publication=>{setSelectedPublication(publication);try{setSelectedPublication(await request(`/publications/${publication.id}`));}catch(e){setError(e.message);}};

  if (loading && !data.accounts.length) return <div className="content-ops-state">正在载入内容运营中心…</div>;
  return <section className="content-operations-center">
    <header className="content-ops-hero">
      <div><span>CONTENT OPERATIONS</span><h2>小红书运营控制台</h2><p>采集、生成、发布、评论维护与运行审计集中管理</p></div>
      <div className={`automation-state ${data.settings.automationEnabled ? "on" : "off"}`}><Robot weight="duotone"/><b>{data.settings.automationEnabled ? "自动运行中" : "自动化已暂停"}</b><small>默认 {data.settings.defaultPublishMode === "AUTO" ? "全自动" : "手动"} · 每 {data.settings.crawlIntervalMinutes || 240} 分钟采集</small></div>
    </header>
    <UiToast message={error||notice} tone={error?"error":"success"} onDismiss={()=>{setError("");setNotice("");}}/>
    <nav className="content-ops-tabs" aria-label="内容运营分区">{tabs.map(([key,label]) => <button type="button" key={key} className={tab===key?"active":""} onClick={() => setTab(key)}>{label}</button>)}</nav>

    {tab === "overview" && <>
      <div className="content-ops-kpis">
        {[["今日采集",data.counters.collectedToday],["待发布草稿",data.counters.readyDrafts],["今日发布",data.counters.publishedToday],["待回复评论",data.counters.pendingComments],["发布失败",data.counters.failedPublications]].map(([label,value],i)=><article key={label}><span>{label}</span><strong>{value || 0}</strong>{i===4&&value>0?<XCircle/>:<CheckCircle/>}</article>)}
      </div>
      <div className="content-ops-grid">
        <article className="content-ops-panel"><header><div><span>PIPELINE</span><h3>自动化流水线</h3></div><Clock/></header><ol><li className="ready"><b>01</b><span>采集最新内容<small>每个来源只保留最新一条</small></span></li><li><b>02</b><span>Gemini 相关性门禁<small>仅 AI 相关内容继续流转</small></span></li><li><b>03</b><span>Gemini 内容改写<small>生成小红书标题、正文和标签</small></span></li><li><b>04</b><span>小红书网页发布<small>扫码会话 · 自动文字卡 · 幂等发送</small></span></li><li className="blocked"><b>05</b><span>评论监听与回复<small>尚未接入评论网页适配器</small></span></li></ol></article>
        <article className="content-ops-panel"><header><div><span>ACCOUNTS</span><h3>账号运行状态</h3></div><button type="button" onClick={()=>setDialog("account")}><Plus/> 添加账号</button></header>{data.accounts.length?data.accounts.map(a=><AccountRow key={a.id} account={a} onUpdate={updateAccount}/>):<Empty text="还没有配置小红书账号"/>}</article>
      </div>
    </>}

    {tab === "accounts" && <div className="content-ops-panel wide"><header><div><span>XIAOHONGSHU</span><h3>账号、发布模式与内容源</h3></div><button type="button" onClick={()=>setDialog("account")}><Plus/> 添加账号</button></header><UiSearchField value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索账号" aria-label="搜索账号"/>{accounts.length?accounts.map(a=><div className="account-config-block" key={a.id}><AccountRow account={a} onUpdate={updateAccount}/><AccountSourceBinding account={a} sources={data.sources} onError={setError}/><XhsAccountActions account={a} onError={setError} onConnected={load}/></div>):<Empty text="没有匹配的账号"/>}</div>}
    {tab === "sources" && <div className="content-ops-panel wide"><header><div><span>COLLECTION</span><h3>采集账号与内容源</h3></div><div className="panel-header-actions"><button type="button" onClick={()=>setDialog("collector")}><Plus/> 添加采集账号</button><button type="button" onClick={()=>setDialog("source")} disabled={!data.collectionAccounts.length}><Plus/> 添加内容来源</button></div></header><section className="collection-account-strip" aria-label="采集账号">{data.collectionAccounts.length?data.collectionAccounts.map(a=><article key={a.id}><span className="source-platform">X</span><span><b>{a.displayName}</b><small>{a.adapterType==="TWITTER_WEB"?"X Cookie 登录":"官方 API"} · {a.credentialConfigured?"凭据已配置":"凭据未配置"}</small></span><i>{a.enabled?"可用":"停用"}</i></article>):<p>先添加一个 X 采集账号，Cookie 只需配置一次。</p>}</section>{data.sources.length?data.sources.map(s=><div className="source-row" key={s.id}><span className="source-platform">X</span><span><b>{s.name}</b><small>{s.adapterType==="TWITTER_WEB"?`Twitter @${s.externalHandle}`:`Twitter UID ${s.externalUid}`} · 使用全局 {data.settings.crawlIntervalMinutes||240} 分钟周期</small></span><span className="source-credential">采集账号：{s.collectionAccountName||"未绑定"}</span><i>{statusLabel(s.lastStatus)}</i><button type="button" onClick={()=>testSource(s)} disabled={testingSourceId===s.id}>{testingSourceId===s.id?"拉取并判断中…":"测试拉取并判断"}</button></div>):<Empty text="还没有内容采集源"/>}{sourceResult&&<SourcePreview result={sourceResult} onClassify={classifyItem}/>}<CollectionHistory items={history} sources={data.sources} query={historyQuery} sourceId={historySource} onQuery={setHistoryQuery} onSource={setHistorySource} onSelect={setSelectedHistory}/></div>}
    {tab === "publishing" && <PublicationQueue publications={data.recentPublications} onSelect={openPublication}/>}
    {tab === "comments" && <div className="content-ops-panel wide"><Empty text="评论维护将在真实发布成功并取得外部内容 ID 后启动"/></div>}
    {tab === "settings" && <div className="content-ops-settings-stack"><Settings settings={data.settings} runs={automationRuns} onSaved={async()=>{setNotice("自动化设置已保存");await load();}} onError={setError}/><GeminiSettings onError={setError}/></div>}

    {dialog && <div className="content-ops-dialog-backdrop"><form className="content-ops-dialog" role="dialog" aria-modal="true" aria-labelledby="content-ops-dialog-title" onSubmit={e=>save(e,dialog)}><header><h3 id="content-ops-dialog-title">{dialog==="account"?"添加小红书账号":dialog==="collector"?"添加 X 采集账号":"添加内容来源"}</h3><button type="button" autoFocus onClick={()=>setDialog("")} aria-label="关闭">×</button></header>{dialog==="account"?<><label>显示名称<input name="displayName" required maxLength="100"/></label><label>账号标识<input name="accountHandle" maxLength="120"/></label><label>发布模式<select name="publishMode" defaultValue="AUTO"><option value="AUTO">全自动</option><option value="MANUAL">手动确认</option></select></label></>:dialog==="collector"?<CollectionAccountFormFields/>:<SourceFormFields collectionAccounts={data.collectionAccounts}/>}<footer><button type="button" onClick={()=>setDialog("")}>取消</button><button type="submit">保存配置</button></footer></form></div>}
    {selectedPublication&&<PublicationDetails publication={selectedPublication} onClose={()=>setSelectedPublication(null)}/>}
    {selectedHistory&&<CollectionDetails item={selectedHistory} onClose={()=>setSelectedHistory(null)}/>}
  </section>;
}

function AccountRow({account,onUpdate}) { return <div className="account-row"><span className="platform-mark">小</span><span><b>{account.displayName}</b><small>{account.accountHandle || "未填写账号标识"}</small></span><label>模式<select value={account.publishMode} onChange={e=>onUpdate(account,{publishMode:e.target.value,enabled:account.enabled})}><option value="AUTO">全自动</option><option value="MANUAL">手动</option></select></label><label className="native-switch"><input type="checkbox" checked={account.enabled} onChange={e=>onUpdate(account,{publishMode:account.publishMode,enabled:e.target.checked})}/><span>{account.enabled?"启用":"停用"}</span></label><i className={account.adapterStatus === "READY" ? "ready" : "blocked"}>{statusLabel(account.adapterStatus)}</i></div>; }
function Empty({text}) { return <div className="content-ops-empty"><Broadcast weight="duotone"/><p>{text}</p></div>; }
function SourceFormFields({collectionAccounts}){const [accountId,setAccountId]=useState(String(collectionAccounts[0]?.id||""));const selected=collectionAccounts.find(a=>String(a.id)===accountId);const adapter=selected?.adapterType;return <><input type="hidden" name="platform" value="TWITTER"/><label>采集账号<select aria-label="采集账号" name="collectionAccountId" required value={accountId} onChange={e=>setAccountId(e.target.value)}>{collectionAccounts.map(a=><option key={a.id} value={a.id}>{a.displayName} · {a.adapterType==="TWITTER_WEB"?"Cookie":"API"}</option>)}</select><small>凭据从采集账号读取，不需要再次粘贴 Cookie。</small></label><label>来源名称<input name="name" required maxLength="120" placeholder="例如：Elon Musk"/></label>{adapter==="TWITTER_API"?<label>Twitter UID<input name="externalUid" required inputMode="numeric" pattern="[0-9]+" maxLength="30" placeholder="数字用户 ID"/></label>:<label>Twitter 用户名<input aria-label="Twitter 用户名" name="externalHandle" required pattern="@?[A-Za-z0-9_]{1,15}" maxLength="16" placeholder="例如：elonmusk"/><small>可填写 elonmusk 或 @elonmusk。</small></label>}<small>采集周期使用“自动化设置”中的全局周期。</small></>}
function CollectionAccountFormFields(){const [adapter,setAdapter]=useState("TWITTER_WEB");return <><label>账号名称<input name="displayName" required maxLength="100" placeholder="例如：我的 X 采集账号"/></label><label>采集方式<select aria-label="采集方式" name="adapterType" value={adapter} onChange={e=>setAdapter(e.target.value)}><option value="TWITTER_WEB">X 登录 Cookie（免 API Key）</option><option value="TWITTER_API">官方 API Bearer</option></select></label>{adapter==="TWITTER_WEB"?<label>X Cookie<textarea aria-label="X Cookie" name="accessToken" required maxLength="20000" spellCheck="false" placeholder="# Netscape HTTP Cookie File&#10;.x.com  TRUE  /  TRUE  ...  auth_token  ...&#10;.x.com  TRUE  /  TRUE  ...  ct0  ..."/><small>完整 Cookie 只配置一次，之后内容源直接绑定此账号。</small></label>:<label>Bearer Token<input aria-label="Bearer Token" name="accessToken" type="password" required autoComplete="new-password"/><small>保存后可供多个内容源复用。</small></label>}</>}
function PublicationQueue({publications,onSelect}){const active=publications.filter(p=>p.status!=="PUBLISHED"),completed=publications.filter(p=>p.status==="PUBLISHED");const group=(title,items)=><section className="publication-group"><header><h4>{title}</h4><span>{items.length}</span></header>{items.length?items.map(p=><button type="button" className="publication-row" key={p.id} onClick={()=>onSelect(p)} aria-label={`查看${p.title}发布详情`}><span><b>{p.title}</b><small>#{p.id} · {p.accountName} · {p.publishMode==="AUTO"?"自动":"手动"} · 尝试 {p.attemptCount} 次</small></span><i className={`publication-status ${p.status?.toLowerCase()}`}>{statusLabel(p.status)}</i></button>):<p className="publication-group-empty">暂无任务</p>}</section>;return <div className="content-ops-panel wide publication-queue"><header><div><span>QUEUE</span><h3>发布队列</h3></div><small>点击任务查看标题、正文、标签、来源和执行结果</small></header>{group("发送中与待处理",active)}{group("已完成",completed)}{!publications.length&&<Empty text="发布队列为空；自动任务生成后会在这里显示"/>}</div>}
function PublicationDetails({publication,onClose}){const time=value=>value?new Date(value).toLocaleString("zh-CN"):"—";let tags=[];try{tags=Array.isArray(publication.tagsJson)?publication.tagsJson:JSON.parse(publication.tagsJson||"[]");}catch{tags=[];}return <div className="content-ops-dialog-backdrop"><section className="content-ops-dialog publication-details" role="dialog" aria-modal="true" aria-labelledby="publication-details-title"><header><div><span>PUBLICATION #{publication.id}</span><h3 id="publication-details-title">发布任务详情</h3></div><button type="button" autoFocus onClick={onClose} aria-label="关闭">×</button></header><dl><div><dt>标题</dt><dd>{publication.title}</dd></div><div><dt>发布账号</dt><dd>{publication.accountName}</dd></div><div><dt>状态</dt><dd>{statusLabel(publication.status)}</dd></div><div><dt>执行次数</dt><dd>{publication.attemptCount}</dd></div><div><dt>计划时间</dt><dd>{time(publication.scheduledAt)}</dd></div><div><dt>完成时间</dt><dd>{time(publication.publishedAt)}</dd></div>{publication.sourceName&&<div><dt>采集来源</dt><dd>{publication.sourceName} · {publication.sourceAuthor||"—"}</dd></div>}{publication.modelName&&<div><dt>生成模型</dt><dd>{publication.modelName}</dd></div>}<div className="publication-reason"><dt>发布正文</dt><dd>{publication.body||"详情读取中…"}</dd></div>{tags.length>0&&<div className="publication-reason"><dt>标签</dt><dd>{tags.map(tag=>`#${tag}`).join("  ")}</dd></div>}{publication.sourceText&&<div className="publication-reason"><dt>采集原文</dt><dd>{publication.sourceText}</dd></div>}{publication.errorCode&&<div><dt>错误代码</dt><dd>{publication.errorCode}</dd></div>}<div className="publication-reason"><dt>执行结果</dt><dd>{publication.errorMessage||publication.externalPostUrl||"当前任务没有错误信息"}</dd></div></dl><footer>{publication.sourceUrl&&<a href={publication.sourceUrl} target="_blank" rel="noreferrer">查看采集原文</a>}<button type="button" onClick={onClose}>关闭</button></footer></section></div>}
function CollectionHistory({items,sources,query,sourceId,onQuery,onSource,onSelect}){return <section className="collection-history"><header><div><span>COLLECTION HISTORY</span><h4>采集历史</h4></div><div className="collection-history-filters"><UiSearchField value={query} onChange={e=>onQuery(e.target.value)} placeholder="查询作者、来源或正文" aria-label="查询采集历史"/><select aria-label="按采集源筛选" value={sourceId} onChange={e=>onSource(e.target.value)}><option value="">全部来源</option>{sources.map(source=><option key={source.id} value={source.id}>{source.name}</option>)}</select></div></header><div className="collection-history-list">{items.length?items.map(item=><button type="button" key={item.id} className="collection-history-row" onClick={()=>onSelect(item)}><span><b>{item.authorName||item.sourceName}</b><small>{item.sourceName} · {item.collectedAt?new Date(item.collectedAt).toLocaleString("zh-CN"):"时间未知"}</small></span><p>{item.rawText}</p><i className={(item.relevanceStatus||"pending").toLowerCase()}>{statusLabel(item.relevanceStatus)}</i></button>):<p className="publication-group-empty">没有匹配的采集记录</p>}</div></section>}
function CollectionDetails({item,onClose}){const time=value=>value?new Date(value).toLocaleString("zh-CN"):"—";return <div className="content-ops-dialog-backdrop"><section className="content-ops-dialog collection-details" role="dialog" aria-modal="true" aria-labelledby="collection-details-title"><header><div><span>COLLECTION #{item.id}</span><h3 id="collection-details-title">采集内容详情</h3></div><button type="button" autoFocus onClick={onClose} aria-label="关闭">×</button></header><dl><div><dt>采集来源</dt><dd>{item.sourceName}</dd></div><div><dt>作者</dt><dd>{item.authorName||"—"}</dd></div><div><dt>发布时间</dt><dd>{time(item.publishedAt)}</dd></div><div><dt>采集时间</dt><dd>{time(item.collectedAt)}</dd></div><div><dt>相关性</dt><dd>{statusLabel(item.relevanceStatus)}{item.relevanceScore!=null?` · ${Math.round(Number(item.relevanceScore)*100)}%`:""}</dd></div>{item.relevanceReason&&<div><dt>判断原因</dt><dd>{item.relevanceReason}</dd></div>}<div className="collection-detail-text"><dt>采集正文</dt><dd>{item.rawText}</dd></div></dl><footer>{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer">查看原文</a>}<button type="button" onClick={onClose}>关闭</button></footer></section></div>}
function SourcePreview({result,onClassify}) { return <section className="source-preview"><header><div><span>FETCH RESULT</span><h4>最新一条拉取结果</h4></div><p>读取 {result.fetchedCount} 条，新增入库 {result.newCount} 条</p></header>{result.items?.length?result.items.map(item=><article key={item.id}><header><b>{item.authorName}</b><time>{item.publishedAt?new Date(item.publishedAt).toLocaleString("zh-CN"):"时间未知"}</time></header><p>{item.rawText}</p><div className="source-preview-actions"><span className={`relevance-state ${(item.relevanceStatus||"PENDING").toLowerCase()}`}>{statusLabel(item.relevanceStatus)}</span>{item.relevanceScore!=null&&<small>相关度 {Math.round(Number(item.relevanceScore)*100)}%</small>}{item.relevanceReason&&<small>{item.relevanceReason}</small>}<button type="button" onClick={()=>onClassify(item)}>用 Gemini 判断</button><a href={item.sourceUrl} target="_blank" rel="noreferrer">查看原推文</a></div></article>):<Empty text="这个来源暂时没有可展示的内容"/>}</section>;}
function AccountSourceBinding({account,sources,onError}) { const [selected,setSelected]=useState([]),[saving,setSaving]=useState(false),[loaded,setLoaded]=useState(false);useEffect(()=>{request(`/accounts/${account.id}/sources`).then(v=>{setSelected(v||[]);setLoaded(true);}).catch(e=>onError(e.message));},[account.id,onError]);const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const save=async()=>{setSaving(true);try{setSelected(await request(`/accounts/${account.id}/sources`,{method:"PUT",body:JSON.stringify({sourceIds:selected})}));}catch(e){onError(e.message);}finally{setSaving(false);}};return <div className="account-source-binding"><span>允许发布的内容源</span>{!loaded?<small>读取中…</small>:sources.length?sources.map(source=><label key={source.id}><input type="checkbox" checked={selected.includes(source.id)} onChange={()=>toggle(source.id)}/><span>{source.name}</span></label>):<small>请先添加内容源</small>}<button type="button" onClick={save} disabled={saving||!loaded}>{saving?"保存中…":"保存来源绑定"}</button></div>;}
function XhsAccountActions({account,onError,onConnected}) { const [login,setLogin]=useState(null),[starting,setStarting]=useState(false),[testing,setTesting]=useState(false),[results,setResults]=useState(null);useEffect(()=>{if(!login?.sessionId||login.status!=="WAITING_SCAN")return;let cancelled=false,timer;const poll=async()=>{try{const next=await request(`/accounts/${account.id}/xhs-login/${login.sessionId}`);if(cancelled)return;setLogin(previous=>({...previous,...next,qrImageDataUrl:next.qrImageDataUrl||previous?.qrImageDataUrl}));if(next.status==="CONNECTED")await onConnected();else if(next.status==="WAITING_SCAN")timer=setTimeout(poll,2000);}catch(e){if(!cancelled)onError(e.message);}};timer=setTimeout(poll,2000);return()=>{cancelled=true;clearTimeout(timer);};},[account.id,login?.sessionId,login?.status,onConnected,onError]);const start=async()=>{setStarting(true);setResults(null);try{setLogin(await request(`/accounts/${account.id}/xhs-login`,{method:"POST"}));}catch(e){onError(e.message);}finally{setStarting(false);}};const test=async()=>{setTesting(true);setResults(null);try{setResults(await request(`/accounts/${account.id}/test-pipeline`,{method:"POST"}));await onConnected();}catch(e){onError(e.message);}finally{setTesting(false);}};const waiting=login?.status==="WAITING_SCAN";return <section className="xhs-account-actions" aria-label={`${account.displayName} 小红书连接与测试`}><div><button type="button" onClick={start} disabled={starting||waiting}>{starting?"正在打开扫码页…":waiting?"等待扫码确认…":account.sessionConfigured?"重新扫码登录":"扫码登录小红书"}</button><button type="button" className="primary" onClick={test} disabled={testing||!account.sessionConfigured}>{testing?"拉取、判断并发布中…":"一键测试小红书"}</button><small>{account.sessionConfigured?`会话已配置${account.lastConnectedAt?` · ${new Date(account.lastConnectedAt).toLocaleString("zh-CN")}`:""}`:"扫码成功后才可执行发布链路"}</small></div>{login?.qrImageDataUrl&&waiting&&<div className="xhs-qr"><img src={login.qrImageDataUrl} alt="小红书登录二维码"/><span>{login.message||"请用小红书 App 扫码并在手机上确认"}</span></div>}{login?.status==="CONNECTED"&&<p className="xhs-success">扫码登录成功，会话已加密保存。</p>}{login?.status==="EXPIRED"&&<p className="xhs-expired">{login.message||"扫码会话已过期，请重新发起。"}</p>}{results&&<div className="pipeline-test-results">{results.map(r=><article key={`${r.sourceId}-${r.contentItemId||"none"}`}><b>{({FILTERED:"已过滤",ALREADY_EXISTS:"已去重",PUBLISHED:"已发布",UNCERTAIN:"待确认",NO_CONTENT:"无内容"})[r.result]||r.result}</b><span>{r.message}</span>{r.draft&&<small>{r.draft.title}</small>}</article>)}</div>}</section>;}
function Settings({settings,runs,onSaved,onError}) { const submit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));v.automationEnabled=v.automationEnabled==="on";v.crawlIntervalMinutes=Number(v.crawlIntervalMinutes);v.commentIntervalMinutes=Number(v.commentIntervalMinutes);try{await request("/settings",{method:"PUT",body:JSON.stringify(v)});await onSaved();}catch(x){onError(x.message);}};return <form className="content-ops-panel wide settings-form" onSubmit={submit}><header><div><span>ORCHESTRATION</span><h3>自动化运行规则</h3><p>采集源统一使用这里的全局周期</p></div><GearSix/></header><div className="settings-inline"><label className="automation-toggle"><input name="automationEnabled" type="checkbox" defaultChecked={settings.automationEnabled}/><span><b>自动运行</b><small>{settings.automationEnabled?"已启用":"已暂停"}</small></span></label><label><span>默认发布</span><select name="defaultPublishMode" defaultValue={settings.defaultPublishMode || "AUTO"}><option value="AUTO">全自动</option><option value="MANUAL">手动确认</option></select></label><label><span>采集周期</span><div className="number-with-unit"><input aria-label="内容采集周期" name="crawlIntervalMinutes" type="number" min="15" max="10080" defaultValue={settings.crawlIntervalMinutes || 240}/><span>分钟</span></div></label><label><span>评论周期</span><div className="number-with-unit"><input aria-label="评论检查周期" name="commentIntervalMinutes" type="number" min="5" max="1440" defaultValue={settings.commentIntervalMinutes || 30}/><span>分钟</span></div></label><button type="submit">保存</button></div><footer><small>最后更新：{settings.updatedAt?new Date(settings.updatedAt).toLocaleString("zh-CN"):"尚未保存"}</small></footer><section className="automation-runs"><header><b>最近自动运行</b><small>任务没生成时，这里会显示“无内容、已过滤、已去重”或失败原因</small></header>{runs.length?runs.slice(0,8).map(run=><article key={run.id}><span className={(run.status||"").toLowerCase()}>{statusLabel(run.status)}</span><b>{run.startedAt?new Date(run.startedAt).toLocaleString("zh-CN"):"—"}</b><small>{runMessage(run)}</small></article>):<p>暂无自动运行记录</p>}</section></form>;}

function GeminiSettings({onError}) {
  const [config,setConfig]=useState(null),[saved,setSaved]=useState(""),[testing,setTesting]=useState(false),[showKey,setShowKey]=useState(false);
  useEffect(()=>{request("/ai-config").then(setConfig).catch(e=>onError(e.message));},[onError]);
  if(!config)return <div className="content-ops-panel wide">正在读取 Gemini 配置…</div>;
  const submit=async e=>{e.preventDefault();setSaved("");const form=e.currentTarget;const v=Object.fromEntries(new FormData(form));v.enabled=v.enabled==="on";v.temperature=Number(v.temperature);v.maxOutputTokens=Number(v.maxOutputTokens);try{const next=await request("/ai-config",{method:"PUT",body:JSON.stringify(v)});setConfig(next);setSaved("Gemini 配置已保存");form.elements.apiKey.value="";}catch(x){onError(x.message);}};
  const test=async()=>{setTesting(true);setSaved("");try{const result=await request("/ai-config/test",{method:"POST"});setSaved(`${result.text} · ${result.latencyMs}ms`);}catch(x){onError(x.message);}finally{setTesting(false);}};
  return <form className="content-ops-panel wide gemini-form" onSubmit={submit}>
    <header><div><span>GEMINI PROVIDER</span><h3>Gemini 内容生成</h3></div><span className={config.apiKeyConfigured?"gemini-key ready":"gemini-key"}>{config.apiKeyConfigured?`密钥已配置 ${config.apiKeyHint || ""}`:"密钥未配置"}</span></header>
    <label className="check-line"><input name="enabled" type="checkbox" defaultChecked={config.enabled}/><span><b>启用 Gemini 生成</b><small>用于相关性判断、小红书内容改写和评论回复</small></span></label>
    <fieldset className="gemini-section gemini-provider-section"><legend>连接配置</legend>
      <div className="gemini-provider-grid"><label className="gemini-api-key">API Key<div className="secret-input"><input name="apiKey" type={showKey?"text":"password"} autoComplete="new-password" placeholder={config.apiKeyConfigured?"留空则保留现有密钥":"输入 Gemini API Key"}/><button type="button" onClick={()=>setShowKey(v=>!v)}>{showKey?"隐藏":"显示"}</button></div><small>仅提交给后端加密保存，页面不会读取现有明文</small></label><label>模型<input name="model" required defaultValue={config.model}/></label><label className="gemini-api-base">API 地址<input name="apiBaseUrl" type="url" required defaultValue={config.apiBaseUrl}/></label></div>
      <div className="gemini-parameter-grid"><label>生成温度<input name="temperature" type="number" min="0" max="2" step="0.05" required defaultValue={config.temperature}/><small>0 更稳定，2 更发散</small></label><label>最大输出 Token<input name="maxOutputTokens" type="number" min="128" max="65536" required defaultValue={config.maxOutputTokens}/><small>限制单次生成长度</small></label></div>
    </fieldset>
    <fieldset className="gemini-section gemini-prompt-section"><legend>提示词模板</legend><div className="gemini-prompt-grid">
      <label className="gemini-relevance-prompt">AI 内容相关性判断提示词<textarea name="relevancePrompt" required minLength="20" maxLength="12000" defaultValue={config.relevancePrompt}/><small>非 AI 内容不会进入后续改写与发布。</small></label>
      <label>小红书内容改写提示词<textarea name="contentRewritePrompt" required minLength="20" maxLength="12000" defaultValue={config.contentRewritePrompt}/></label>
      <label>评论回复提示词<textarea name="commentReplyPrompt" required minLength="20" maxLength="12000" defaultValue={config.commentReplyPrompt}/></label>
    </div></fieldset>
    <footer><button type="submit">保存 Gemini 配置</button><button type="button" onClick={test} disabled={testing||!config.enabled||!config.apiKeyConfigured}>{testing?"测试中…":"测试连接"}</button>{saved&&<span>{saved}</span>}</footer>
  </form>;
}
