import { useEffect, useMemo, useState } from "react";
import { Broadcast, CheckCircle, Clock, GearSix, Plus, Robot, Warning, XCircle } from "@phosphor-icons/react";
import UiSearchField from "./UiSearchField";
import "./ContentOperationsCenter.css";

const EMPTY = { settings: {}, counters: {}, accounts: [], collectionAccounts: [], sources: [], recentPublications: [] };
const tabs = [["overview","总览"],["accounts","账号"],["sources","采集源"],["publishing","发布队列"],["comments","评论维护"],["settings","自动化设置"]];

async function request(path, options) {
  const response = await fetch(`/api/content-operations${path}`, { headers: { "Content-Type": "application/json" }, ...options });
  const result = await response.json();
  if (!response.ok || result.code !== 200) throw new Error(result.message || `请求失败 · ${response.status}`);
  return result.data;
}

const statusLabel = (value) => ({ NOT_CONFIGURED:"未配置", PENDING:"待执行", PROCESSING:"执行中", UNKNOWN:"待人工确认", RELEVANT:"AI 相关", IRRELEVANT:"非 AI 内容", PUBLISHED:"已发布", FAILED:"失败", READY:"就绪" }[value] || value || "—");

export default function ContentOperationsCenter() {
  const [data, setData] = useState(EMPTY), [tab, setTab] = useState("overview"), [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [dialog, setDialog] = useState("");
  const [selectedPublication,setSelectedPublication]=useState(null);
  const [sourceResult,setSourceResult]=useState(null),[testingSourceId,setTestingSourceId]=useState(null);
  const load = async () => { setLoading(true); setError(""); try { setData(await request("/overview")); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const accounts = useMemo(() => data.accounts.filter((x) => `${x.displayName} ${x.accountHandle || ""}`.toLowerCase().includes(query.toLowerCase())), [data.accounts, query]);

  const updateAccount = async (account, patch) => { try { await request(`/accounts/${account.id}`, { method:"PATCH", body:JSON.stringify(patch) }); await load(); } catch (e) { setError(e.message); } };
  const save = async (event, kind) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget));
    if (kind === "account") values.publishMode = values.publishMode || "AUTO";
    if (kind === "source") values.pollIntervalMinutes = Number(values.pollIntervalMinutes || 240);
    const path=kind === "account" ? "/accounts" : kind === "collector" ? "/collection-accounts" : "/sources";
    try { await request(path, { method:"POST", body:JSON.stringify(values) }); setDialog(""); await load(); }
    catch (e) { setError(e.message); }
  };
  const withDecision=(current,item,decision)=>({...current,items:current.items.map(x=>x.id===item.id?{...x,relevanceStatus:decision.relevant?"RELEVANT":"IRRELEVANT",relevanceScore:decision.score,relevanceReason:decision.reason,relevanceCheckedAt:decision.checkedAt}:x)});
  const applyDecision=(item,decision)=>setSourceResult(current=>withDecision(current,item,decision));
  const classifyItem=async item=>{setError("");try{applyDecision(item,await request(`/items/${item.id}/classify`,{method:"POST"}));}catch(e){setError(e.message);}};
  const testSource=async source=>{setTestingSourceId(source.id);setError("");try{const result=await request(`/sources/${source.id}/test-fetch`,{method:"POST"});setSourceResult(result);if(result.items?.[0])setSourceResult(withDecision(result,result.items[0],await request(`/items/${result.items[0].id}/classify`,{method:"POST"})));await load();}catch(e){setError(e.message);}finally{setTestingSourceId(null);}};

  if (loading && !data.accounts.length) return <div className="content-ops-state">正在载入内容运营中心…</div>;
  return <section className="content-operations-center">
    <header className="content-ops-hero">
      <div><span>CONTENT OPERATIONS</span><h2>小红书运营控制台</h2><p>采集、生成、发布、评论维护与运行审计集中管理</p></div>
      <div className={`automation-state ${data.settings.automationEnabled ? "on" : "off"}`}><Robot weight="duotone"/><b>{data.settings.automationEnabled ? "自动运行中" : "自动化已暂停"}</b><small>默认 {data.settings.defaultPublishMode === "AUTO" ? "全自动" : "手动"} · 每 {data.settings.crawlIntervalMinutes || 240} 分钟采集</small></div>
    </header>
    {error && <div className="content-ops-error" role="alert" aria-live="assertive"><Warning aria-hidden="true"/><span>{error}</span><button type="button" aria-label="关闭错误提示" onClick={() => setError("")}>关闭</button></div>}
    <nav className="content-ops-tabs" aria-label="内容运营分区">{tabs.map(([key,label]) => <button type="button" key={key} className={tab===key?"active":""} onClick={() => setTab(key)}>{label}</button>)}</nav>

    {tab === "overview" && <>
      <div className="content-ops-kpis">
        {[["今日采集",data.counters.collectedToday],["待发布草稿",data.counters.readyDrafts],["今日发布",data.counters.publishedToday],["待回复评论",data.counters.pendingComments],["发布失败",data.counters.failedPublications]].map(([label,value],i)=><article key={label}><span>{label}</span><strong>{value || 0}</strong>{i===4&&value>0?<XCircle/>:<CheckCircle/>}</article>)}
      </div>
      <div className="content-ops-grid">
        <article className="content-ops-panel"><header><div><span>PIPELINE</span><h3>自动化流水线</h3></div><Clock/></header><ol><li className="ready"><b>01</b><span>采集最新内容<small>每个来源只保留最新一条</small></span></li><li><b>02</b><span>Gemini 相关性门禁<small>仅 AI 相关内容继续流转</small></span></li><li><b>03</b><span>Gemini 内容改写<small>生成小红书标题、正文和标签</small></span></li><li><b>04</b><span>小红书网页发布<small>扫码会话 · 自动文字卡 · 幂等发送</small></span></li><li className="blocked"><b>05</b><span>评论监听与回复<small>尚未接入评论网页适配器</small></span></li></ol></article>
        <article className="content-ops-panel"><header><div><span>ACCOUNTS</span><h3>账号运行状态</h3></div><button type="button" onClick={()=>setDialog("account")}><Plus/> 添加账号</button></header>{data.accounts.length?data.accounts.map(a=><AccountRow key={a.id} account={a} onUpdate={updateAccount}/>):<Empty text="还没有配置小红书账号"/>}</article>
      </div>
    </>}

    {tab === "accounts" && <div className="content-ops-panel wide"><header><div><span>XIAOHONGSHU</span><h3>账号、发布模式与内容源</h3></div><button type="button" onClick={()=>setDialog("account")}><Plus/> 添加账号</button></header><UiSearchField value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索账号" aria-label="搜索账号"/>{accounts.length?accounts.map(a=><div className="account-config-block" key={a.id}><AccountRow account={a} onUpdate={updateAccount}/><AccountSourceBinding account={a} sources={data.sources} onError={setError}/><XhsAccountActions account={a} onError={setError} onConnected={load}/></div>):<Empty text="没有匹配的账号"/>}</div>}
    {tab === "sources" && <div className="content-ops-panel wide"><header><div><span>COLLECTION</span><h3>采集账号与内容源</h3></div><div className="panel-header-actions"><button type="button" onClick={()=>setDialog("collector")}><Plus/> 添加采集账号</button><button type="button" onClick={()=>setDialog("source")} disabled={!data.collectionAccounts.length}><Plus/> 添加内容来源</button></div></header><section className="collection-account-strip" aria-label="采集账号">{data.collectionAccounts.length?data.collectionAccounts.map(a=><article key={a.id}><span className="source-platform">X</span><span><b>{a.displayName}</b><small>{a.adapterType==="TWITTER_WEB"?"X Cookie 登录":"官方 API"} · {a.credentialConfigured?"凭据已配置":"凭据未配置"}</small></span><i>{a.enabled?"可用":"停用"}</i></article>):<p>先添加一个 X 采集账号，Cookie 只需配置一次。</p>}</section>{data.sources.length?data.sources.map(s=><div className="source-row" key={s.id}><span className="source-platform">X</span><span><b>{s.name}</b><small>{s.adapterType==="TWITTER_WEB"?`Twitter @${s.externalHandle}`:`Twitter UID ${s.externalUid}`} · 每 {s.pollIntervalMinutes} 分钟 · 每次只取最新 1 条</small></span><span className="source-credential">采集账号：{s.collectionAccountName||"未绑定"}</span><i>{statusLabel(s.lastStatus)}</i><button type="button" onClick={()=>testSource(s)} disabled={testingSourceId===s.id}>{testingSourceId===s.id?"拉取并判断中…":"测试拉取并判断"}</button></div>):<Empty text="还没有内容采集源"/>}{sourceResult&&<SourcePreview result={sourceResult} onClassify={classifyItem}/>}</div>}
    {tab === "publishing" && <div className="content-ops-panel wide"><header><div><span>QUEUE</span><h3>发布任务</h3></div></header>{data.recentPublications.length?data.recentPublications.map(p=><div className="publication-row" key={p.id}><span><b>{p.title}</b><small>{p.accountName} · {p.publishMode} · 尝试 {p.attemptCount} 次</small></span><button type="button" className={`publication-status ${p.status?.toLowerCase()}`} onClick={()=>setSelectedPublication(p)} aria-label={`查看${p.title}发布详情`}>{statusLabel(p.status)}</button></div>):<Empty text="发布队列为空；绑定来源并执行一键测试后会在这里显示任务"/>}</div>}
    {tab === "comments" && <div className="content-ops-panel wide"><Empty text="评论维护将在真实发布成功并取得外部内容 ID 后启动"/></div>}
    {tab === "settings" && <div className="content-ops-settings-stack"><GeminiSettings onError={setError}/><Settings settings={data.settings} onSaved={load} onError={setError}/></div>}

    {dialog && <div className="content-ops-dialog-backdrop"><form className="content-ops-dialog" role="dialog" aria-modal="true" aria-labelledby="content-ops-dialog-title" onSubmit={e=>save(e,dialog)}><header><h3 id="content-ops-dialog-title">{dialog==="account"?"添加小红书账号":dialog==="collector"?"添加 X 采集账号":"添加内容来源"}</h3><button type="button" autoFocus onClick={()=>setDialog("")} aria-label="关闭">×</button></header>{dialog==="account"?<><label>显示名称<input name="displayName" required maxLength="100"/></label><label>账号标识<input name="accountHandle" maxLength="120"/></label><label>发布模式<select name="publishMode" defaultValue="AUTO"><option value="AUTO">全自动</option><option value="MANUAL">手动确认</option></select></label></>:dialog==="collector"?<CollectionAccountFormFields/>:<SourceFormFields collectionAccounts={data.collectionAccounts}/>}<footer><button type="button" onClick={()=>setDialog("")}>取消</button><button type="submit">保存配置</button></footer></form></div>}
    {selectedPublication&&<PublicationDetails publication={selectedPublication} onClose={()=>setSelectedPublication(null)}/>}
  </section>;
}

function AccountRow({account,onUpdate}) { return <div className="account-row"><span className="platform-mark">小</span><span><b>{account.displayName}</b><small>{account.accountHandle || "未填写账号标识"}</small></span><label>模式<select value={account.publishMode} onChange={e=>onUpdate(account,{publishMode:e.target.value,enabled:account.enabled})}><option value="AUTO">全自动</option><option value="MANUAL">手动</option></select></label><label className="native-switch"><input type="checkbox" checked={account.enabled} onChange={e=>onUpdate(account,{publishMode:account.publishMode,enabled:e.target.checked})}/><span>{account.enabled?"启用":"停用"}</span></label><i className={account.adapterStatus === "READY" ? "ready" : "blocked"}>{statusLabel(account.adapterStatus)}</i></div>; }
function Empty({text}) { return <div className="content-ops-empty"><Broadcast weight="duotone"/><p>{text}</p></div>; }
function SourceFormFields({collectionAccounts}){const [accountId,setAccountId]=useState(String(collectionAccounts[0]?.id||""));const selected=collectionAccounts.find(a=>String(a.id)===accountId);const adapter=selected?.adapterType;return <><input type="hidden" name="platform" value="TWITTER"/><label>采集账号<select aria-label="采集账号" name="collectionAccountId" required value={accountId} onChange={e=>setAccountId(e.target.value)}>{collectionAccounts.map(a=><option key={a.id} value={a.id}>{a.displayName} · {a.adapterType==="TWITTER_WEB"?"Cookie":"API"}</option>)}</select><small>凭据从采集账号读取，不需要再次粘贴 Cookie。</small></label><label>来源名称<input name="name" required maxLength="120" placeholder="例如：Elon Musk"/></label>{adapter==="TWITTER_API"?<label>Twitter UID<input name="externalUid" required inputMode="numeric" pattern="[0-9]+" maxLength="30" placeholder="数字用户 ID"/></label>:<label>Twitter 用户名<input aria-label="Twitter 用户名" name="externalHandle" required pattern="@?[A-Za-z0-9_]{1,15}" maxLength="16" placeholder="例如：elonmusk"/><small>可填写 elonmusk 或 @elonmusk。</small></label>}<label>采集周期（分钟）<input aria-label="采集周期（分钟）" name="pollIntervalMinutes" type="number" min="15" max="10080" defaultValue="240"/><small>每次只处理最新一条非置顶文字推文，不补拉历史。</small></label></>}
function CollectionAccountFormFields(){const [adapter,setAdapter]=useState("TWITTER_WEB");return <><label>账号名称<input name="displayName" required maxLength="100" placeholder="例如：我的 X 采集账号"/></label><label>采集方式<select aria-label="采集方式" name="adapterType" value={adapter} onChange={e=>setAdapter(e.target.value)}><option value="TWITTER_WEB">X 登录 Cookie（免 API Key）</option><option value="TWITTER_API">官方 API Bearer</option></select></label>{adapter==="TWITTER_WEB"?<label>X Cookie<textarea aria-label="X Cookie" name="accessToken" required maxLength="20000" spellCheck="false" placeholder="# Netscape HTTP Cookie File&#10;.x.com  TRUE  /  TRUE  ...  auth_token  ...&#10;.x.com  TRUE  /  TRUE  ...  ct0  ..."/><small>完整 Cookie 只配置一次，之后内容源直接绑定此账号。</small></label>:<label>Bearer Token<input aria-label="Bearer Token" name="accessToken" type="password" required autoComplete="new-password"/><small>保存后可供多个内容源复用。</small></label>}</>}
function PublicationDetails({publication,onClose}){const time=value=>value?new Date(value).toLocaleString("zh-CN"):"—";return <div className="content-ops-dialog-backdrop"><section className="content-ops-dialog publication-details" role="dialog" aria-modal="true" aria-labelledby="publication-details-title"><header><div><span>PUBLICATION #{publication.id}</span><h3 id="publication-details-title">发布任务详情</h3></div><button type="button" autoFocus onClick={onClose} aria-label="关闭">×</button></header><dl><div><dt>标题</dt><dd>{publication.title}</dd></div><div><dt>发布账号</dt><dd>{publication.accountName}</dd></div><div><dt>状态</dt><dd>{statusLabel(publication.status)}</dd></div><div><dt>执行次数</dt><dd>{publication.attemptCount}</dd></div><div><dt>计划时间</dt><dd>{time(publication.scheduledAt)}</dd></div><div><dt>开始时间</dt><dd>{time(publication.startedAt)}</dd></div>{publication.errorCode&&<div><dt>错误代码</dt><dd>{publication.errorCode}</dd></div>}<div className="publication-reason"><dt>详细原因</dt><dd>{publication.errorMessage||"当前任务没有错误信息"}</dd></div></dl><footer><button type="button" onClick={onClose}>关闭</button></footer></section></div>}
function SourcePreview({result,onClassify}) { return <section className="source-preview"><header><div><span>FETCH RESULT</span><h4>最新一条拉取结果</h4></div><p>读取 {result.fetchedCount} 条，新增入库 {result.newCount} 条</p></header>{result.items?.length?result.items.map(item=><article key={item.id}><header><b>{item.authorName}</b><time>{item.publishedAt?new Date(item.publishedAt).toLocaleString("zh-CN"):"时间未知"}</time></header><p>{item.rawText}</p><div className="source-preview-actions"><span className={`relevance-state ${(item.relevanceStatus||"PENDING").toLowerCase()}`}>{statusLabel(item.relevanceStatus)}</span>{item.relevanceScore!=null&&<small>相关度 {Math.round(Number(item.relevanceScore)*100)}%</small>}{item.relevanceReason&&<small>{item.relevanceReason}</small>}<button type="button" onClick={()=>onClassify(item)}>用 Gemini 判断</button><a href={item.sourceUrl} target="_blank" rel="noreferrer">查看原推文</a></div></article>):<Empty text="这个来源暂时没有可展示的内容"/>}</section>;}
function AccountSourceBinding({account,sources,onError}) { const [selected,setSelected]=useState([]),[saving,setSaving]=useState(false),[loaded,setLoaded]=useState(false);useEffect(()=>{request(`/accounts/${account.id}/sources`).then(v=>{setSelected(v||[]);setLoaded(true);}).catch(e=>onError(e.message));},[account.id,onError]);const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const save=async()=>{setSaving(true);try{setSelected(await request(`/accounts/${account.id}/sources`,{method:"PUT",body:JSON.stringify({sourceIds:selected})}));}catch(e){onError(e.message);}finally{setSaving(false);}};return <div className="account-source-binding"><span>允许发布的内容源</span>{!loaded?<small>读取中…</small>:sources.length?sources.map(source=><label key={source.id}><input type="checkbox" checked={selected.includes(source.id)} onChange={()=>toggle(source.id)}/><span>{source.name}</span></label>):<small>请先添加内容源</small>}<button type="button" onClick={save} disabled={saving||!loaded}>{saving?"保存中…":"保存来源绑定"}</button></div>;}
function XhsAccountActions({account,onError,onConnected}) { const [login,setLogin]=useState(null),[starting,setStarting]=useState(false),[testing,setTesting]=useState(false),[results,setResults]=useState(null);useEffect(()=>{if(!login?.sessionId||login.status!=="WAITING_SCAN")return;let cancelled=false,timer;const poll=async()=>{try{const next=await request(`/accounts/${account.id}/xhs-login/${login.sessionId}`);if(cancelled)return;setLogin(previous=>({...previous,...next,qrImageDataUrl:next.qrImageDataUrl||previous?.qrImageDataUrl}));if(next.status==="CONNECTED")await onConnected();else if(next.status==="WAITING_SCAN")timer=setTimeout(poll,2000);}catch(e){if(!cancelled)onError(e.message);}};timer=setTimeout(poll,2000);return()=>{cancelled=true;clearTimeout(timer);};},[account.id,login?.sessionId,login?.status,onConnected,onError]);const start=async()=>{setStarting(true);setResults(null);try{setLogin(await request(`/accounts/${account.id}/xhs-login`,{method:"POST"}));}catch(e){onError(e.message);}finally{setStarting(false);}};const test=async()=>{setTesting(true);setResults(null);try{setResults(await request(`/accounts/${account.id}/test-pipeline`,{method:"POST"}));await onConnected();}catch(e){onError(e.message);}finally{setTesting(false);}};const waiting=login?.status==="WAITING_SCAN";return <section className="xhs-account-actions" aria-label={`${account.displayName} 小红书连接与测试`}><div><button type="button" onClick={start} disabled={starting||waiting}>{starting?"正在打开扫码页…":waiting?"等待扫码确认…":account.sessionConfigured?"重新扫码登录":"扫码登录小红书"}</button><button type="button" className="primary" onClick={test} disabled={testing||!account.sessionConfigured}>{testing?"拉取、判断并发布中…":"一键测试小红书"}</button><small>{account.sessionConfigured?`会话已配置${account.lastConnectedAt?` · ${new Date(account.lastConnectedAt).toLocaleString("zh-CN")}`:""}`:"扫码成功后才可执行发布链路"}</small></div>{login?.qrImageDataUrl&&waiting&&<div className="xhs-qr"><img src={login.qrImageDataUrl} alt="小红书登录二维码"/><span>{login.message||"请用小红书 App 扫码并在手机上确认"}</span></div>}{login?.status==="CONNECTED"&&<p className="xhs-success">扫码登录成功，会话已加密保存。</p>}{login?.status==="EXPIRED"&&<p className="xhs-expired">{login.message||"扫码会话已过期，请重新发起。"}</p>}{results&&<div className="pipeline-test-results">{results.map(r=><article key={`${r.sourceId}-${r.contentItemId||"none"}`}><b>{({FILTERED:"已过滤",ALREADY_EXISTS:"已去重",PUBLISHED:"已发布",UNCERTAIN:"待确认",NO_CONTENT:"无内容"})[r.result]||r.result}</b><span>{r.message}</span>{r.draft&&<small>{r.draft.title}</small>}</article>)}</div>}</section>;}
function Settings({settings,onSaved,onError}) { const submit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));v.automationEnabled=v.automationEnabled==="on";v.crawlIntervalMinutes=Number(v.crawlIntervalMinutes);v.commentIntervalMinutes=Number(v.commentIntervalMinutes);try{await request("/settings",{method:"PUT",body:JSON.stringify(v)});await onSaved();}catch(x){onError(x.message);}};return <form className="content-ops-panel wide settings-form" onSubmit={submit}><header><div><span>ORCHESTRATION</span><h3>自动化运行规则</h3><p>统一控制采集、发布与评论轮询频率</p></div><GearSix/></header><label className="automation-toggle"><input name="automationEnabled" type="checkbox" defaultChecked={settings.automationEnabled}/><span><b>启用自动运行</b><small>关闭后不会启动新的定时任务，已有记录仍然保留。</small></span></label><div className="settings-field-grid"><label><span>默认发布模式</span><select name="defaultPublishMode" defaultValue={settings.defaultPublishMode || "AUTO"}><option value="AUTO">全自动发布</option><option value="MANUAL">手动确认</option></select><small>新添加的小红书账号默认采用此模式。</small></label><label><span>内容采集周期</span><div className="number-with-unit"><input name="crawlIntervalMinutes" type="number" min="15" max="10080" defaultValue={settings.crawlIntervalMinutes || 240}/><span>分钟</span></div><small>到期后，每个来源只读取最新一条内容。</small></label><label><span>评论检查周期</span><div className="number-with-unit"><input name="commentIntervalMinutes" type="number" min="5" max="1440" defaultValue={settings.commentIntervalMinutes || 30}/><span>分钟</span></div><small>评论适配器接入后按此频率执行。</small></label></div><footer><button type="submit">保存自动化设置</button><small>最后更新：{settings.updatedAt?new Date(settings.updatedAt).toLocaleString("zh-CN"):"尚未保存"}</small></footer></form>;}

function GeminiSettings({onError}) {
  const [config,setConfig]=useState(null),[saved,setSaved]=useState(""),[testing,setTesting]=useState(false),[showKey,setShowKey]=useState(false);
  useEffect(()=>{request("/ai-config").then(setConfig).catch(e=>onError(e.message));},[onError]);
  if(!config)return <div className="content-ops-panel wide">正在读取 Gemini 配置…</div>;
  const submit=async e=>{e.preventDefault();setSaved("");const form=e.currentTarget;const v=Object.fromEntries(new FormData(form));v.enabled=v.enabled==="on";v.temperature=Number(v.temperature);v.maxOutputTokens=Number(v.maxOutputTokens);try{const next=await request("/ai-config",{method:"PUT",body:JSON.stringify(v)});setConfig(next);setSaved("Gemini 配置已保存");form.elements.apiKey.value="";}catch(x){onError(x.message);}};
  const test=async()=>{setTesting(true);setSaved("");try{const result=await request("/ai-config/test",{method:"POST"});setSaved(`${result.text} · ${result.latencyMs}ms`);}catch(x){onError(x.message);}finally{setTesting(false);}};
  return <form className="content-ops-panel wide gemini-form" onSubmit={submit}>
    <header><div><span>GEMINI PROVIDER</span><h3>Gemini 内容生成</h3></div><span className={config.apiKeyConfigured?"gemini-key ready":"gemini-key"}>{config.apiKeyConfigured?`密钥已配置 ${config.apiKeyHint || ""}`:"密钥未配置"}</span></header>
    <label className="check-line"><input name="enabled" type="checkbox" defaultChecked={config.enabled}/><span><b>启用 Gemini 生成</b><small>用于相关性判断、小红书内容改写和评论回复</small></span></label>
    <div className="gemini-field-row"><label>API Key<div className="secret-input"><input name="apiKey" type={showKey?"text":"password"} autoComplete="new-password" placeholder={config.apiKeyConfigured?"留空则保留现有密钥":"输入 Gemini API Key"}/><button type="button" onClick={()=>setShowKey(v=>!v)}>{showKey?"隐藏":"显示"}</button></div><small>仅提交给后端加密保存，页面不会读取现有明文</small></label><label>模型<input name="model" required defaultValue={config.model}/></label></div>
    <label>API 地址<input name="apiBaseUrl" type="url" required defaultValue={config.apiBaseUrl}/></label>
    <div className="gemini-field-row compact"><label>生成温度<input name="temperature" type="number" min="0" max="2" step="0.05" required defaultValue={config.temperature}/></label><label>最大输出 Token<input name="maxOutputTokens" type="number" min="128" max="65536" required defaultValue={config.maxOutputTokens}/></label></div>
    <label>AI 内容相关性判断提示词<textarea name="relevancePrompt" required minLength="20" maxLength="12000" defaultValue={config.relevancePrompt}/><small>Gemini 会先按此规则判断；非 AI 内容不会进入后续改写与发布。</small></label>
    <label>小红书内容改写提示词<textarea name="contentRewritePrompt" required minLength="20" maxLength="12000" defaultValue={config.contentRewritePrompt}/></label>
    <label>评论回复提示词<textarea name="commentReplyPrompt" required minLength="20" maxLength="12000" defaultValue={config.commentReplyPrompt}/></label>
    <footer><button type="submit">保存 Gemini 配置</button><button type="button" onClick={test} disabled={testing||!config.enabled||!config.apiKeyConfigured}>{testing?"测试中…":"测试连接"}</button>{saved&&<span>{saved}</span>}</footer>
  </form>;
}
