import { useEffect, useState } from "react";
import { Key, LinkSimple, Plus, ShieldCheck, UserCircle, X } from "@phosphor-icons/react";
import UiSearchField from "./UiSearchField";
import UiToast from "./UiToast";
import { readJsonResponse } from "./apiResponse";
import "./PlatformAccountCenter.css";

const PLATFORM_LABELS={X:"X",XIAOHONGSHU:"小红书",DOUYIN:"抖音",GEMINI:"Gemini"};
const STATUS_LABELS={NOT_CONFIGURED:"未配置",PENDING_LOGIN:"等待登录",CONNECTED:"已连接",EXPIRED:"已过期",ERROR:"异常",DISABLED:"已停用"};
const PLATFORM_DEFAULTS={X:{adapterType:"X_WEB",secretType:"COOKIE"},XIAOHONGSHU:{adapterType:"XIAOHONGSHU_WEB",secretType:"STORAGE_STATE"},DOUYIN:{adapterType:"DOUYIN_WEB",secretType:"STORAGE_STATE"},GEMINI:{adapterType:"GEMINI_API",secretType:"API_KEY"}};

async function request(path,options={}){
  const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});
  const result=await readJsonResponse(response,"账号中心响应异常");
  if(!response.ok||result.code!==200)throw new Error(result.message||`请求失败 · ${response.status}`);
  return result.data;
}
const initialForm=()=>({platform:"X",displayName:"",accountHandle:"",adapterType:"X_WEB",publicConfigJson:"",secretType:"COOKIE",secret:""});

export default function PlatformAccountCenter(){
  const [query,setQuery]=useState("");const [platform,setPlatform]=useState("");const [status,setStatus]=useState("");
  const [accounts,setAccounts]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const [editing,setEditing]=useState(false);const [form,setForm]=useState(initialForm);const [usageAccount,setUsageAccount]=useState(null);const [usages,setUsages]=useState([]);const [saving,setSaving]=useState(false);
  const load=async(signal)=>{setLoading(true);try{const params=new URLSearchParams({page:"1",pageSize:"30"});if(query.trim())params.set("query",query.trim());if(platform)params.set("platform",platform);if(status)params.set("status",status);const data=await request(`/api/platform-accounts?${params}`,{signal});setAccounts(data?.items||[]);setError("");}catch(e){if(e.name!=="AbortError")setError(e.message);}finally{if(!signal?.aborted)setLoading(false);}};
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>load(controller.signal),300);return()=>{clearTimeout(timer);controller.abort();};},[query,platform,status]);
  const changePlatform=(value)=>setForm(current=>({...current,platform:value,...PLATFORM_DEFAULTS[value],publicConfigJson:value==="GEMINI"?'{"apiBaseUrl":"https://generativelanguage.googleapis.com"}':""}));
  const save=async(event)=>{event.preventDefault();setSaving(true);try{const account=await request("/api/platform-accounts",{method:"POST",body:JSON.stringify({platform:form.platform,displayName:form.displayName,accountHandle:form.accountHandle||null,adapterType:form.adapterType,publicConfigJson:form.publicConfigJson||null,enabled:true})});if(form.secret.trim())await request(`/api/platform-accounts/${account.id}/secrets/${form.secretType}`,{method:"PUT",body:JSON.stringify({value:form.secret,hint:secretHint(form.secretType,form.secret)})});setForm(initialForm());setEditing(false);setNotice("账号已保存");await load();}catch(e){setError(e.message);}finally{setSaving(false);}};
  const showUsages=async(account)=>{setUsageAccount(account);try{setUsages(await request(`/api/platform-accounts/${account.id}/usages`)||[]);}catch(e){setError(e.message);setUsages([]);}};
  const archive=async()=>{if(!usageAccount||usages.length)return;try{await request(`/api/platform-accounts/${usageAccount.id}`,{method:"DELETE"});setUsageAccount(null);setNotice("账号已归档");await load();}catch(e){setError(e.message);}};
  const social=accounts.filter(item=>item.accountKind==="SOCIAL"),apis=accounts.filter(item=>item.accountKind==="API_SERVICE");
  return <section className="platform-account-center" aria-label="账号中心">
    <header className="account-center-hero"><div><span>ENCRYPTED ACCOUNT VAULT</span><h2>所有设备，共用一套登录信息</h2><p>Cookie、浏览器会话和 API Key 加密保存在后端；页面只显示脱敏提示。</p></div><button type="button" className="account-primary" onClick={()=>setEditing(true)}><Plus/>新增账号</button></header>
    <div className="account-toolbar"><UiSearchField aria-label="搜索账号" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或 Handle"/><select aria-label="按平台筛选" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">全部平台</option>{Object.entries(PLATFORM_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="按连接状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{Object.entries(STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
    <div className="account-sections">
      <AccountSection title="平台账号" icon={<UserCircle/>} items={social} loading={loading} onUsages={showUsages}/>
      <AccountSection title="API 服务" icon={<Key/>} items={apis} loading={loading} onUsages={showUsages}/>
      <section className="account-section usage-section"><header><LinkSimple/><div><h3>使用关系</h3><span>删除前先确认业务引用</span></div></header>{usageAccount?<><h4>{usageAccount.displayName}</h4>{usages.length?<ul>{usages.map(item=><li key={`${item.consumerType}-${item.consumerId}`}><b>{item.consumerName||item.consumerType}</b><span>{item.consumerType} · #{item.consumerId}</span></li>)}</ul>:<p className="account-empty">当前没有业务模块引用该账号。</p>}<footer><button type="button" onClick={()=>setUsageAccount(null)}>关闭</button><button type="button" className="account-danger" disabled={usages.length>0} onClick={archive}>归档账号</button></footer></>:<p className="account-empty">从账号卡片进入，可查看 X 发布、内容采集、小红书运营或 Gemini 配置的引用。</p>}</section>
    </div>
    {editing?<div className="account-dialog-backdrop"><form className="account-dialog" onSubmit={save} aria-label="新增平台账号"><header><div><span>NEW ACCOUNT</span><h3>新增账号</h3></div><button type="button" aria-label="关闭新增账号" onClick={()=>setEditing(false)}><X/></button></header><label>平台<select aria-label="平台" value={form.platform} onChange={e=>changePlatform(e.target.value)}>{Object.entries(PLATFORM_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>账号名称<input aria-label="账号名称" required maxLength="100" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>账号 Handle<input aria-label="账号 Handle" value={form.accountHandle} onChange={e=>setForm({...form,accountHandle:e.target.value})} placeholder="可选"/></label>{form.platform==="X"?<label>凭据类型<select aria-label="X 凭据类型" value={form.secretType} onChange={e=>setForm({...form,secretType:e.target.value})}><option value="COOKIE">Cookie</option><option value="STORAGE_STATE">浏览器会话</option><option value="BEARER_TOKEN">Bearer Token</option></select></label>:null}<label>{form.platform==="GEMINI"?"API Key":form.platform==="X"?"Cookie / Token":"浏览器会话"}<textarea aria-label={form.platform==="GEMINI"?"API Key":"登录凭据"} value={form.secret} onChange={e=>setForm({...form,secret:e.target.value})} placeholder={form.platform==="GEMINI"?"输入 Gemini API Key":"可先留空，保存后通过扫码或导入会话"}/></label><p><ShieldCheck/>凭据提交后立即加密，之后无法从页面读取原值。</p><footer><button type="button" onClick={()=>setEditing(false)}>取消</button><button type="submit" className="account-primary" disabled={saving}>{saving?"保存中…":"保存账号"}</button></footer></form></div>:null}
    <UiToast message={error||notice} tone={error?"error":"success"} onClose={()=>{setError("");setNotice("");}}/>
  </section>;
}

function AccountSection({title,icon,items,loading,onUsages}){return <section className="account-section"><header>{icon}<div><h3>{title}</h3><span>{items.length} 个账号</span></div></header>{loading?<p className="account-empty">正在同步账号状态…</p>:items.length?<div className="account-card-list">{items.map(item=><article className="account-card" key={item.id}><header><div className={`account-platform platform-${item.platform.toLowerCase()}`}>{PLATFORM_LABELS[item.platform]||item.platform}</div><span className={`account-status status-${String(item.connectionStatus).toLowerCase()}`}>{STATUS_LABELS[item.connectionStatus]||item.connectionStatus}</span></header><h4>{item.displayName}</h4><p>{item.accountHandle||item.adapterType}</p><dl><div><dt>凭据</dt><dd>{item.credentialHints?.filter(Boolean).join(" · ")||"尚未配置"}</dd></div><div><dt>最近验证</dt><dd>{item.lastValidatedAt?new Date(item.lastValidatedAt).toLocaleString("zh-CN"):"从未验证"}</dd></div></dl>{item.lastErrorMessage?<small className="account-error">{item.lastErrorMessage}</small>:null}<button type="button" onClick={()=>onUsages(item)} aria-label={`查看 ${item.displayName} 使用关系`}>查看使用关系</button></article>)}</div>:<p className="account-empty">暂无匹配账号。</p>}</section>}
function secretHint(type,value){if(type==="API_KEY"||type==="BEARER_TOKEN")return `••••${value.slice(-4)}`;return type==="COOKIE"?"Cookie 会话":"浏览器会话";}
