UPDATE c_PromptTemplates
SET Prompt = 'worst quality, low quality, normal quality, lowres, blurry, jpeg artifacts, bad anatomy, bad proportions, poorly drawn face, bad hands, malformed hands, extra fingers, missing fingers, fused fingers, extra limbs, missing limbs, deformed limbs, long neck, duplicate, cropped, out of frame, text, watermark, signature, username, logo'
WHERE Id = 'general_negative';

INSERT INTO c_PromptOptions(Id, Category, Name, PositivePrompt, NegativePrompt, SortOrder, Enabled, AllowMultiple) VALUES
('no_humans', 'character_count', '无人 / 纯场景', 'no humans', 'person, people', 40, TRUE, FALSE),
('four_people', 'character_count', '四人', '4people', 'solo, two people, three people', 50, TRUE, FALSE),
('small_group', 'character_count', '多人小组', 'group, multiple people', 'solo', 60, TRUE, FALSE),
('crowd', 'character_count', '人群', 'crowd', 'solo, empty scene', 70, TRUE, FALSE),
('multiple_girls', 'character_count', '多名女性', 'multiple girls', 'solo, male only', 80, TRUE, FALSE),
('multiple_boys', 'character_count', '多名男性', 'multiple boys', 'solo, female only', 90, TRUE, FALSE),

('young_woman', 'character_type', '年轻成年女性', 'young adult woman', NULL, 60, TRUE, TRUE),
('mature_woman', 'character_type', '成熟女性', 'mature woman', 'child', 70, TRUE, TRUE),
('muscular_woman', 'character_type', '健美女性', 'muscular woman, athletic female', NULL, 80, TRUE, TRUE),
('petite_woman', 'character_type', '娇小成年女性', 'petite adult woman', 'child', 90, TRUE, TRUE),
('tall_woman', 'character_type', '高挑女性', 'tall woman, long legs', NULL, 100, TRUE, TRUE),
('young_man', 'character_type', '年轻成年男性', 'young adult man', NULL, 110, TRUE, TRUE),
('mature_man', 'character_type', '成熟男性', 'mature man', 'child', 120, TRUE, TRUE),
('muscular_man', 'character_type', '肌肉男性', 'muscular man, athletic male', NULL, 130, TRUE, TRUE),
('androgynous_adult', 'character_type', '中性气质成人', 'androgynous adult', NULL, 140, TRUE, TRUE),
('elf', 'character_type', '精灵', 'elf, pointy ears', 'human ears', 150, TRUE, TRUE),
('demon', 'character_type', '恶魔', 'demon, demon horns', NULL, 160, TRUE, TRUE),
('angel', 'character_type', '天使', 'angel, angel wings, halo', NULL, 170, TRUE, TRUE),
('catgirl', 'character_type', '猫娘', 'cat girl, cat ears, cat tail', NULL, 180, TRUE, TRUE),
('kemonomimi', 'character_type', '兽耳角色', 'animal ears, animal tail', NULL, 190, TRUE, TRUE),

('married_couple', 'relationship', '夫妻', 'married couple, wedding rings', 'strangers', 40, TRUE, TRUE),
('girlfriends', 'relationship', '女性恋人', 'female lovers, yuri couple', 'male only', 50, TRUE, TRUE),
('boyfriends', 'relationship', '男性恋人', 'male lovers, yaoi couple', 'female only', 60, TRUE, TRUE),
('siblings', 'relationship', '兄弟姐妹', 'siblings', NULL, 70, TRUE, TRUE),
('twins', 'relationship', '双胞胎', 'twins', 'different appearance', 80, TRUE, TRUE),
('rivals', 'relationship', '对手', 'rivals, competitive tension', NULL, 90, TRUE, TRUE),
('master_servant', 'relationship', '主人与侍从', 'master and servant', NULL, 100, TRUE, TRUE),
('teacher_student_adults', 'relationship', '成年师生', 'adult teacher and adult student', 'child', 110, TRUE, TRUE),
('coworkers', 'relationship', '同事', 'coworkers', NULL, 120, TRUE, TRUE),
('strangers', 'relationship', '陌生人', 'strangers', 'intimate couple', 130, TRUE, TRUE),
('protective', 'relationship', '保护关系', 'protective embrace', 'hostile', 140, TRUE, TRUE),
('dominant_submissive_adults', 'relationship', '成年支配与顺从', 'adult dominant and submissive partners', NULL, 150, TRUE, TRUE),

('looking_away', 'action', '移开视线', 'looking away', 'looking at viewer', 50, TRUE, TRUE),
('eye_contact', 'action', '相互对视', 'eye contact, looking at each other', 'looking away', 60, TRUE, TRUE),
('holding_hands', 'action', '牵手', 'holding hands', 'separated hands', 70, TRUE, TRUE),
('hand_on_hip', 'action', '手叉腰', 'hand on hip', NULL, 80, TRUE, TRUE),
('hands_behind_back', 'action', '双手背后', 'hands behind back', NULL, 90, TRUE, TRUE),
('arms_crossed', 'action', '双臂交叉', 'arms crossed', NULL, 100, TRUE, TRUE),
('touching_face', 'action', '触摸脸颊', 'touching face', NULL, 110, TRUE, TRUE),
('touching_hair', 'action', '拨弄头发', 'touching hair', NULL, 120, TRUE, TRUE),
('hair_flip', 'action', '甩动头发', 'hair flip, flowing hair', 'static hair', 130, TRUE, TRUE),
('waving', 'action', '挥手', 'waving', NULL, 140, TRUE, TRUE),
('peace_sign', 'action', '比耶', 'peace sign', NULL, 150, TRUE, TRUE),
('finger_to_lips', 'action', '手指抵唇', 'finger to lips, shushing', NULL, 160, TRUE, TRUE),
('eating', 'action', '进食', 'eating', NULL, 170, TRUE, TRUE),
('drinking', 'action', '饮用', 'drinking', NULL, 180, TRUE, TRUE),
('reading', 'action', '阅读', 'reading a book', NULL, 190, TRUE, TRUE),
('using_phone', 'action', '使用手机', 'using smartphone', NULL, 200, TRUE, TRUE),
('running', 'action', '奔跑', 'running, motion', 'standing still', 210, TRUE, TRUE),
('dancing', 'action', '跳舞', 'dancing, dynamic motion', 'static pose', 220, TRUE, TRUE),
('stretching', 'action', '伸懒腰', 'stretching', NULL, 230, TRUE, TRUE),
('undressing_adult', 'action', '成年角色脱衣', 'adult undressing, clothes pull', 'fully dressed', 240, TRUE, TRUE),
('lifting_skirt_adult', 'action', '成年角色提裙', 'adult lifting skirt', 'long closed skirt', 250, TRUE, TRUE),
('adjusting_legwear', 'action', '整理袜子', 'adjusting legwear, pulling up stockings', 'bare legs', 260, TRUE, TRUE),
('breast_grab_adult', 'action', '成年胸部爱抚', 'adult breast grab', NULL, 270, TRUE, TRUE),
('ass_grab_adult', 'action', '成年臀部爱抚', 'adult ass grab', NULL, 280, TRUE, TRUE),
('straddling_adult', 'action', '成年跨坐', 'adult straddling', NULL, 290, TRUE, TRUE),
('masturbation_adult', 'action', '成年自慰', 'adult masturbation', NULL, 300, TRUE, TRUE),
('oral_sex_adult', 'action', '成年口交', 'adult oral sex', NULL, 310, TRUE, TRUE),
('vaginal_sex_adult', 'action', '成年性交', 'adult vaginal sex', NULL, 320, TRUE, TRUE),

('black_pantyhose', 'clothing', '黑丝袜 / 黑色连裤袜', 'black pantyhose, sheer black tights', 'bare legs, white legwear', 11, TRUE, TRUE),
('black_thighhighs', 'clothing', '黑色过膝袜 / 黑色长筒袜', 'black thighhighs, black stockings', 'bare legs, white thighhighs', 12, TRUE, TRUE),
('sheer_black_stockings', 'clothing', '黑色透明丝袜', 'sheer black stockings, glossy legwear', 'opaque legwear, bare legs', 13, TRUE, TRUE),
('black_garter_stockings', 'clothing', '黑色吊带袜', 'black garter stockings, garter straps', 'pantyhose, bare legs', 14, TRUE, TRUE),
('black_fishnet_stockings', 'clothing', '黑色渔网袜', 'black fishnet stockings', 'opaque stockings, bare legs', 15, TRUE, TRUE),
('black_knee_socks', 'clothing', '黑色及膝袜', 'black knee socks', 'bare legs', 16, TRUE, TRUE),
('white_pantyhose', 'clothing', '白色连裤袜', 'white pantyhose, sheer white tights', 'bare legs, black legwear', 17, TRUE, TRUE),
('white_thighhighs', 'clothing', '白色过膝袜', 'white thighhighs', 'bare legs, black thighhighs', 18, TRUE, TRUE),
('nude_pantyhose', 'clothing', '肤色丝袜', 'nude pantyhose, skin-tone tights', 'bare legs', 19, TRUE, TRUE),
('red_thighhighs', 'clothing', '红色过膝袜', 'red thighhighs', 'bare legs', 21, TRUE, TRUE),
('striped_thighhighs', 'clothing', '条纹过膝袜', 'striped thighhighs', 'plain legwear', 22, TRUE, TRUE),
('lace_stockings', 'clothing', '蕾丝袜', 'lace stockings, lace trim', 'plain legwear, bare legs', 23, TRUE, TRUE),
('wet_pantyhose', 'clothing', '湿润丝袜', 'wet pantyhose, wet fabric, glossy legwear', 'dry fabric, bare legs', 24, TRUE, TRUE),
('torn_pantyhose', 'clothing', '破损丝袜', 'torn pantyhose, ripped tights', 'intact legwear', 25, TRUE, TRUE),
('garter_belt', 'clothing', '吊袜带', 'garter belt, garter straps', 'pantyhose', 26, TRUE, TRUE),
('zettai_ryouiki', 'clothing', '绝对领域', 'zettai ryouiki, thigh gap between skirt and thighhighs', 'long skirt, bare legs', 27, TRUE, TRUE),
('ankle_socks', 'clothing', '短袜', 'ankle socks', 'bare feet', 28, TRUE, TRUE),
('loose_socks', 'clothing', '泡泡袜', 'loose socks', 'tight socks', 29, TRUE, TRUE),
('leggings', 'clothing', '紧身裤', 'leggings', 'bare legs', 31, TRUE, TRUE),
('yoga_pants', 'clothing', '瑜伽裤', 'yoga pants, tight pants', 'loose pants', 32, TRUE, TRUE),
('denim_shorts', 'clothing', '牛仔短裤', 'denim shorts', 'long pants', 33, TRUE, TRUE),
('miniskirt', 'clothing', '迷你裙', 'miniskirt', 'long skirt', 34, TRUE, TRUE),
('pleated_skirt', 'clothing', '百褶裙', 'pleated skirt', 'pants', 35, TRUE, TRUE),
('pencil_skirt', 'clothing', '包臀铅笔裙', 'pencil skirt, tight skirt', 'loose skirt', 36, TRUE, TRUE),
('leather_skirt', 'clothing', '皮裙', 'leather skirt', 'fabric skirt', 37, TRUE, TRUE),
('little_black_dress', 'clothing', '黑色小礼裙', 'little black dress, elegant black dress', 'casual clothes', 38, TRUE, TRUE),
('evening_gown', 'clothing', '晚礼服', 'evening gown, formal dress', 'casual wear', 39, TRUE, TRUE),
('qipao', 'clothing', '旗袍', 'qipao, chinese dress, high slit', 'western dress', 41, TRUE, TRUE),
('kimono', 'clothing', '和服', 'kimono, japanese clothes', 'western clothes', 42, TRUE, TRUE),
('maid_outfit', 'clothing', '女仆装', 'maid outfit, maid headdress, apron', 'casual wear', 43, TRUE, TRUE),
('nurse_outfit_adult', 'clothing', '成年护士装', 'adult nurse outfit', 'casual wear', 44, TRUE, TRUE),
('office_lady_suit', 'clothing', '职业女性套装', 'office lady, business suit, pencil skirt', 'sportswear', 45, TRUE, TRUE),
('blazer', 'clothing', '西装外套', 'blazer', 'sleeveless', 46, TRUE, TRUE),
('white_shirt', 'clothing', '白衬衫', 'white shirt', 'black shirt', 47, TRUE, TRUE),
('open_shirt', 'clothing', '敞开衬衫', 'open shirt, partially unbuttoned', 'buttoned shirt', 48, TRUE, TRUE),
('crop_top', 'clothing', '露脐上衣', 'crop top, midriff', 'covered midriff', 49, TRUE, TRUE),
('hoodie', 'clothing', '连帽衫', 'hoodie', 'formal wear', 51, TRUE, TRUE),
('oversized_sweater', 'clothing', '宽松毛衣', 'oversized sweater', 'tight clothes', 52, TRUE, TRUE),
('turtleneck', 'clothing', '高领毛衣', 'turtleneck sweater', 'open neckline', 53, TRUE, TRUE),
('sports_bra', 'clothing', '运动内衣', 'sports bra', 'formal wear', 54, TRUE, TRUE),
('bikini', 'clothing', '比基尼', 'bikini', 'one-piece swimsuit', 55, TRUE, TRUE),
('micro_bikini_adult', 'clothing', '成年微型比基尼', 'adult micro bikini', 'covered body', 56, TRUE, TRUE),
('one_piece_swimsuit', 'clothing', '连体泳衣', 'one-piece swimsuit', 'bikini', 57, TRUE, TRUE),
('lingerie_adult', 'clothing', '成年女性内衣', 'adult lingerie, lace underwear', 'fully dressed', 58, TRUE, TRUE),
('black_lingerie_adult', 'clothing', '黑色蕾丝内衣', 'adult black lace lingerie', 'white underwear, fully dressed', 59, TRUE, TRUE),
('bra_and_panties_adult', 'clothing', '成年胸罩与内裤', 'adult bra and panties', 'fully dressed', 60, TRUE, TRUE),
('corset', 'clothing', '束腰', 'corset', 'loose clothes', 61, TRUE, TRUE),
('bodysuit', 'clothing', '紧身连体衣', 'bodysuit, skin tight', 'loose clothes', 62, TRUE, TRUE),
('latex_bodysuit_adult', 'clothing', '成年乳胶紧身衣', 'adult latex bodysuit, shiny latex', 'matte fabric', 63, TRUE, TRUE),
('leather_jacket', 'clothing', '皮夹克', 'leather jacket', 'soft knitwear', 64, TRUE, TRUE),
('high_heels', 'clothing', '高跟鞋', 'high heels', 'flat shoes, barefoot', 65, TRUE, TRUE),
('stiletto_heels', 'clothing', '细高跟鞋', 'stiletto heels', 'flat shoes', 66, TRUE, TRUE),
('boots', 'clothing', '长靴', 'boots', 'sandals, barefoot', 67, TRUE, TRUE),
('thighhigh_boots', 'clothing', '过膝长靴', 'thighhigh boots', 'ankle boots', 68, TRUE, TRUE),
('choker', 'clothing', '颈圈', 'choker', 'bare neck', 69, TRUE, TRUE),

('happy', 'expression', '开心', 'happy expression', 'sad', 50, TRUE, FALSE),
('grin', 'expression', '露齿笑', 'grin', 'frown', 60, TRUE, FALSE),
('smirk', 'expression', '坏笑', 'smirk', 'innocent smile', 70, TRUE, FALSE),
('seductive_smile', 'expression', '魅惑微笑', 'seductive smile', 'angry, sad', 80, TRUE, FALSE),
('angry', 'expression', '生气', 'angry expression, glaring', 'smile', 90, TRUE, FALSE),
('sad', 'expression', '悲伤', 'sad expression, frown', 'smile', 100, TRUE, FALSE),
('surprised', 'expression', '惊讶', 'surprised, wide-eyed', 'expressionless', 110, TRUE, FALSE),
('embarrassed', 'expression', '害羞尴尬', 'embarrassed, blush', 'confident', 120, TRUE, FALSE),
('expressionless', 'expression', '无表情', 'expressionless', 'smile, open mouth', 130, TRUE, FALSE),
('sleepy', 'expression', '困倦', 'sleepy, half-closed eyes', 'wide-eyed', 140, TRUE, FALSE),
('wink', 'expression', '眨眼', 'wink, one eye closed', 'both eyes open', 150, TRUE, FALSE),
('open_mouth', 'expression', '张嘴', 'open mouth, parted lips', 'closed mouth', 160, TRUE, FALSE),
('ahegao_adult', 'expression', '成年阿黑颜', 'adult ahegao, rolled eyes, tongue out', 'expressionless', 170, TRUE, FALSE),
('afterglow_adult', 'expression', '成年余韵表情', 'adult afterglow, flushed face, satisfied expression', 'angry', 180, TRUE, FALSE),

('crouching', 'pose', '蹲姿', 'crouching', 'standing upright', 50, TRUE, FALSE),
('squatting', 'pose', '深蹲姿势', 'squatting', 'standing', 60, TRUE, FALSE),
('all_fours', 'pose', '四肢着地', 'on all fours', 'standing', 70, TRUE, FALSE),
('bending_over', 'pose', '弯腰', 'bending over', 'standing straight', 80, TRUE, FALSE),
('leaning_forward', 'pose', '身体前倾', 'leaning forward', 'leaning back', 90, TRUE, FALSE),
('leaning_back', 'pose', '身体后仰', 'leaning back', 'leaning forward', 100, TRUE, FALSE),
('crossed_legs', 'pose', '交叉双腿', 'crossed legs', 'spread legs', 110, TRUE, FALSE),
('spread_legs_adult', 'pose', '成年张腿姿势', 'adult spread legs', 'crossed legs', 120, TRUE, FALSE),
('legs_up', 'pose', '抬腿', 'legs up', 'feet on floor', 130, TRUE, FALSE),
('one_leg_raised', 'pose', '单腿抬起', 'one leg raised', 'both feet on floor', 140, TRUE, FALSE),
('arched_back', 'pose', '弓背', 'arched back', 'straight back', 150, TRUE, FALSE),
('contrapposto', 'pose', '对立式站姿', 'contrapposto, weight on one leg', 'rigid pose', 160, TRUE, FALSE),
('reclining', 'pose', '斜倚', 'reclining', 'standing', 170, TRUE, FALSE),
('foetal_position', 'pose', '蜷缩姿势', 'foetal position, curled up', 'standing', 180, TRUE, FALSE),

('straight_on', 'camera_angle', '正面平视', 'straight-on, front view', 'side view, rear view', 50, TRUE, FALSE),
('from_side', 'camera_angle', '侧面视角', 'from side, profile view', 'front view', 60, TRUE, FALSE),
('three_quarter_view', 'camera_angle', '四分之三视角', 'three-quarter view', 'straight-on', 70, TRUE, FALSE),
('dutch_angle', 'camera_angle', '荷兰角', 'dutch angle, tilted frame', 'level horizon', 80, TRUE, FALSE),
('over_shoulder', 'camera_angle', '越肩镜头', 'over-the-shoulder shot', 'straight-on', 90, TRUE, FALSE),
('pov', 'camera_angle', '第一人称视角', 'POV, first-person view', 'third-person view', 100, TRUE, FALSE),
('fisheye', 'camera_angle', '鱼眼视角', 'fisheye lens, wide-angle distortion', 'telephoto', 110, TRUE, FALSE),
('top_down', 'camera_angle', '俯视顶拍', 'top-down view, overhead shot', 'low angle', 120, TRUE, FALSE),
('worm_eye', 'camera_angle', '虫视角', 'worm''s-eye view, extreme low angle', 'high angle', 130, TRUE, FALSE),
('from_below_skirt_adult', 'camera_angle', '成年裙底低角度', 'adult low angle from below skirt', 'high angle', 140, TRUE, FALSE),

('extreme_close_up', 'shot_type', '极近特写', 'extreme close-up', 'full body, distant view', 50, TRUE, FALSE),
('portrait_shot', 'shot_type', '肖像镜头', 'portrait, head and shoulders', 'full body', 60, TRUE, FALSE),
('bust_shot', 'shot_type', '胸像镜头', 'bust shot', 'full body, feet', 70, TRUE, FALSE),
('waist_up', 'shot_type', '腰部以上', 'waist up', 'full body', 80, TRUE, FALSE),
('knees_up', 'shot_type', '膝盖以上', 'knees up', 'close-up', 90, TRUE, FALSE),
('wide_shot', 'shot_type', '远景', 'wide shot, distant view', 'close-up', 100, TRUE, FALSE),
('panorama', 'shot_type', '全景', 'panorama, panoramic view', 'close-up, narrow frame', 110, TRUE, FALSE),

('living_room', 'scene', '客厅', 'living room interior', 'outdoors', 60, TRUE, FALSE),
('bathroom', 'scene', '浴室', 'bathroom, tiled walls', 'outdoors', 70, TRUE, FALSE),
('shower', 'scene', '淋浴间', 'shower room, steam, wet', 'dry room', 80, TRUE, FALSE),
('bathtub', 'scene', '浴缸', 'bathtub, bathroom', 'outdoors', 90, TRUE, FALSE),
('hotel_room', 'scene', '酒店房间', 'hotel room', 'outdoors', 100, TRUE, FALSE),
('office', 'scene', '办公室', 'modern office interior', 'outdoors', 110, TRUE, FALSE),
('classroom', 'scene', '教室', 'classroom', 'outdoors', 120, TRUE, FALSE),
('library', 'scene', '图书馆', 'library, bookshelves', 'outdoors', 130, TRUE, FALSE),
('gym', 'scene', '健身房', 'gym interior, exercise equipment', 'outdoors', 140, TRUE, FALSE),
('swimming_pool', 'scene', '游泳池', 'swimming pool', 'dry land', 150, TRUE, FALSE),
('hot_spring', 'scene', '温泉', 'hot spring, steam, rocks', 'city', 160, TRUE, FALSE),
('rooftop', 'scene', '屋顶', 'rooftop, city skyline', 'indoors', 170, TRUE, FALSE),
('balcony', 'scene', '阳台', 'balcony', 'windowless room', 180, TRUE, FALSE),
('night_city', 'scene', '夜晚城市', 'city at night, neon lights', 'daytime countryside', 190, TRUE, FALSE),
('alley', 'scene', '小巷', 'narrow alley, urban', 'open field', 200, TRUE, FALSE),
('train_interior', 'scene', '列车车厢', 'train interior', 'outdoors', 210, TRUE, FALSE),
('car_interior', 'scene', '汽车内部', 'car interior', 'outdoors', 220, TRUE, FALSE),
('restaurant', 'scene', '餐厅', 'restaurant interior', 'outdoors', 230, TRUE, FALSE),
('bar', 'scene', '酒吧', 'bar interior, ambient lighting', 'daylight outdoors', 240, TRUE, FALSE),
('stage', 'scene', '舞台', 'stage, spotlights', 'private room', 250, TRUE, FALSE),
('fantasy_castle', 'scene', '幻想城堡', 'fantasy castle', 'modern city', 260, TRUE, FALSE),
('simple_background', 'scene', '简洁背景', 'simple background', 'detailed background', 270, TRUE, FALSE),

('diagonal_composition', 'composition', '对角线构图', 'diagonal composition', 'static horizontal composition', 60, TRUE, TRUE),
('triangular_composition', 'composition', '三角形构图', 'triangular composition', 'scattered composition', 70, TRUE, TRUE),
('leading_lines', 'composition', '引导线', 'leading lines', 'random lines', 80, TRUE, TRUE),
('foreground_framing', 'composition', '前景框架', 'foreground framing', 'flat framing', 90, TRUE, TRUE),
('layered_depth', 'composition', '多层景深', 'layered depth, foreground, midground, background', 'flat image', 100, TRUE, TRUE),
('bokeh', 'composition', '背景虚化光斑', 'bokeh, blurred background', 'sharp busy background', 110, TRUE, TRUE),
('motion_blur', 'composition', '动感模糊', 'motion blur, sense of speed', 'static scene', 120, TRUE, TRUE),
('rim_light', 'composition', '轮廓光', 'rim light', 'flat lighting', 130, TRUE, TRUE),
('backlighting', 'composition', '逆光', 'backlighting, glowing silhouette', 'front lighting', 140, TRUE, TRUE),
('volumetric_light', 'composition', '体积光', 'volumetric lighting, light rays', 'flat lighting', 150, TRUE, TRUE),
('cinematic_lighting', 'composition', '电影感灯光', 'cinematic lighting', 'flat lighting', 160, TRUE, TRUE),
('dramatic_shadows', 'composition', '戏剧性阴影', 'dramatic shadows, high contrast', 'flat lighting', 170, TRUE, TRUE),
('shallow_depth_of_field', 'composition', '浅景深', 'shallow depth of field, subject focus', 'everything in focus', 180, TRUE, TRUE),
('negative_space', 'composition', '留白构图', 'negative space composition', 'cluttered composition', 190, TRUE, TRUE),

('amazing_quality', 'quality', '惊艳画质', 'amazing quality', 'bad quality', 50, TRUE, TRUE),
('very_aesthetic', 'quality', '高审美', 'very aesthetic', 'displeasing', 60, TRUE, TRUE),
('ultra_detailed', 'quality', '极致细节', 'ultra detailed', 'low detail', 70, TRUE, TRUE),
('sharp_focus', 'quality', '锐利对焦', 'sharp focus', 'blurry, out of focus', 80, TRUE, TRUE),
('high_resolution', 'quality', '高分辨率', 'high resolution', 'lowres', 90, TRUE, TRUE),
('professional_photography', 'quality', '专业摄影质感', 'professional photography', 'amateur photo', 100, TRUE, TRUE),
('cinematic', 'quality', '电影质感', 'cinematic', 'flat image', 110, TRUE, TRUE),
('photorealistic', 'quality', '照片级真实', 'photorealistic', 'cartoon', 120, TRUE, TRUE),
('anime_screencap', 'quality', '动画截图风格', 'anime screencap', 'photorealistic', 130, TRUE, TRUE),
('illustration', 'quality', '精致插画', 'detailed illustration', 'photograph', 140, TRUE, TRUE);
