INSERT INTO c_PromptOptions(Id, Category, Name, PositivePrompt, NegativePrompt, SortOrder, Enabled, AllowMultiple) VALUES
('one_boy_one_girl', 'character_type', '一男一女', '1boy, 1girl', 'single gender', 1, TRUE, TRUE),
('two_girls', 'character_type', '两名女性', '2girls', 'male, solo', 2, TRUE, TRUE),
('two_boys', 'character_type', '两名男性', '2boys', 'female, solo', 3, TRUE, TRUE),
('three_girls', 'character_type', '三名女性', '3girls', 'male, solo', 4, TRUE, TRUE),
('three_boys', 'character_type', '三名男性', '3boys', 'female, solo', 5, TRUE, TRUE),
('two_girls_one_boy', 'character_type', '两女一男', '2girls, 1boy', 'single gender, solo', 6, TRUE, TRUE),
('one_girl_two_boys', 'character_type', '一女两男', '1girl, 2boys', 'single gender, solo', 7, TRUE, TRUE),
('three_girls_one_boy', 'character_type', '三女一男', '3girls, 1boy', 'single gender, solo', 8, TRUE, TRUE),
('one_girl_three_boys', 'character_type', '一女三男', '1girl, 3boys', 'single gender, solo', 9, TRUE, TRUE),
('mixed_gender_group', 'character_type', '男女混合多人', 'mixed-gender group, multiple girls, multiple boys', 'single gender, solo', 10, TRUE, TRUE),
('two_women_adult', 'character_type', '两名成年女性', '2 adult women', 'child, male', 11, TRUE, TRUE),
('two_men_adult', 'character_type', '两名成年男性', '2 adult men', 'child, female', 12, TRUE, TRUE),
('adult_man_woman', 'character_type', '成年男女', 'adult man and adult woman', 'child, single gender', 13, TRUE, TRUE),
('adult_women_group', 'character_type', '成年女性群体', 'group of adult women', 'child, male only', 14, TRUE, TRUE),
('heart_hands', 'action', '双手比心', 'heart hands', NULL, 330, TRUE, TRUE),
('finger_heart', 'action', '手指比心', 'finger heart', NULL, 340, TRUE, TRUE),
('thumbs_up', 'action', '竖起拇指', 'thumbs up', NULL, 350, TRUE, TRUE),
('pointing_at_viewer', 'action', '指向镜头', 'pointing at viewer', 'pointing away', 360, TRUE, TRUE),
('beckoning', 'action', '招手示意靠近', 'beckoning', NULL, 370, TRUE, TRUE),
('salute', 'action', '敬礼', 'salute', NULL, 380, TRUE, TRUE),
('high_five', 'action', '击掌', 'high five', 'separated hands', 390, TRUE, TRUE),
('fist_bump', 'action', '碰拳', 'fist bump', 'separated hands', 400, TRUE, TRUE),
('clapping', 'action', '鼓掌', 'clapping', NULL, 410, TRUE, TRUE),
('shrugging', 'action', '耸肩', 'shrugging', NULL, 420, TRUE, TRUE),
('facepalm', 'action', '捂脸', 'facepalm', NULL, 430, TRUE, TRUE),
('covering_mouth', 'action', '手掩嘴', 'covering mouth', NULL, 440, TRUE, TRUE),
('looking_back', 'action', '回眸', 'looking back', 'looking forward', 450, TRUE, TRUE),
('looking_up', 'action', '向上看', 'looking up', 'looking down', 460, TRUE, TRUE),
('looking_down', 'action', '向下看', 'looking down', 'looking up', 470, TRUE, TRUE),
('whispering', 'action', '耳语', 'whispering', NULL, 480, TRUE, TRUE),
('headpat', 'action', '摸头', 'headpat', NULL, 490, TRUE, TRUE),
('cuddling', 'action', '依偎', 'cuddling', 'separated', 500, TRUE, TRUE),
('hair_bow', 'clothing', '蝴蝶结发饰', 'hair bow', 'no hair ornament', 70, TRUE, TRUE),
('hair_ribbon', 'clothing', '发带', 'hair ribbon', 'no hair ornament', 71, TRUE, TRUE),
('hairclip', 'clothing', '发夹', 'hairclip', 'no hair ornament', 72, TRUE, TRUE),
('hair_flower', 'clothing', '花朵发饰', 'hair flower', 'no hair ornament', 73, TRUE, TRUE),
('headband', 'clothing', '头箍', 'headband', 'no headwear', 74, TRUE, TRUE),
('glasses', 'clothing', '眼镜', 'glasses', 'no eyewear', 75, TRUE, TRUE),
('sunglasses', 'clothing', '太阳镜', 'sunglasses', 'clear glasses', 76, TRUE, TRUE),
('earrings', 'clothing', '耳环', 'earrings', 'no earrings', 77, TRUE, TRUE),
('necklace', 'clothing', '项链', 'necklace', 'bare neck', 78, TRUE, TRUE),
('bracelet', 'clothing', '手链', 'bracelet', 'no jewelry', 79, TRUE, TRUE),
('wristwatch', 'clothing', '腕表', 'wristwatch', 'bare wrist', 80, TRUE, TRUE),
('scarf', 'clothing', '围巾', 'scarf', 'bare neck', 81, TRUE, TRUE),
('wet_clothes', 'clothing', '湿透衣物', 'wet clothes, wet fabric', 'dry clothes', 82, TRUE, TRUE),
('wet_shirt', 'clothing', '湿衬衫', 'wet shirt, see-through wet fabric', 'dry shirt', 83, TRUE, TRUE),
('rainy_street', 'scene', '雨夜街道', 'rainy street at night, reflections', 'dry weather', 280, TRUE, FALSE),
('underwater', 'scene', '水下', 'underwater, bubbles, caustic light', 'dry land', 290, TRUE, FALSE),
('poolside', 'scene', '泳池边', 'poolside', 'indoors', 300, TRUE, FALSE),
('lake', 'scene', '湖边', 'lake, lakeside', 'city interior', 310, TRUE, FALSE),
('snowy_scene', 'scene', '雪景', 'snowy scene, falling snow', 'summer', 320, TRUE, FALSE),
('sunset', 'scene', '日落', 'sunset, golden hour', 'midday', 330, TRUE, FALSE),
('starry_night', 'scene', '星空夜景', 'starry night, night sky', 'daytime', 340, TRUE, FALSE),
('cherry_blossoms', 'scene', '樱花场景', 'cherry blossoms, falling petals', 'winter', 350, TRUE, FALSE);
