INSERT INTO c_PromptOptions(Id, Category, Name, PositivePrompt, NegativePrompt, SortOrder, Enabled, AllowMultiple) VALUES
('adult_missionary', 'pose', '成人传教士姿势', 'adult couple, missionary position', '', 500, TRUE, FALSE),
('adult_mating_press', 'pose', '成人交配压制姿势', 'adult couple, mating press', '', 510, TRUE, FALSE),
('adult_doggystyle', 'pose', '成人后入式', 'adult couple, doggystyle, sex from behind', '', 520, TRUE, FALSE),
('adult_prone_bone', 'pose', '成人俯卧后入式', 'adult couple, prone bone', '', 530, TRUE, FALSE),
('adult_bent_over_sex', 'pose', '成人弯腰后入式', 'adult couple, bent over, sex from behind', '', 540, TRUE, FALSE),
('adult_spooning_sex', 'pose', '成人侧卧抱姿', 'adult couple, spooning, on side', '', 550, TRUE, FALSE),
('adult_cowgirl_position', 'pose', '成人女上位', 'adult couple, cowgirl position', '', 560, TRUE, FALSE),
('adult_reverse_cowgirl', 'pose', '成人反向女上位', 'adult couple, reverse cowgirl position', '', 570, TRUE, FALSE),
('adult_squatting_cowgirl', 'pose', '成人蹲式女上位', 'adult couple, squatting cowgirl position', '', 580, TRUE, FALSE),
('adult_reverse_squatting_cowgirl', 'pose', '成人反向蹲式女上位', 'adult couple, reverse squatting cowgirl position', '', 590, TRUE, FALSE),
('adult_amazon_position', 'pose', '成人亚马逊姿势', 'adult couple, amazon position', '', 600, TRUE, FALSE),
('adult_upright_straddle', 'pose', '成人正向跨坐', 'adult couple, upright straddle', '', 610, TRUE, FALSE),
('adult_reverse_upright_straddle', 'pose', '成人反向跨坐', 'adult couple, reverse upright straddle', '', 620, TRUE, FALSE),
('adult_anvil_position', 'pose', '成人铁砧姿势', 'adult couple, anvil position', '', 630, TRUE, FALSE),
('adult_knees_to_chest', 'pose', '成人屈膝抱胸姿势', 'adult couple, knees to chest', '', 640, TRUE, FALSE),
('adult_legs_over_head', 'pose', '成人双腿过头姿势', 'adult couple, legs over head', '', 650, TRUE, FALSE),
('adult_standing_sex', 'pose', '成人站立性爱姿势', 'adult couple, standing sex', '', 660, TRUE, FALSE),
('adult_standing_missionary', 'pose', '成人站立传教士姿势', 'adult couple, standing missionary', '', 670, TRUE, FALSE),
('adult_suspended_congress', 'pose', '成人悬抱姿势', 'adult couple, suspended congress', '', 680, TRUE, FALSE),
('adult_reverse_suspended_congress', 'pose', '成人反向悬抱姿势', 'adult couple, reverse suspended congress', '', 690, TRUE, FALSE),
('adult_full_nelson_position', 'pose', '成人全尼尔森姿势', 'adult couple, full nelson', '', 700, TRUE, FALSE),
('adult_piledriver_position', 'pose', '成人打桩机姿势', 'adult couple, piledriver position', '', 710, TRUE, FALSE),
('adult_69_position', 'pose', '成人六九式', 'adult couple, 69 position', '', 720, TRUE, FALSE),
('adult_spitroast', 'pose', '成人夹心式', 'adults, spitroast position', '', 730, TRUE, FALSE),
('adult_reverse_spitroast', 'pose', '成人反向夹心式', 'adults, reverse spitroast position', '', 740, TRUE, FALSE),
('adult_top_down_bottom_up', 'pose', '成人上下交叠姿势', 'adults, top-down bottom-up position', '', 750, TRUE, FALSE),
('adult_mounting_position', 'pose', '成人骑乘姿势', 'adult couple, mounting position', '', 760, TRUE, FALSE);
