ALTER TABLE maid_AgentToolCalls
    MODIFY COLUMN Id BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN ParentToolCallId BIGINT NULL;

ALTER TABLE maid_VoiceRoleAudioCaches
    MODIFY COLUMN Id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE maid_VoiceRoleBindings
    MODIFY COLUMN Id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE maid_VoiceTriggerLogs
    MODIFY COLUMN Id BIGINT NOT NULL AUTO_INCREMENT;
