CREATE TABLE q_market_dataset (
    Id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    Provider                 VARCHAR(32)  NOT NULL,
    MarketType               VARCHAR(32)  NOT NULL,
    DataType                 VARCHAR(32)  NOT NULL,
    Symbol                   VARCHAR(32)  NOT NULL,
    IntervalCode             VARCHAR(16)  NOT NULL,
    EarliestOpenTimeMs       BIGINT       NULL,
    LatestOpenTimeMs         BIGINT       NULL,
    CandleCount              BIGINT       NOT NULL DEFAULT 0,
    ExpectedInsideRange      BIGINT       NOT NULL DEFAULT 0,
    GapCount                 BIGINT       NOT NULL DEFAULT 0,
    Status                   VARCHAR(32)  NOT NULL,
    LastSuccessfulSyncAt      DATETIME(6)  NULL,
    LastValidatedAt          DATETIME(6)  NULL,
    LastSyncTaskId           VARCHAR(36)  NULL,
    CreatedAt                DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UpdatedAt                DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_dataset_key (Provider, MarketType, DataType, Symbol, IntervalCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE q_market_candle (
    Id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    DatasetId                BIGINT       NOT NULL,
    Provider                 VARCHAR(32)  NOT NULL,
    MarketType               VARCHAR(32)  NOT NULL,
    Symbol                   VARCHAR(32)  NOT NULL,
    IntervalCode             VARCHAR(16)  NOT NULL,
    OpenTimeMs               BIGINT       NOT NULL,
    CloseTimeMs              BIGINT       NOT NULL,
    OpenPrice                DECIMAL(38,18) NOT NULL,
    HighPrice                DECIMAL(38,18) NOT NULL,
    LowPrice                 DECIMAL(38,18) NOT NULL,
    ClosePrice               DECIMAL(38,18) NOT NULL,
    Volume                   DECIMAL(38,18) NOT NULL,
    QuoteVolume              DECIMAL(38,18) NOT NULL,
    TradeCount               BIGINT       NOT NULL,
    TakerBuyBaseVolume       DECIMAL(38,18) NOT NULL,
    TakerBuyQuoteVolume      DECIMAL(38,18) NOT NULL,
    Source                   VARCHAR(32)  NOT NULL,
    CreatedAt                DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_candle_key (Provider, MarketType, Symbol, IntervalCode, OpenTimeMs),
    INDEX idx_candle_dataset_time (DatasetId, OpenTimeMs),
    INDEX idx_candle_sym_int_time (Symbol, IntervalCode, OpenTimeMs)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE q_market_sync_task (
    Id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    TaskId                   VARCHAR(36)  NOT NULL,
    DatasetId                BIGINT       NOT NULL,
    ActiveDatasetKey         VARCHAR(160) NULL,
    Provider                 VARCHAR(32)  NOT NULL,
    MarketType               VARCHAR(32)  NOT NULL,
    DataType                 VARCHAR(32)  NOT NULL,
    Symbol                   VARCHAR(32)  NOT NULL,
    IntervalCode             VARCHAR(16)  NOT NULL,
    RequestedStartTimeMs     BIGINT       NOT NULL,
    RequestedEndTimeMs       BIGINT       NOT NULL,
    NormalizedStartTimeMs    BIGINT       NOT NULL,
    NormalizedEndTimeMs      BIGINT       NOT NULL,
    ExpectedCount            BIGINT       NOT NULL DEFAULT 0,
    FetchedCount             BIGINT       NOT NULL DEFAULT 0,
    InsertedCount            BIGINT       NOT NULL DEFAULT 0,
    ExistingCount            BIGINT       NOT NULL DEFAULT 0,
    ConflictCount            BIGINT       NOT NULL DEFAULT 0,
    GapCount                 BIGINT       NOT NULL DEFAULT 0,
    BatchCount               INT          NOT NULL DEFAULT 0,
    ProgressPercent          DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
    Status                   VARCHAR(32)  NOT NULL,
    ErrorCode                VARCHAR(64)  NULL,
    ErrorMessage             VARCHAR(512) NULL,
    UsedWeight1m             INT          NULL,
    RetryAfterSeconds        INT          NULL,
    QueuedAt                 DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    StartedAt                DATETIME(6)  NULL,
    FinishedAt               DATETIME(6)  NULL,
    UpdatedAt                DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_task_id (TaskId),
    UNIQUE KEY uk_active_dataset (ActiveDatasetKey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE q_market_data_gap (
    Id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    DatasetId                BIGINT       NOT NULL,
    StartOpenTimeMs          BIGINT       NOT NULL,
    EndOpenTimeMsExclusive   BIGINT       NOT NULL,
    MissingCount             BIGINT       NOT NULL,
    DetectedByTaskId         VARCHAR(36)  NOT NULL,
    DetectedAt               DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_gap_dataset_start (DatasetId, StartOpenTimeMs)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
