CREATE TABLE q_backtest_run (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    RunId VARCHAR(36) NOT NULL,
    DatasetId BIGINT NOT NULL,
    DatasetLastValidatedAt DATETIME(6) NULL,
    DatasetLastSyncTaskId VARCHAR(36) NULL,
    Provider VARCHAR(32) NOT NULL,
    MarketType VARCHAR(32) NOT NULL,
    DataType VARCHAR(32) NOT NULL,
    Symbol VARCHAR(32) NOT NULL,
    IntervalCode VARCHAR(16) NOT NULL,
    StartOpenTimeMs BIGINT NOT NULL,
    EndOpenTimeExclusiveMs BIGINT NOT NULL,
    StrategyCode VARCHAR(64) NOT NULL,
    StrategyVersion VARCHAR(32) NOT NULL,
    RequestedParametersJson LONGTEXT NOT NULL,
    ResolvedParametersJson LONGTEXT NULL,
    OrderAmount DECIMAL(38,18) NOT NULL,
    FeeRate DECIMAL(38,18) NOT NULL,
    ForceCloseAtEnd TINYINT(1) NOT NULL,
    Status VARCHAR(32) NOT NULL,
    ProgressPercent DECIMAL(7,4) NOT NULL DEFAULT 0,
    BarCount INT NULL,
    TradeCount INT NULL,
    WinningTradeCount INT NULL,
    LosingTradeCount INT NULL,
    BreakEvenTradeCount INT NULL,
    WinRate DECIMAL(38,18) NULL,
    GrossProfit DECIMAL(38,18) NULL,
    GrossLoss DECIMAL(38,18) NULL,
    NetProfit DECIMAL(38,18) NULL,
    TotalReturnRatio DECIMAL(38,18) NULL,
    MaximumDrawdownRatio DECIMAL(38,18) NULL,
    ProfitFactor DECIMAL(38,18) NULL,
    AverageTradeReturnRatio DECIMAL(38,18) NULL,
    BuyAndHoldReturnRatio DECIMAL(38,18) NULL,
    TotalFees DECIMAL(38,18) NULL,
    ExecutionModel VARCHAR(64) NULL,
    WarningsJson LONGTEXT NULL,
    EquityPointCount INT NULL,
    ErrorCode VARCHAR(64) NULL,
    ErrorMessage VARCHAR(1000) NULL,
    QueuedAt DATETIME(6) NOT NULL,
    StartedAt DATETIME(6) NULL,
    FinishedAt DATETIME(6) NULL,
    UpdatedAt DATETIME(6) NOT NULL,
    CONSTRAINT uk_backtest_run_id UNIQUE (RunId),
    INDEX idx_backtest_run_status_queue (Status, QueuedAt),
    INDEX idx_backtest_run_symbol_interval (Symbol, IntervalCode, QueuedAt),
    INDEX idx_backtest_run_strategy (StrategyCode, QueuedAt)
);

CREATE TABLE q_backtest_trade (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    RunId VARCHAR(36) NOT NULL,
    TradeNo INT NOT NULL,
    EntrySignalIndex INT NOT NULL,
    EntryIndex INT NOT NULL,
    EntryTimeMs BIGINT NOT NULL,
    EntryPrice DECIMAL(38,18) NOT NULL,
    ExitSignalIndex INT NULL,
    ExitIndex INT NOT NULL,
    ExitTimeMs BIGINT NOT NULL,
    ExitPrice DECIMAL(38,18) NOT NULL,
    Amount DECIMAL(38,18) NOT NULL,
    GrossProfit DECIMAL(38,18) NOT NULL,
    Fee DECIMAL(38,18) NOT NULL,
    NetProfit DECIMAL(38,18) NOT NULL,
    ReturnRatio DECIMAL(38,18) NOT NULL,
    BarsHeld INT NOT NULL,
    ForcedExit TINYINT(1) NOT NULL,
    ExitReason VARCHAR(64) NOT NULL,
    CONSTRAINT uk_backtest_trade_run_no UNIQUE (RunId, TradeNo),
    INDEX idx_backtest_trade_run_no (RunId, TradeNo)
);

CREATE TABLE q_backtest_equity (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    RunId VARCHAR(36) NOT NULL,
    PointIndex INT NOT NULL,
    OpenTimeMs BIGINT NOT NULL,
    EquityRatio DECIMAL(38,18) NOT NULL,
    DrawdownRatio DECIMAL(38,18) NOT NULL,
    InPosition TINYINT(1) NOT NULL,
    CONSTRAINT uk_backtest_equity_run_index UNIQUE (RunId, PointIndex),
    INDEX idx_backtest_equity_run_time (RunId, OpenTimeMs)
);
