CREATE TABLE q_walk_forward_study (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    StudyId VARCHAR(36) NOT NULL,
    DatasetId BIGINT NOT NULL,
    Provider VARCHAR(32) NOT NULL,
    MarketType VARCHAR(32) NOT NULL,
    DataType VARCHAR(32) NOT NULL,
    Symbol VARCHAR(64) NOT NULL,
    IntervalCode VARCHAR(16) NOT NULL,
    StrategyCode VARCHAR(128) NOT NULL,
    StrategyVersion VARCHAR(32) NOT NULL,
    ParameterGridJson JSON NOT NULL,
    WindowMode VARCHAR(16) NOT NULL,
    StudyStartOpenTimeMs BIGINT NOT NULL,
    StudyEndOpenTimeMs BIGINT NOT NULL,
    TrainingBars INT NOT NULL,
    ValidationBars INT NOT NULL,
    StepBars INT NOT NULL,
    FoldCount INT NOT NULL,
    CandidateCountPerFold INT NOT NULL,
    TotalChildRuns INT NOT NULL,
    SelectionMetric VARCHAR(64) NOT NULL,
    MinimumTrainTrades INT NOT NULL,
    OrderAmount DECIMAL(38,18) NOT NULL,
    FeeRate DECIMAL(38,18) NOT NULL,
    ForceCloseAtEnd BOOLEAN NOT NULL,
    Status VARCHAR(32) NOT NULL,
    ProgressPercent DECIMAL(7,4) NOT NULL DEFAULT 0,
    ErrorCode VARCHAR(128) NULL,
    ErrorMessage VARCHAR(1000) NULL,
    CreatedAt DATETIME(3) NOT NULL,
    UpdatedAt DATETIME(3) NOT NULL,
    StartedAt DATETIME(3) NULL,
    FinishedAt DATETIME(3) NULL,
    CONSTRAINT uk_walk_forward_study_id UNIQUE (StudyId),
    INDEX ix_walk_forward_study_status_created (Status, CreatedAt, Id),
    INDEX ix_walk_forward_study_strategy_created (StrategyCode, CreatedAt, Id),
    INDEX ix_walk_forward_study_symbol_created (Symbol, CreatedAt, Id)
);

CREATE TABLE q_walk_forward_fold (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    FoldId VARCHAR(36) NOT NULL,
    StudyId VARCHAR(36) NOT NULL,
    FoldIndex INT NOT NULL,
    TrainingStartOpenTimeMs BIGINT NOT NULL,
    TrainingEndOpenTimeMs BIGINT NOT NULL,
    ValidationStartOpenTimeMs BIGINT NOT NULL,
    ValidationEndOpenTimeMs BIGINT NOT NULL,
    ExperimentId VARCHAR(36) NOT NULL,
    Status VARCHAR(32) NOT NULL,
    ClaimToken VARCHAR(36) NULL,
    ClaimedAt DATETIME(3) NULL,
    SelectedCandidateId VARCHAR(36) NULL,
    SelectedParametersJson JSON NULL,
    SelectedTrainingRunId VARCHAR(36) NULL,
    SelectedValidationRunId VARCHAR(36) NULL,
    SelectionMetricValue DECIMAL(38,18) NULL,
    ErrorCode VARCHAR(128) NULL,
    ErrorMessage VARCHAR(1000) NULL,
    CreatedAt DATETIME(3) NOT NULL,
    UpdatedAt DATETIME(3) NOT NULL,
    StartedAt DATETIME(3) NULL,
    FinishedAt DATETIME(3) NULL,
    CONSTRAINT uk_walk_forward_fold_id UNIQUE (FoldId),
    CONSTRAINT uk_walk_forward_study_fold UNIQUE (StudyId, FoldIndex),
    CONSTRAINT uk_walk_forward_experiment_id UNIQUE (ExperimentId),
    INDEX ix_walk_forward_fold_study_index (StudyId, FoldIndex),
    INDEX ix_walk_forward_fold_study_status (StudyId, Status, FoldIndex),
    INDEX ix_walk_forward_fold_status_claimed (Status, ClaimedAt)
);
