CREATE TABLE q_research_study (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ResearchStudyId CHAR(36) NOT NULL,
    Name VARCHAR(120) NOT NULL,
    Description VARCHAR(2000) NULL,
    DatasetId BIGINT NOT NULL,
    Provider VARCHAR(32) NOT NULL,
    MarketType VARCHAR(32) NOT NULL,
    DataType VARCHAR(32) NOT NULL,
    Symbol VARCHAR(64) NOT NULL,
    IntervalCode VARCHAR(16) NOT NULL,
    StrategyCode VARCHAR(128) NOT NULL,
    StrategyVersion VARCHAR(64) NOT NULL,
    ExecutionProfileCode VARCHAR(64) NOT NULL,
    DirectionMode VARCHAR(32) NOT NULL,
    OrderSizingMode VARCHAR(32) NOT NULL,
    EvaluationMode VARCHAR(32) NOT NULL,
    ParameterSpaceMode VARCHAR(32) NOT NULL,
    ParameterSpaceJson JSON NOT NULL,
    ExpandedParameterGridJson JSON NOT NULL,
    CandidateCount INT NOT NULL,
    StudyStartOpenTimeMs BIGINT NOT NULL,
    StudyEndOpenTimeMs BIGINT NOT NULL,
    TrainingBars INT NOT NULL,
    ValidationBars INT NOT NULL,
    SelectionMetric VARCHAR(64) NOT NULL,
    MinimumTrainTrades INT NOT NULL,
    OrderAmount DECIMAL(38,18) NOT NULL,
    FeeRate DECIMAL(38,18) NOT NULL,
    ForceCloseAtEnd BOOLEAN NOT NULL,
    ComparisonGroupKey CHAR(64) NOT NULL,
    WalkForwardStudyId CHAR(36) NOT NULL,
    Status VARCHAR(32) NOT NULL,
    ProgressPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
    ErrorCode VARCHAR(128) NULL,
    ErrorMessage VARCHAR(1000) NULL,
    CreatedAt DATETIME(6) NOT NULL,
    StartedAt DATETIME(6) NULL,
    FinishedAt DATETIME(6) NULL,
    UpdatedAt DATETIME(6) NOT NULL,
    CONSTRAINT uk_research_study_id UNIQUE (ResearchStudyId),
    CONSTRAINT uk_research_study_child UNIQUE (WalkForwardStudyId),
    CONSTRAINT ck_research_study_candidates CHECK (CandidateCount BETWEEN 1 AND 64),
    CONSTRAINT ck_research_study_force_close CHECK (ForceCloseAtEnd = TRUE),
    INDEX ix_research_study_status_updated (Status, UpdatedAt, ResearchStudyId),
    INDEX ix_research_study_created (CreatedAt, ResearchStudyId),
    INDEX ix_research_study_group_created (ComparisonGroupKey, CreatedAt, ResearchStudyId),
    INDEX ix_research_study_strategy_created (StrategyCode, StrategyVersion, CreatedAt),
    INDEX ix_research_study_dataset_created (DatasetId, CreatedAt)
);
