package com.aiprovider.model.vo;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PlatformAccountVO {
    private long id;private String platform;private String accountKind;private String displayName;private String accountHandle;private String adapterType;private String publicConfigJson;private boolean enabled;private String connectionStatus;private String credentialHint;private LocalDateTime lastValidatedAt;private LocalDateTime lastConnectedAt;private String lastErrorCode;private String lastErrorMessage;private List<String> credentialTypes=new ArrayList<>();private List<String> credentialHints=new ArrayList<>();
    public long getId(){return id;}public void setId(long v){id=v;}public String getPlatform(){return platform;}public void setPlatform(String v){platform=v;}public String getAccountKind(){return accountKind;}public void setAccountKind(String v){accountKind=v;}public String getDisplayName(){return displayName;}public void setDisplayName(String v){displayName=v;}public String getAccountHandle(){return accountHandle;}public void setAccountHandle(String v){accountHandle=v;}public String getAdapterType(){return adapterType;}public void setAdapterType(String v){adapterType=v;}public String getPublicConfigJson(){return publicConfigJson;}public void setPublicConfigJson(String v){publicConfigJson=v;}public boolean isEnabled(){return enabled;}public void setEnabled(boolean v){enabled=v;}public String getConnectionStatus(){return connectionStatus;}public void setConnectionStatus(String v){connectionStatus=v;}public String getCredentialHint(){return credentialHint;}public void setCredentialHint(String v){credentialHint=v;}public LocalDateTime getLastValidatedAt(){return lastValidatedAt;}public void setLastValidatedAt(LocalDateTime v){lastValidatedAt=v;}public LocalDateTime getLastConnectedAt(){return lastConnectedAt;}public void setLastConnectedAt(LocalDateTime v){lastConnectedAt=v;}public String getLastErrorCode(){return lastErrorCode;}public void setLastErrorCode(String v){lastErrorCode=v;}public String getLastErrorMessage(){return lastErrorMessage;}public void setLastErrorMessage(String v){lastErrorMessage=v;}public List<String> getCredentialTypes(){return credentialTypes;}public void setCredentialTypes(List<String> v){credentialTypes=v;}public List<String> getCredentialHints(){return credentialHints;}public void setCredentialHints(List<String> v){credentialHints=v;}
    @Override public String toString(){return "PlatformAccountVO{id="+id+",platform='"+platform+"',displayName='"+displayName+"',credentialTypes="+credentialTypes+"}";}
}
