package com.aiprovider.service;

import com.aiprovider.model.vo.XhsPublicationResultVO;
import com.aiprovider.repository.ContentOperationsRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class XiaohongshuPublicationServiceTest {
    @TempDir Path temp;
    @Test void publishesTextCardAndPersistsSuccess() throws Exception {ContentOperationsRepository repository=mock(ContentOperationsRepository.class);PlatformAccountCredentialService credentials=mock(PlatformAccountCredentialService.class);XiaohongshuWebAdapter adapter=mock(XiaohongshuWebAdapter.class);XhsTextCardRenderer renderer=mock(XhsTextCardRenderer.class);Map<String,Object> task=new HashMap<>();task.put("status","PENDING");task.put("accountEnabled",true);task.put("platformAccountId",12L);task.put("title","标题");task.put("body","正文");task.put("tagsJson","[\"AI\"]");task.put("accountId",2L);task.put("contentItemId",3L);when(repository.findPublicationDetails(1)).thenReturn(task);when(repository.claimPublication(1)).thenReturn(true);when(credentials.requireSecret(12L,"XIAOHONGSHU","STORAGE_STATE")).thenReturn("state");Path card=Files.createFile(temp.resolve("card.png"));when(renderer.render(1,"标题","正文")).thenReturn(card);when(adapter.publish(eq("state"),eq("标题"),eq("正文"),eq(Collections.singletonList("AI")),eq(card))).thenReturn("https://creator.xiaohongshu.com/success");XhsPublicationResultVO result=new XiaohongshuPublicationService(repository,credentials,adapter,renderer,new ObjectMapper()).publish(1);assertEquals("PUBLISHED",result.getStatus());verify(repository).markPublicationPublished(1,"https://creator.xiaohongshu.com/success");verify(repository).markAccountPublished(2);verify(repository).markContentItemPublished(3);assertFalse(Files.exists(card));}
    @Test void failsBeforeAutomationWhenSessionMissing(){ContentOperationsRepository repository=mock(ContentOperationsRepository.class);Map<String,Object> task=new HashMap<>();task.put("status","PENDING");task.put("accountEnabled",true);when(repository.findPublicationDetails(1)).thenReturn(task);XiaohongshuPublicationService service=new XiaohongshuPublicationService(repository,mock(PlatformAccountCredentialService.class),mock(XiaohongshuWebAdapter.class),mock(XhsTextCardRenderer.class),new ObjectMapper());assertThrows(IllegalArgumentException.class,()->service.publish(1));verify(repository,never()).claimPublication(anyLong());}
    @Test void marksUncertainResultAndPreventsBlindRetry() throws Exception {ContentOperationsRepository repository=mock(ContentOperationsRepository.class);PlatformAccountCredentialService credentials=mock(PlatformAccountCredentialService.class);XiaohongshuWebAdapter adapter=mock(XiaohongshuWebAdapter.class);XhsTextCardRenderer renderer=mock(XhsTextCardRenderer.class);Map<String,Object> task=new HashMap<>();task.put("status","PENDING");task.put("accountEnabled",true);task.put("platformAccountId",12L);task.put("title","标题");task.put("body","正文");task.put("accountId",2L);task.put("contentItemId",3L);when(repository.findPublicationDetails(1)).thenReturn(task);when(repository.claimPublication(1)).thenReturn(true);when(credentials.requireSecret(12L,"XIAOHONGSHU","STORAGE_STATE")).thenReturn("state");Path card=Files.createFile(temp.resolve("uncertain.png"));when(renderer.render(1,"标题","正文")).thenReturn(card);when(adapter.publish(anyString(),anyString(),anyString(),anyList(),any())).thenThrow(new XiaohongshuAutomationException("结果未知",true));XiaohongshuPublicationService service=new XiaohongshuPublicationService(repository,credentials,adapter,renderer,new ObjectMapper());assertThrows(XiaohongshuAutomationException.class,()->service.publish(1));verify(repository).markPublicationUnknown(1,"结果未知");verify(repository,never()).markPublicationFailed(anyLong(),anyString(),anyString());}
}
