import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatRatioString } from "./quantBacktestsFormat";
export default function QuantWalkForwardOosChart({ equity, loading, error }) {
  if (loading) return <section className="backtest-card backtest-empty">正在读取 OOS 指数…</section>;
  if (error) return <section className="backtest-card backtest-inline-error" role="alert">OOS 指数加载失败：{error}</section>;
  if (!equity) return null;
  if (!equity.totalPoints) return <section className="backtest-card backtest-empty">没有可用的样本外曲线</section>;
  return <section className="backtest-card quant-walk-forward-oos"><header className="quant-section-head"><h4>Normalized OOS Index</h4><small>初始指数=1；成功 Fold 的 VALIDATION 相对权益按时间复利衔接。该指数不是账户余额。</small></header>{equity.hasGaps && <p className="backtest-inline-error" role="alert">存在失败 Fold；OOS 指数只连接成功 Fold，不补造缺失区间。</p>}<div className="quant-oos-summary"><span>收益 {formatRatioString(equity.totalReturnRatio)}</span><span>最大回撤 {formatRatioString(equity.maximumDrawdownRatio)}</span><span>成功 Fold {equity.successfulFolds}</span><span>缺失 Fold {equity.missingFolds}</span></div><div className="backtest-chart quant-oos-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={equity.points}><CartesianGrid stroke="var(--border-subtle)" /><XAxis dataKey="openTime" tickFormatter={(value) => new Date(value).toLocaleDateString("zh-CN")} /><YAxis domain={["auto", "auto"]} /><Tooltip formatter={(value, name) => [String(value), name === "indexRatio" ? "指数" : "回撤"]} /><Area type="monotone" dataKey="indexRatio" stroke="var(--accent-primary)" fill="var(--accent-primary)" fillOpacity={0.14} /></AreaChart></ResponsiveContainer></div><div className="backtest-chart quant-oos-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={equity.points}><CartesianGrid stroke="var(--border-subtle)" /><XAxis dataKey="openTime" hide /><YAxis domain={[0, 1]} /><Tooltip formatter={(value) => [String(value), "回撤"]} /><Area type="monotone" dataKey="drawdownRatio" stroke="var(--accent-red)" fill="var(--accent-red)" fillOpacity={0.1} /></AreaChart></ResponsiveContainer></div></section>;
}
