import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowsClockwise, Flask, Warning } from "@phosphor-icons/react";
import QuantPageScaffold from "./QuantPageScaffold";
import QuantWalkForwardCreatePanel from "./QuantWalkForwardCreatePanel";
import QuantWalkForwardStudyList from "./QuantWalkForwardStudyList";
import QuantWalkForwardStudyDetail from "./QuantWalkForwardStudyDetail";
import QuantWalkForwardFolds from "./QuantWalkForwardFolds";
import QuantWalkForwardParameterFrequency from "./QuantWalkForwardParameterFrequency";
import QuantWalkForwardOosChart from "./QuantWalkForwardOosChart";
import { fetchDatasets, fetchStrategies } from "./quantBacktestsApi";
import { fetchWalkForwardFolds, fetchWalkForwardOosEquity, fetchWalkForwardStudies, fetchWalkForwardStudy } from "./quantWalkForwardApi";
import "./QuantWalkForward.css";

const NON_TERMINAL = new Set(["QUEUED", "RUNNING"]);
function readRoute() { const params = new URLSearchParams(window.location.search); const page = Number(params.get("foldPage")); return { studyId: params.get("studyId") || "", foldPage: Number.isSafeInteger(page) && page > 0 ? page : 1, foldId: params.get("foldId") || "" }; }
function writeRoute(values, replace = false) { const url = new URL(window.location.href); url.searchParams.set("mode", "walk-forward"); ["runId", "openCreate", "strategyCode", "experimentId", "candidatePage", "candidateSort", "candidateOrder"].forEach((key) => url.searchParams.delete(key)); if (values.studyId) url.searchParams.set("studyId", values.studyId); else url.searchParams.delete("studyId"); url.searchParams.set("foldPage", String(values.foldPage || 1)); if (values.foldId) url.searchParams.set("foldId", values.foldId); else url.searchParams.delete("foldId"); window.history[replace ? "replaceState" : "pushState"]({}, "", `${url.pathname}?${url.searchParams.toString()}`); window.dispatchEvent(new PopStateEvent("popstate")); }
function jump(mode, key, value) { const url = new URL(window.location.href); url.searchParams.set("mode", mode); ["studyId", "foldPage", "foldId", "experimentId", "candidatePage", "candidateSort", "candidateOrder", "runId", "openCreate", "strategyCode"].forEach((item) => url.searchParams.delete(item)); url.searchParams.set(key, value); window.history.pushState({}, "", `${url.pathname}?${url.searchParams.toString()}`); window.dispatchEvent(new PopStateEvent("popstate")); }
const validDataset = (item) => item && Number.isSafeInteger(Number(item.id)) && item.status === "CONTIGUOUS" && item.gapCount === 0 && item.gapSegmentCount === 0 && item.earliestOpenTime && item.latestOpenTime && item.lastValidatedAt && Number(item.candleCount) > 0;

export default function QuantWalkForwardWorkspace() {
  const initial = useRef(readRoute()).current;
  const [strategies, setStrategies] = useState([]); const [datasets, setDatasets] = useState([]);
  const [filters, setFilters] = useState({ status: "", symbol: "", strategyCode: "" }); const [listPage, setListPage] = useState(1); const [listData, setListData] = useState({ records: [], total: 0, page: 1, pageSize: 20 });
  const [studyId, setStudyId] = useState(initial.studyId); const [detail, setDetail] = useState(null); const [foldPage, setFoldPage] = useState(initial.foldPage); const [foldData, setFoldData] = useState({ records: [], total: 0, page: 1, pageSize: 50 }); const [selectedFold, setSelectedFold] = useState(null); const [oos, setOos] = useState(null);
  const [loading, setLoading] = useState({ shared: true, list: true, detail: false, folds: false, oos: false }); const [errors, setErrors] = useState({}); const [refreshing, setRefreshing] = useState(false); const [showCreate, setShowCreate] = useState(false); const [creating, setCreating] = useState(false); const [visible, setVisible] = useState(() => document.visibilityState === "visible");
  const aborts = useRef({}); const sequence = useRef({ shared: 0, list: 0, detail: 0, folds: 0, oos: 0 }); const selectedRef = useRef(initial.studyId); const polling = useRef(false);
  const selectedFoldId = selectedFold?.foldId || "";
  const loadShared = useCallback(async () => { aborts.current.shared?.abort(); const controller = new AbortController(); aborts.current.shared = controller; const current = ++sequence.current.shared; setLoading((value) => ({ ...value, shared: true })); setErrors((value) => ({ ...value, strategies: "", datasets: "" })); const [strategyResult, datasetResult] = await Promise.allSettled([fetchStrategies(controller.signal), fetchDatasets(controller.signal)]); if (current !== sequence.current.shared) return; if (strategyResult.status === "fulfilled") setStrategies(strategyResult.value); else if (strategyResult.reason?.name !== "AbortError") setErrors((value) => ({ ...value, strategies: strategyResult.reason.message })); if (datasetResult.status === "fulfilled") setDatasets(datasetResult.value.filter(validDataset)); else if (datasetResult.reason?.name !== "AbortError") setErrors((value) => ({ ...value, datasets: datasetResult.reason.message })); setLoading((value) => ({ ...value, shared: false })); }, []);
  const loadList = useCallback(async (page = 1, options = {}) => { aborts.current.list?.abort(); const controller = new AbortController(); aborts.current.list = controller; const current = ++sequence.current.list; if (!options.background) setLoading((value) => ({ ...value, list: true })); setErrors((value) => ({ ...value, list: "" })); try { const result = await fetchWalkForwardStudies({ ...filters, page, pageSize: 20 }, controller.signal); if (current !== sequence.current.list) return null; setListData(result); setListPage(result.page); return result; } catch (exception) { if (exception.name !== "AbortError" && current === sequence.current.list) setErrors((value) => ({ ...value, list: exception.message })); return null; } finally { if (current === sequence.current.list) setLoading((value) => ({ ...value, list: false })); } }, [filters]);
  const loadDetail = useCallback(async (id, options = {}) => { if (!id) return null; aborts.current.detail?.abort(); const controller = new AbortController(); aborts.current.detail = controller; const current = ++sequence.current.detail; if (!options.background) setLoading((value) => ({ ...value, detail: true })); setErrors((value) => ({ ...value, detail: "" })); try { const result = await fetchWalkForwardStudy(id, controller.signal); if (current !== sequence.current.detail || id !== selectedRef.current) return null; setDetail(result); return result; } catch (exception) { if (exception.name !== "AbortError" && current === sequence.current.detail && id === selectedRef.current) { setDetail(null); setErrors((value) => ({ ...value, detail: exception.message })); } return null; } finally { if (current === sequence.current.detail) setLoading((value) => ({ ...value, detail: false })); } }, []);
  const loadFolds = useCallback(async (id, page, options = {}) => { if (!id) return null; aborts.current.folds?.abort(); const controller = new AbortController(); aborts.current.folds = controller; const current = ++sequence.current.folds; if (!options.background) setLoading((value) => ({ ...value, folds: true })); setErrors((value) => ({ ...value, folds: "" })); try { const result = await fetchWalkForwardFolds(id, { page, pageSize: 50 }, controller.signal); if (current !== sequence.current.folds || id !== selectedRef.current) return null; setFoldData(result); setSelectedFold((currentFold) => { const routeFold = readRoute().foldId; return result.records.find((item) => item.foldId === (routeFold || currentFold?.foldId)) || null; }); return result; } catch (exception) { if (exception.name !== "AbortError" && current === sequence.current.folds && id === selectedRef.current) setErrors((value) => ({ ...value, folds: exception.message })); return null; } finally { if (current === sequence.current.folds) setLoading((value) => ({ ...value, folds: false })); } }, []);
  const loadOos = useCallback(async (id) => { if (!id) return null; aborts.current.oos?.abort(); const controller = new AbortController(); aborts.current.oos = controller; const current = ++sequence.current.oos; setLoading((value) => ({ ...value, oos: true })); setErrors((value) => ({ ...value, oos: "" })); try { const result = await fetchWalkForwardOosEquity(id, 1200, controller.signal); if (current !== sequence.current.oos || id !== selectedRef.current) return null; setOos(result); return result; } catch (exception) { if (exception.name !== "AbortError" && current === sequence.current.oos && id === selectedRef.current) setErrors((value) => ({ ...value, oos: exception.message })); return null; } finally { if (current === sequence.current.oos) setLoading((value) => ({ ...value, oos: false })); } }, []);
  useEffect(() => { loadShared(); return () => Object.values(aborts.current).forEach((controller) => controller?.abort()); }, [loadShared]);
  useEffect(() => { const timer = window.setTimeout(() => loadList(1), 250); return () => window.clearTimeout(timer); }, [filters, loadList]);
  useEffect(() => { selectedRef.current = studyId; if (!studyId) { setDetail(null); setFoldData({ records: [], total: 0, page: 1, pageSize: 50 }); setSelectedFold(null); setOos(null); return; } setSelectedFold(null); loadDetail(studyId); }, [studyId, loadDetail]);
  useEffect(() => { if (studyId) loadFolds(studyId, foldPage); }, [foldPage, studyId, loadFolds]);
  useEffect(() => { if (!studyId || !detail?.summary || !["COMPLETED", "COMPLETED_WITH_FAILURES", "FAILED"].includes(detail.summary.status)) return; loadOos(studyId); }, [detail?.summary?.status, loadOos, studyId]);
  useEffect(() => { const onPop = () => { const route = readRoute(); selectedRef.current = route.studyId; setStudyId(route.studyId); setFoldPage(route.foldPage); }; window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, []);
  useEffect(() => { polling.current = false; if (!studyId || !detail?.summary || !NON_TERMINAL.has(detail.summary.status) || !visible) return undefined; let active = true; const poll = async () => { if (!active || polling.current || !visible) return; polling.current = true; const result = await loadDetail(studyId, { background: true }); if (!result || !active || studyId !== selectedRef.current) { polling.current = false; return; } await Promise.all([loadFolds(studyId, foldPage, { background: true }), loadList(listPage, { background: true })]); if (!NON_TERMINAL.has(result.summary.status)) await loadOos(studyId); polling.current = false; }; poll(); const timer = window.setInterval(poll, 3000); return () => { active = false; window.clearInterval(timer); }; }, [detail?.summary?.status, foldPage, listPage, loadDetail, loadFolds, loadList, loadOos, studyId, visible]);
  useEffect(() => { const onVisibility = () => { const next = document.visibilityState === "visible"; setVisible(next); if (!next) Object.values(aborts.current).forEach((controller) => controller?.abort()); }; document.addEventListener("visibilitychange", onVisibility); return () => document.removeEventListener("visibilitychange", onVisibility); }, []);
  const selectStudy = (id) => { selectedRef.current = id; setStudyId(id); setFoldPage(1); setSelectedFold(null); setOos(null); writeRoute({ studyId: id, foldPage: 1 }); };
  const selectFold = (fold) => { setSelectedFold(fold); writeRoute({ studyId, foldPage, foldId: fold.foldId }); };
  const refresh = async () => { setRefreshing(true); await Promise.all([loadShared(), loadList(listPage), studyId ? loadDetail(studyId) : null, studyId ? loadFolds(studyId, foldPage) : null]); setRefreshing(false); };
  const onCreated = async (created) => { selectedRef.current = created.studyId; setStudyId(created.studyId); setFoldPage(1); writeRoute({ studyId: created.studyId, foldPage: 1 }); await Promise.all([loadList(1), loadDetail(created.studyId), loadFolds(created.studyId, 1)]); };
  const closeCreate = () => { if (creating) return; setShowCreate(false); };
  const detailData = detail?.summary;
  return <QuantPageScaffold pageClass="quant-backtests-page quant-walk-forward-page"><div className="quant-workspace-head"><div><span className="eyebrow">QUANT · WALK-FORWARD LAB</span><h3>滚动验证</h3><small>按 TRAIN 指标选择参数，再观察连续样本外 VALIDATION 表现</small></div><div className="backtest-head-actions"><button type="button" className="quant-refresh" onClick={refresh} disabled={refreshing}><ArrowsClockwise className={refreshing ? "spin" : ""} />刷新</button><button type="button" className="quant-primary-action quant-walk-forward-open" onClick={() => setShowCreate(true)}><Flask />新建滚动验证</button></div></div>{errors.strategies && <div className="backtest-notice" role="alert"><Warning />策略不可用：{errors.strategies}</div>}{errors.datasets && <div className="backtest-notice" role="alert"><Warning />数据集不可用：{errors.datasets}</div>}{errors.list && <div className="backtest-notice" role="alert">Study 列表加载失败：{errors.list}</div>}<div className="quant-walk-forward-main"><QuantWalkForwardStudyList page={listPage} data={listData} filters={filters} loading={loading.list} selectedId={studyId} onFilters={(next) => { setFilters(next); setListPage(1); }} onPage={(page) => loadList(page)} onSelect={selectStudy} /><QuantWalkForwardStudyDetail detail={detail} loading={loading.detail} error={errors.detail} onRetry={() => loadDetail(studyId)} /></div>{detailData && <><QuantWalkForwardFolds data={foldData} page={foldPage} selectedFold={selectedFold} loading={loading.folds} error={errors.folds} onPage={(page) => { setFoldPage(page); writeRoute({ studyId, foldPage: page, foldId: selectedFoldId }); }} onSelect={selectFold} onOpenExperiment={(id) => jump("experiment", "experimentId", id)} onOpenRun={(id) => jump("single", "runId", id)} /><div className="quant-walk-forward-bottom"><QuantWalkForwardParameterFrequency frequencies={detail.parameterFrequencies} selectedParameterChanges={detailData.selectedParameterChanges} /><QuantWalkForwardOosChart equity={oos} loading={loading.oos} error={errors.oos} /></div></>}{showCreate && <div className="backtest-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) closeCreate(); }}><QuantWalkForwardCreatePanel strategies={strategies} datasets={datasets} onClose={closeCreate} onCreated={onCreated} onSavingChange={setCreating} /></div>}</QuantPageScaffold>;
}
