package com.aiprovider.service.quant;

import com.aiprovider.quant.market.history.service.MarketDataSnapshotException;

import com.aiprovider.controller.quant.dto.*; import com.aiprovider.mapper.*; import com.aiprovider.mapper.row.*; import com.aiprovider.quant.backtest.*; import com.aiprovider.quant.market.history.model.MarketDataSnapshot; import com.aiprovider.quant.market.history.port.MarketDatasetRepository; import com.aiprovider.quant.market.history.service.MarketDataSnapshotService; import com.aiprovider.quant.strategy.*; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.time.*; import java.util.*; import java.util.concurrent.*;

@Service public class BacktestRunService {
 private final BacktestRunMapper runs;private final BacktestTradeMapper trades;private final BacktestEquityMapper equity;private final MarketDatasetRepository datasets;private final MarketDataSnapshotService snapshots;private final BacktestEngine engine;private final StrategyRegistry strategies;private final BacktestPersistenceService persistence;private final BacktestFailureService failures;private final ThreadPoolExecutor executor;private final ObjectMapper json;
 public BacktestRunService(BacktestRunMapper r,BacktestTradeMapper t,BacktestEquityMapper e,MarketDatasetRepository d,MarketDataSnapshotService s,BacktestEngine b,StrategyRegistry g,BacktestPersistenceService p,BacktestFailureService f,@Qualifier("quantBacktestExecutor") ThreadPoolExecutor x,ObjectMapper j){runs=r;trades=t;equity=e;datasets=d;snapshots=s;engine=b;strategies=g;persistence=p;failures=f;executor=x;json=j;}
 public String create(BacktestCreateRequest q){validate(q);var dataset=datasets.findById(q.getDatasetId());if(dataset==null)throw error("BACKTEST_DATASET_NOT_FOUND","datasetId="+q.getDatasetId()+" not found");QuantStrategyDefinition def=definition(q.getStrategyCode());if(!def.version().equals(q.getStrategyVersion()))throw error("BACKTEST_STRATEGY_VERSION_NOT_SUPPORTED","strategyCode="+q.getStrategyCode()+" version="+q.getStrategyVersion());try{def.minimumRequiredBars(q.getStrategyParameters());}catch(StrategyException e){throw error(e.getErrorCode(),e.getMessage());}BacktestRunRow row=new BacktestRunRow();row.runId=UUID.randomUUID().toString();row.datasetId=q.getDatasetId();row.provider=dataset.getProvider().name();row.marketType=dataset.getMarketType().name();row.dataType=dataset.getDataType().name();row.symbol=dataset.getSymbol();row.intervalCode=dataset.getInterval().code();row.startOpenTimeMs=q.getStartOpenTimeInclusive().toEpochMilli();row.endOpenTimeExclusiveMs=q.getEndOpenTimeExclusive().toEpochMilli();row.strategyCode=q.getStrategyCode().trim();row.strategyVersion=q.getStrategyVersion().trim();row.requestedParametersJson=write(q.getStrategyParameters()==null?Map.of():q.getStrategyParameters());row.orderAmount=q.getOrderAmount();row.feeRate=q.getFeeRate();row.forceCloseAtEnd=q.isForceCloseAtEnd();row.queuedAt=Instant.now();row.updatedAt=row.queuedAt;runs.insert(row);try{executor.execute(()->run(row.runId,q));}catch(RejectedExecutionException ex){failures.markFailed(row.runId,"BACKTEST_QUEUE_FULL","runId="+row.runId+" queue is full");throw error("BACKTEST_QUEUE_FULL","runId="+row.runId+" queue is full");}return row.runId;}
 private void run(String id,BacktestCreateRequest q){try{cas(id,BacktestRunStatus.QUEUED,BacktestRunStatus.LOADING_SNAPSHOT,BigDecimal.TEN);MarketDataSnapshot s=snapshots.load(q.getDatasetId(),q.getStartOpenTimeInclusive(),q.getEndOpenTimeExclusive());BacktestRunRow meta=new BacktestRunRow();meta.runId=id;meta.datasetLastValidatedAt=s.getDatasetLastValidatedAt();meta.datasetLastSyncTaskId=s.getDatasetLastSyncTaskId();meta.provider=s.getProvider().name();meta.marketType=s.getMarketType().name();meta.dataType=s.getDataType().name();meta.symbol=s.getSymbol();meta.intervalCode=s.getInterval().code();meta.barCount=(int)s.getActualCandleCount();meta.updatedAt=Instant.now();if(runs.updateSnapshot(meta)!=1)throw error("BACKTEST_STATE_CONFLICT","runId="+id+" snapshot update failed");cas(id,BacktestRunStatus.LOADING_SNAPSHOT,BacktestRunStatus.RUNNING_ENGINE,new BigDecimal("30"));BacktestResult result=engine.run(new BacktestRequest(q.getStrategyCode().trim(),q.getStrategyVersion().trim(),q.getStrategyParameters(),q.getOrderAmount(),q.getFeeRate(),q.isForceCloseAtEnd()),s.getSymbol(),s.getInterval(),s.getCandles());validateResult(id,s,result);cas(id,BacktestRunStatus.RUNNING_ENGINE,BacktestRunStatus.PERSISTING,new BigDecimal("80"));persistence.persistCompleted(id,result);}catch(Exception ex){String code=ex instanceof BacktestTaskException?((BacktestTaskException)ex).getErrorCode():"BACKTEST_EXECUTION_FAILED";failures.markFailed(id,code,safe(ex.getMessage()));}}
 private void cas(String id,BacktestRunStatus from,BacktestRunStatus to,BigDecimal progress){if(runs.transition(id,from.name(),to.name(),progress,Instant.now())!=1)throw error("BACKTEST_STATE_CONFLICT","runId="+id+" transition "+from+" -> "+to+" failed");}
 private void validateResult(String id,MarketDataSnapshot s,BacktestResult r){if(r.getBarCount()!=s.getActualCandleCount()||!s.getSymbol().equals(r.getSymbol())||s.getInterval()!=r.getInterval()||r.getTrades().size()!=r.getMetrics().getTradeCount()||r.getEquityCurve().size()!=r.getBarCount()||r.getMetrics().getMaximumDrawdownRatio().signum()<0||r.getMetrics().getWinningTradeCount()+r.getMetrics().getLosingTradeCount()+r.getMetrics().getBreakEvenTradeCount()!=r.getMetrics().getTradeCount()||r.getEquityCurve().isEmpty()||r.getEquityCurve().get(r.getEquityCurve().size()-1).equityRatio().subtract(BigDecimal.ONE).compareTo(r.getMetrics().getTotalReturnRatio())!=0)throw error("BACKTEST_RESULT_INVALID","runId="+id+" result consistency check failed");for(int i=0;i<r.getTrades().size();i++)if(r.getTrades().get(i).getTradeNo()!=i+1)throw error("BACKTEST_RESULT_INVALID","runId="+id+" tradeNo is not continuous");}
 public List<BacktestDtos.Strategy> strategies(){return strategies.list().stream().map(d->new BacktestDtos.Strategy(d.code(),d.name(),d.version(),d.description(),d.minimumRequiredBars(Map.of()),d.parameters().stream().map(p->new BacktestDtos.Parameter(p.name(),p.defaultValue(),p.minValue(),p.maxValue())).toList())).toList();}
 public BacktestDtos.Page<BacktestDtos.RunDetail> page(int page,int size,String status,String symbol,String code){if(page<1||size<1||size>100)throw error("BACKTEST_REQUEST_INVALID","page/pageSize invalid");String s=status==null||status.isBlank()?null:status.trim().toUpperCase(Locale.ROOT);if(s!=null)try{BacktestRunStatus.valueOf(s);}catch(IllegalArgumentException e){throw error("BACKTEST_REQUEST_INVALID","status invalid: "+status);}String sym=symbol==null||symbol.isBlank()?null:symbol.trim().toUpperCase(Locale.ROOT);String strategy=code==null||code.isBlank()?null:code.trim();return new BacktestDtos.Page<>(runs.findPage(s,sym,strategy,size,(page-1)*size).stream().map(this::detail).toList(),runs.count(s,sym,strategy),page,size);}
 public List<BacktestDtos.RunDetail> nonTerminal(){return runs.findNonTerminal().stream().map(this::detail).toList();}
 public BacktestDtos.RunDetail get(String id){return detail(require(id));}
 public BacktestDtos.Page<BacktestDtos.Trade> trades(String id,int page,int size){BacktestRunRow run=require(id);if(page<1||size<1||size>500)throw error("BACKTEST_REQUEST_INVALID","page/pageSize invalid");if(!BacktestRunStatus.COMPLETED.name().equals(run.status))return new BacktestDtos.Page<>(List.of(),0,page,size);return new BacktestDtos.Page<>(trades.findPage(id,size,(page-1)*size).stream().map(this::trade).toList(),trades.count(id),page,size);}
 public BacktestDtos.Equity equity(String id,int max){require(id);if(max<100||max>5000)throw error("BACKTEST_REQUEST_INVALID","maxPoints must be 100..5000");int total=equity.count(id);if(total==0)return new BacktestDtos.Equity(false,0,List.of());List<BacktestEquityRow> rows=total<=max?equity.findAll(id):equity.findAtIndices(id,BacktestEquitySampler.indices(total,max));return new BacktestDtos.Equity(total>max,total,rows.stream().map(this::point).toList());}
 private BacktestRunRow require(String id){BacktestRunRow r=runs.findByRunId(id);if(r==null)throw error("BACKTEST_RUN_NOT_FOUND","runId="+id+" not found");return r;}
 private QuantStrategyDefinition definition(String code){try{return strategies.get(code==null?null:code.trim());}catch(StrategyException e){throw error(e.getErrorCode(),e.getMessage());}}
 private void validate(BacktestCreateRequest q){if(q==null||q.getDatasetId()<=0||q.getStartOpenTimeInclusive()==null||q.getEndOpenTimeExclusive()==null||!q.getStartOpenTimeInclusive().isBefore(q.getEndOpenTimeExclusive())||q.getStrategyCode()==null||q.getStrategyCode().isBlank()||q.getStrategyVersion()==null||q.getStrategyVersion().isBlank()||q.getOrderAmount()==null||q.getOrderAmount().signum()<=0||q.getFeeRate()==null||q.getFeeRate().signum()<0||q.getFeeRate().compareTo(new BigDecimal("0.01"))>0||!q.isForceCloseAtEnd()||q.getStrategyParameters()!=null&&q.getStrategyParameters().entrySet().stream().anyMatch(e->e.getKey()==null||e.getValue()==null))throw error("BACKTEST_REQUEST_INVALID","invalid backtest request");}
 private BacktestTaskException error(String code,String message){return new BacktestTaskException(code,message);}
 private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw error("BACKTEST_REQUEST_INVALID","parameters cannot be serialized");}}
 private String safe(String m){if(m==null||m.isBlank())return "backtest execution failed";String s=m.replaceAll("[\\r\\n]"," ");return s.substring(0,Math.min(1000,s.length()));}
 private BacktestDtos.RunDetail detail(BacktestRunRow r){Map<String,Integer> req=read(r.requestedParametersJson),res=r.resolvedParametersJson==null?Map.of():read(r.resolvedParametersJson);Map<String,Object> metrics=new LinkedHashMap<>();metrics.put("winRate",r.winRate);metrics.put("grossProfit",r.grossProfit);metrics.put("grossLoss",r.grossLoss);metrics.put("netProfit",r.netProfit);metrics.put("totalReturnRatio",r.totalReturnRatio);metrics.put("maximumDrawdownRatio",r.maximumDrawdownRatio);metrics.put("profitFactor",r.profitFactor);metrics.put("averageTradeReturnRatio",r.averageTradeReturnRatio);metrics.put("buyAndHoldReturnRatio",r.buyAndHoldReturnRatio);metrics.put("totalFees",r.totalFees);return new BacktestDtos.RunDetail(r.runId,r.datasetId,r.datasetLastValidatedAt,r.datasetLastSyncTaskId,r.provider,r.marketType,r.dataType,r.symbol,r.intervalCode,Instant.ofEpochMilli(r.startOpenTimeMs),Instant.ofEpochMilli(r.endOpenTimeExclusiveMs),r.strategyCode,r.strategyVersion,req,res,r.orderAmount,r.feeRate,r.forceCloseAtEnd,r.status,r.progressPercent,r.errorCode,r.errorMessage,r.queuedAt,r.startedAt,r.finishedAt,r.barCount,r.tradeCount,r.winningTradeCount,r.losingTradeCount,r.breakEvenTradeCount,metrics,r.equityPointCount==null?0:r.equityPointCount);}
 private BacktestDtos.Trade trade(BacktestTradeRow r){return new BacktestDtos.Trade(r.tradeNo,r.entrySignalIndex,r.entryIndex,Instant.ofEpochMilli(r.entryTimeMs),r.entryPrice,r.exitSignalIndex,r.exitIndex,Instant.ofEpochMilli(r.exitTimeMs),r.exitPrice,r.amount,r.grossProfit,r.fee,r.netProfit,r.returnRatio,r.barsHeld,r.forcedExit,r.exitReason);}
 private BacktestDtos.EquityPoint point(BacktestEquityRow r){return new BacktestDtos.EquityPoint(r.pointIndex,Instant.ofEpochMilli(r.openTimeMs),r.equityRatio,r.drawdownRatio,r.inPosition);}
 private Map<String,Integer> read(String s){try{return json.readValue(s,new TypeReference<Map<String,Integer>>(){});}catch(Exception e){throw error("BACKTEST_PERSISTENCE_FAILED","stored JSON is invalid");}}
}
