package com.aiprovider.service.quant;

import com.aiprovider.controller.quant.dto.*; import com.aiprovider.mapper.*; import com.aiprovider.quant.backtest.*; import com.aiprovider.quant.market.history.model.MarketDataSnapshot; import com.aiprovider.quant.market.history.port.MarketDatasetRepository; import com.aiprovider.quant.market.history.service.MarketDataSnapshotService; import com.aiprovider.quant.strategy.*; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.time.*; import java.util.*; import java.util.concurrent.RejectedExecutionException;

@Service
public class BacktestRunService {
 private final BacktestRunMapper runs; private final BacktestTradeMapper trades; private final BacktestEquityMapper equity; private final MarketDatasetRepository datasets; private final MarketDataSnapshotService snapshots; private final BacktestEngine engine; private final StrategyRegistry strategies; private final BacktestPersistenceService persistence; private final ThreadPoolTaskExecutor executor; private final ObjectMapper json;
 public BacktestRunService(BacktestRunMapper r,BacktestTradeMapper t,BacktestEquityMapper e,MarketDatasetRepository d,MarketDataSnapshotService s,BacktestEngine b,StrategyRegistry g,BacktestPersistenceService p,@Qualifier("quantBacktestExecutor") ThreadPoolTaskExecutor x,ObjectMapper j){runs=r;trades=t;equity=e;datasets=d;snapshots=s;engine=b;strategies=g;persistence=p;executor=x;json=j;}
 public String create(BacktestCreateRequest q){validate(q);var dataset=datasets.findById(q.getDatasetId());if(dataset==null)throw new BacktestTaskException("BACKTEST_DATASET_NOT_FOUND","datasetId="+q.getDatasetId()+" not found");QuantStrategyDefinition def=getStrategy(q.getStrategyCode());if(!def.version().equals(q.getStrategyVersion()))throw new BacktestTaskException("BACKTEST_STRATEGY_VERSION_NOT_SUPPORTED","strategyCode="+q.getStrategyCode()+" version="+q.getStrategyVersion());def.minimumRequiredBars(q.getStrategyParameters());String id=UUID.randomUUID().toString();Map<String,Object> row=new HashMap<>();row.put("runId",id);row.put("datasetId",q.getDatasetId());row.put("provider",dataset.getProvider().name());row.put("marketType",dataset.getMarketType().name());row.put("dataType",dataset.getDataType().name());row.put("symbol",dataset.getSymbol());row.put("intervalCode",dataset.getInterval().code());row.put("startMs",q.getStartOpenTimeInclusive().toEpochMilli());row.put("endMs",q.getEndOpenTimeExclusive().toEpochMilli());row.put("strategyCode",q.getStrategyCode());row.put("strategyVersion",q.getStrategyVersion());row.put("requestedJson",write(q.getStrategyParameters()==null?Map.of():q.getStrategyParameters()));row.put("orderAmount",q.getOrderAmount());row.put("feeRate",q.getFeeRate());row.put("forceCloseAtEnd",q.isForceCloseAtEnd());row.put("now",Instant.now());runs.insert(row);try{executor.execute(()->run(id,q));}catch(RejectedExecutionException ex){runs.fail(id,"BACKTEST_QUEUE_FULL","runId="+id+" queue is full",Instant.now());throw new BacktestTaskException("BACKTEST_QUEUE_FULL","runId="+id+" queue is full");}return id;}
 private void run(String id,BacktestCreateRequest q){try{if(runs.transition(id,"QUEUED","LOADING_SNAPSHOT",BigDecimal.TEN,Instant.now())!=1)return;MarketDataSnapshot s=snapshots.load(q.getDatasetId(),q.getStartOpenTimeInclusive(),q.getEndOpenTimeExclusive());Map<String,Object> meta=new HashMap<>();meta.put("runId",id);meta.put("validatedAt",s.getDatasetLastValidatedAt());meta.put("syncTaskId",s.getDatasetLastSyncTaskId());meta.put("provider",s.getProvider().name());meta.put("marketType",s.getMarketType().name());meta.put("dataType",s.getDataType().name());meta.put("symbol",s.getSymbol());meta.put("intervalCode",s.getInterval().code());meta.put("barCount",s.getActualCandleCount());meta.put("now",Instant.now());runs.updateSnapshot(meta);if(runs.transition(id,"LOADING_SNAPSHOT","RUNNING_ENGINE",new BigDecimal("30"),Instant.now())!=1)throw new BacktestTaskException("BACKTEST_EXECUTION_FAILED","runId="+id+" state transition failed");BacktestResult result=engine.run(new BacktestRequest(q.getStrategyCode(),q.getStrategyVersion(),q.getStrategyParameters(),q.getOrderAmount(),q.getFeeRate(),q.isForceCloseAtEnd()),s.getSymbol(),s.getInterval(),s.getCandles());validateResult(id,s,result);if(runs.transition(id,"RUNNING_ENGINE","PERSISTING",new BigDecimal("80"),Instant.now())!=1)throw new BacktestTaskException("BACKTEST_PERSISTENCE_FAILED","runId="+id+" state transition failed");persistence.persistCompleted(id,result);}catch(Exception ex){String code=ex instanceof BacktestTaskException?((BacktestTaskException)ex).getErrorCode():"BACKTEST_EXECUTION_FAILED";runs.fail(id,code,safeMessage(id,q,ex),Instant.now());}}
 private void validateResult(String id,MarketDataSnapshot s,BacktestResult r){if(r.getBarCount()!=s.getActualCandleCount()||!s.getSymbol().equals(r.getSymbol())||s.getInterval()!=r.getInterval()||r.getTrades().size()!=r.getMetrics().getTradeCount()||r.getEquityCurve().size()!=r.getBarCount()||r.getMetrics().getMaximumDrawdownRatio().signum()<0||r.getEquityCurve().get(r.getEquityCurve().size()-1).equityRatio().subtract(BigDecimal.ONE).compareTo(r.getMetrics().getTotalReturnRatio())!=0)throw new BacktestTaskException("BACKTEST_RESULT_INVALID","runId="+id+" result consistency check failed");}
 public List<BacktestDtos.Strategy> strategies(){List<BacktestDtos.Strategy> out=new ArrayList<>();for(var d:strategies.list()){var ps=d.parameters().stream().map(p->new BacktestDtos.Parameter(p.name(),p.defaultValue(),p.minValue(),p.maxValue())).toList();out.add(new BacktestDtos.Strategy(d.code(),d.name(),d.version(),d.description(),d.minimumRequiredBars(Map.of()),ps));}return out;}
 public BacktestDtos.Page<BacktestDtos.RunDetail> page(int page,int size,String status,String symbol,String code){if(page<1||size<1||size>100)throw new IllegalArgumentException("page/pageSize invalid");return new BacktestDtos.Page<>(runs.findPage(status,symbol,code,size,(page-1)*size).stream().map(this::detail).toList(),runs.count(status,symbol,code),page,size);}
 public List<BacktestDtos.RunDetail> nonTerminal(){return runs.findNonTerminal().stream().map(this::detail).toList();}
 public BacktestDtos.RunDetail get(String id){Map<String,Object> r=runs.findByRunId(id);if(r==null)throw new BacktestTaskException("BACKTEST_RUN_NOT_FOUND","runId="+id+" not found");return detail(r);}
 public BacktestDtos.Page<BacktestDtos.Trade> trades(String id,int page,int size){require(id);if(page<1||size<1||size>500)throw new IllegalArgumentException("page/pageSize invalid");return new BacktestDtos.Page<>(trades.findPage(id,size,(page-1)*size).stream().map(this::trade).toList(),trades.count(id),page,size);}
 public BacktestDtos.Equity equity(String id,int max){require(id);if(max<100||max>5000)throw new IllegalArgumentException("maxPoints must be 100..5000");int total=equity.count(id);if(total==0)return new BacktestDtos.Equity(false,0,List.of());int stride=Math.max(1,(int)Math.ceil((double)total/max));List<Map<String,Object>> rows=equity.findSampled(id,stride);int last=Optional.ofNullable(equity.maxIndex(id)).orElse(0);if(rows.stream().noneMatch(x->num(x.get("PointIndex"))==last))rows.add(equity.findAt(id,last));rows.sort(Comparator.comparingInt(x->num(x.get("PointIndex"))));if(rows.size()>max){rows=rows.subList(0,max-1);rows.add(equity.findAt(id,last));}return new BacktestDtos.Equity(total>max,total,rows.stream().map(this::point).toList());}
 private void require(String id){if(runs.findByRunId(id)==null)throw new BacktestTaskException("BACKTEST_RUN_NOT_FOUND","runId="+id+" not found");}
 private QuantStrategyDefinition getStrategy(String code){try{return strategies.get(code);}catch(StrategyException e){throw new BacktestTaskException(e.getErrorCode(),e.getMessage(),e);}}
 private void validate(BacktestCreateRequest q){if(q==null||q.getDatasetId()<=0||q.getStartOpenTimeInclusive()==null||q.getEndOpenTimeExclusive()==null||!q.getStartOpenTimeInclusive().isBefore(q.getEndOpenTimeExclusive())||q.getStrategyCode()==null||q.getStrategyVersion()==null||q.getOrderAmount()==null||q.getOrderAmount().signum()<=0||q.getFeeRate()==null||q.getFeeRate().signum()<0)throw new BacktestTaskException("BACKTEST_REQUEST_INVALID","invalid backtest request");}
 private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new BacktestTaskException("BACKTEST_REQUEST_INVALID","parameters cannot be serialized",e);}}
 private String safeMessage(String id,BacktestCreateRequest q,Exception e){String m=e.getMessage();return (m==null?e.getClass().getSimpleName():m).replaceAll("[\\r\\n]"," ").substring(0,Math.min(1000,(m==null?e.getClass().getSimpleName():m).length()));}
 private int num(Object v){return ((Number)v).intValue();} private Instant instant(Object v){if(v instanceof Instant)return (Instant)v;if(v instanceof Number)return Instant.ofEpochMilli(((Number)v).longValue());if(v instanceof java.sql.Timestamp)return ((java.sql.Timestamp)v).toInstant();return ((java.time.LocalDateTime)v).toInstant(ZoneOffset.UTC);}
 private BacktestDtos.EquityPoint point(Map<String,Object> r){return new BacktestDtos.EquityPoint(num(r.get("PointIndex")),instant(r.get("OpenTimeMs")),(BigDecimal)r.get("EquityRatio"),(BigDecimal)r.get("DrawdownRatio"),bool(r.get("InPosition")));}
 private BacktestDtos.Trade trade(Map<String,Object> r){return new BacktestDtos.Trade(num(r.get("TradeNo")),num(r.get("EntrySignalIndex")),num(r.get("EntryIndex")),instant(r.get("EntryTimeMs")),(BigDecimal)r.get("EntryPrice"),r.get("ExitSignalIndex")==null?null:num(r.get("ExitSignalIndex")),num(r.get("ExitIndex")),instant(r.get("ExitTimeMs")),(BigDecimal)r.get("ExitPrice"),(BigDecimal)r.get("Amount"),(BigDecimal)r.get("GrossProfit"),(BigDecimal)r.get("Fee"),(BigDecimal)r.get("NetProfit"),(BigDecimal)r.get("ReturnRatio"),num(r.get("BarsHeld")),bool(r.get("ForcedExit")),(String)r.get("ExitReason"));}
 private BacktestDtos.RunDetail detail(Map<String,Object> r){Map<String,Integer> req=read((String)r.get("RequestedParametersJson"));Map<String,Integer> res=r.get("ResolvedParametersJson")==null?Map.of():read((String)r.get("ResolvedParametersJson"));Map<String,Object> metrics=new LinkedHashMap<>();String[] names={"WinRate","GrossProfit","GrossLoss","NetProfit","TotalReturnRatio","MaximumDrawdownRatio","ProfitFactor","AverageTradeReturnRatio","BuyAndHoldReturnRatio","TotalFees"};for(String n:names)metrics.put(n,r.get(n));return new BacktestDtos.RunDetail((String)r.get("RunId"),numLong(r.get("DatasetId")),instantNullable(r.get("DatasetLastValidatedAt")),(String)r.get("DatasetLastSyncTaskId"),(String)r.get("Provider"),(String)r.get("MarketType"),(String)r.get("DataType"),(String)r.get("Symbol"),(String)r.get("IntervalCode"),Instant.ofEpochMilli(numLong(r.get("StartOpenTimeMs"))),Instant.ofEpochMilli(numLong(r.get("EndOpenTimeExclusiveMs"))),(String)r.get("StrategyCode"),(String)r.get("StrategyVersion"),req,res,(BigDecimal)r.get("OrderAmount"),(BigDecimal)r.get("FeeRate"),bool(r.get("ForceCloseAtEnd")),(String)r.get("Status"),(BigDecimal)r.get("ProgressPercent"),(String)r.get("ErrorCode"),(String)r.get("ErrorMessage"),instantNullable(r.get("QueuedAt")),instantNullable(r.get("StartedAt")),instantNullable(r.get("FinishedAt")),intNullable(r.get("BarCount")),intNullable(r.get("TradeCount")),intNullable(r.get("WinningTradeCount")),intNullable(r.get("LosingTradeCount")),intNullable(r.get("BreakEvenTradeCount")),metrics,intNullable(r.get("EquityPointCount"))==null?0:intNullable(r.get("EquityPointCount")));}
 private Map<String,Integer> read(String s){try{return json.readValue(s,new TypeReference<Map<String,Integer>>(){});}catch(Exception e){throw new BacktestTaskException("BACKTEST_PERSISTENCE_FAILED","stored parameters are invalid",e);}}
 private long numLong(Object v){return ((Number)v).longValue();} private Integer intNullable(Object v){return v==null?null:((Number)v).intValue();} private Instant instantNullable(Object v){return v==null?null:instant(v);}
 private boolean bool(Object v){return Boolean.TRUE.equals(v)||(v instanceof Number&&((Number)v).intValue()==1);}
}
