package com.aiprovider.service.quant;

import com.aiprovider.config.quant.QuantBacktestProperties;
import com.aiprovider.mapper.*;
import com.aiprovider.mapper.row.*;
import com.aiprovider.quant.backtest.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service public class BacktestPersistenceService {
    private final BacktestRunMapper runs; private final BacktestTradeMapper trades; private final BacktestEquityMapper equity; private final ObjectMapper json; private final QuantBacktestProperties properties;
    public BacktestPersistenceService(BacktestRunMapper r,BacktestTradeMapper t,BacktestEquityMapper e,ObjectMapper j,QuantBacktestProperties p){runs=r;trades=t;equity=e;json=j;properties=p;}
    @Transactional public void persistCompleted(String runId,BacktestResult result){try{
        trades.deleteByRunId(runId); equity.deleteByRunId(runId); BacktestMetrics m=result.getMetrics(); BacktestRunRow row=new BacktestRunRow(); row.runId=runId; row.resolvedParametersJson=json.writeValueAsString(result.getStrategyParameters()); row.barCount=result.getBarCount(); row.tradeCount=m.getTradeCount(); row.winningTradeCount=m.getWinningTradeCount(); row.losingTradeCount=m.getLosingTradeCount(); row.breakEvenTradeCount=m.getBreakEvenTradeCount(); row.winRate=BacktestDecimalStoragePolicy.normalizeNullable(m.getWinRate(),"winRate"); row.grossProfit=BacktestDecimalStoragePolicy.normalizeRequired(m.getGrossProfit(),"grossProfit"); row.grossLoss=BacktestDecimalStoragePolicy.normalizeRequired(m.getGrossLoss(),"grossLoss"); row.netProfit=BacktestDecimalStoragePolicy.normalizeRequired(m.getNetProfit(),"netProfit"); row.totalReturnRatio=BacktestDecimalStoragePolicy.normalizeRequired(m.getTotalReturnRatio(),"totalReturnRatio"); row.maximumDrawdownRatio=BacktestDecimalStoragePolicy.normalizeRequired(m.getMaximumDrawdownRatio(),"maximumDrawdownRatio"); row.profitFactor=BacktestDecimalStoragePolicy.normalizeNullable(m.getProfitFactor(),"profitFactor"); row.averageTradeReturnRatio=BacktestDecimalStoragePolicy.normalizeNullable(m.getAverageTradeReturnRatio(),"averageTradeReturnRatio"); row.buyAndHoldReturnRatio=BacktestDecimalStoragePolicy.normalizeRequired(m.getBuyAndHoldReturnRatio(),"buyAndHoldReturnRatio"); row.totalFees=BacktestDecimalStoragePolicy.normalizeRequired(m.getTotalFees(),"totalFees"); row.finalEquity=BacktestDecimalStoragePolicy.normalizeRequired(m.getFinalEquity(),"finalEquity"); row.totalPnl=BacktestDecimalStoragePolicy.normalizeRequired(m.getTotalPnl(),"totalPnl"); row.averageExposureRatio=BacktestDecimalStoragePolicy.normalizeRequired(m.getAverageExposureRatio(),"averageExposureRatio"); row.maximumExposureRatio=BacktestDecimalStoragePolicy.normalizeRequired(m.getMaximumExposureRatio(),"maximumExposureRatio"); row.executionModel=result.getExecutionModel(); row.warningsJson=json.writeValueAsString(result.getWarnings()); row.equityPointCount=result.getEquityCurve().size(); row.finishedAt=Instant.now(); row.updatedAt=row.finishedAt;
        List<BacktestTradeRow> tr=tradeRows(runId,result.getTrades()); for(int i=0;i<tr.size();i+=properties.getTradeInsertBatchSize()){List<BacktestTradeRow> batch=tr.subList(i,Math.min(i+properties.getTradeInsertBatchSize(),tr.size()));if(trades.insertBatch(batch)!=batch.size())throw new BacktestTaskException("BACKTEST_PERSISTENCE_FAILED","trade batch affected an unexpected number of rows");}
        List<BacktestEquityRow> eq=equityRows(runId,result.getEquityCurve()); for(int i=0;i<eq.size();i+=properties.getEquityInsertBatchSize()){List<BacktestEquityRow> batch=eq.subList(i,Math.min(i+properties.getEquityInsertBatchSize(),eq.size()));if(equity.insertBatch(batch)!=batch.size())throw new BacktestTaskException("BACKTEST_PERSISTENCE_FAILED","equity batch affected an unexpected number of rows");}
        if(runs.complete(row)!=1) throw new BacktestTaskException("BACKTEST_STATE_CONFLICT","runId="+runId+" PERSISTING CAS failed");
    }catch(BacktestTaskException e){throw e;}catch(Exception e){throw new BacktestTaskException("BACKTEST_PERSISTENCE_FAILED","runId="+runId+" result persistence failed",e);}}
    private List<BacktestTradeRow> tradeRows(String id,List<BacktestTrade> source){List<BacktestTradeRow> out=new ArrayList<>();for(BacktestTrade t:source){BacktestTradeRow r=new BacktestTradeRow();r.runId=id;r.tradeNo=t.getTradeNo();r.entrySignalIndex=t.getEntrySignalIndex();r.entryIndex=t.getEntryIndex();r.entryTimeMs=t.getEntryTime().toEpochMilli();r.entryPrice=BacktestDecimalStoragePolicy.normalizeRequired(t.getEntryPrice(),"entryPrice");r.exitSignalIndex=t.getExitSignalIndex();r.exitIndex=t.getExitIndex();r.exitTimeMs=t.getExitTime().toEpochMilli();r.exitPrice=BacktestDecimalStoragePolicy.normalizeRequired(t.getExitPrice(),"exitPrice");r.amount=BacktestDecimalStoragePolicy.normalizeRequired(t.getAmount(),"amount");r.grossProfit=BacktestDecimalStoragePolicy.normalizeRequired(t.getGrossProfit(),"grossProfit");r.fee=BacktestDecimalStoragePolicy.normalizeRequired(t.getFee(),"fee");r.netProfit=BacktestDecimalStoragePolicy.normalizeRequired(t.getNetProfit(),"netProfit");r.returnRatio=BacktestDecimalStoragePolicy.normalizeRequired(t.getReturnRatio(),"returnRatio");r.barsHeld=t.getBarsHeld();r.forcedExit=t.isForcedExit();r.exitReason=t.getExitReason();r.positionSide=t.getPositionSide().name();r.entryOrderSide=t.getEntryOrderSide().name();r.exitOrderSide=t.getExitOrderSide().name();out.add(r);}return out;}
    private List<BacktestEquityRow> equityRows(String id,List<EquityPoint> source){List<BacktestEquityRow> out=new ArrayList<>();for(int i=0;i<source.size();i++){EquityPoint p=source.get(i);BacktestEquityRow r=new BacktestEquityRow();r.runId=id;r.pointIndex=i;r.openTimeMs=p.openTime().toEpochMilli();r.equityRatio=BacktestDecimalStoragePolicy.normalizeRequired(p.equityRatio(),"equityRatio");r.drawdownRatio=BacktestDecimalStoragePolicy.normalizeRequired(p.drawdownRatio(),"drawdownRatio");r.inPosition=p.inPosition();r.equityValue=BacktestDecimalStoragePolicy.normalizeRequired(p.equityValue(),"equityValue");r.availableCapital=BacktestDecimalStoragePolicy.normalizeRequired(p.availableCapital(),"availableCapital");r.realizedPnl=BacktestDecimalStoragePolicy.normalizeRequired(p.realizedPnl(),"realizedPnl");r.unrealizedPnl=BacktestDecimalStoragePolicy.normalizeRequired(p.unrealizedPnl(),"unrealizedPnl");r.positionQuantity=BacktestDecimalStoragePolicy.normalizeRequired(p.positionQuantity(),"positionQuantity");r.positionNotional=BacktestDecimalStoragePolicy.normalizeRequired(p.positionNotional(),"positionNotional");r.exposureRatio=BacktestDecimalStoragePolicy.normalizeRequired(p.exposureRatio(),"exposureRatio");out.add(r);}return out;}
}
