package com.aiprovider.service.quant;

import com.aiprovider.controller.quant.dto.*;
import com.aiprovider.mapper.*;
import com.aiprovider.mapper.row.*;
import com.aiprovider.quant.market.history.model.MarketDataset;
import com.aiprovider.quant.strategy.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.util.*;

@Service
public class BacktestExperimentService {
    private static final int MAX_CANDIDATES=64, MAX_LEGS=128;
    private final BacktestExperimentMapper experiments; private final BacktestExperimentCandidateMapper candidates;
    private final BacktestRunMapper runs; private final com.aiprovider.quant.market.history.port.MarketDatasetRepository datasets;
    private final StrategyRegistry strategies; private final ObjectMapper json;
    public BacktestExperimentService(BacktestExperimentMapper e,BacktestExperimentCandidateMapper c,BacktestRunMapper r,com.aiprovider.quant.market.history.port.MarketDatasetRepository d,StrategyRegistry s,ObjectMapper j){experiments=e;candidates=c;runs=r;datasets=d;strategies=s;json=j;}

    @Transactional
    public BacktestExperimentDtos.CreateResponse create(BacktestExperimentCreateRequest q){
        validateRequest(q); MarketDataset dataset=datasets.findById(q.getDatasetId());
        if(dataset==null)throw error("BACKTEST_EXPERIMENT_RANGE_INVALID","datasetId not found");
        QuantStrategyDefinition definition;
        try{definition=strategies.get(q.getStrategyCode().trim());}catch(StrategyException e){throw error("BACKTEST_EXPERIMENT_GRID_INVALID",e.getMessage());}
        if(!definition.version().equals(q.getStrategyVersion().trim()))throw error("BACKTEST_EXPERIMENT_GRID_INVALID","strategy version is not supported");
        LinkedHashMap<String,List<Integer>> grid=validateGrid(q.getParameterGrid(),definition);
        List<LinkedHashMap<String,Integer>> combinations=combine(grid,definition);
        validateRange(dataset,q,combinations,definition);
        Instant now=Instant.now(); BacktestExperimentRow row=new BacktestExperimentRow(); row.experimentId=UUID.randomUUID().toString(); row.datasetId=q.getDatasetId();
        row.provider=dataset.getProvider().name();row.marketType=dataset.getMarketType().name();row.dataType=dataset.getDataType().name();row.symbol=dataset.getSymbol();row.intervalCode=dataset.getInterval().code();row.strategyCode=q.getStrategyCode().trim();row.strategyVersion=q.getStrategyVersion().trim();row.parameterGridJson=write(grid);row.candidateCount=combinations.size();
        row.trainingStartOpenTimeMs=q.getTrainingStartOpenTimeInclusive().toEpochMilli();row.trainingEndOpenTimeMs=q.getTrainingEndOpenTimeExclusive().toEpochMilli();row.validationStartOpenTimeMs=q.getValidationStartOpenTimeInclusive().toEpochMilli();row.validationEndOpenTimeMs=q.getValidationEndOpenTimeExclusive().toEpochMilli();row.orderAmount=q.getOrderAmount();row.feeRate=q.getFeeRate();row.forceCloseAtEnd=true;row.createdAt=now;row.updatedAt=now;experiments.insert(row);
        List<BacktestExperimentCandidateRow> rows=new ArrayList<>(); for(int i=0;i<combinations.size();i++){BacktestExperimentCandidateRow c=new BacktestExperimentCandidateRow();c.candidateId=UUID.randomUUID().toString();c.experimentId=row.experimentId;c.candidateIndex=i;c.parametersJson=write(combinations.get(i));c.trainingRunId=UUID.randomUUID().toString();c.validationRunId=UUID.randomUUID().toString();c.createdAt=now;c.updatedAt=now;rows.add(c);} candidates.insertBatch(rows);
        return new BacktestExperimentDtos.CreateResponse(row.experimentId,row.candidateCount,row.candidateCount*2);
    }
    public BacktestDtos.Page<BacktestExperimentDtos.ExperimentSummary> page(int page,int size,String status,String symbol,String strategyCode){validatePage(page,size);long offset=offset(page,size);String s=clean(status,true),sym=clean(symbol,true),code=clean(strategyCode,false);return new BacktestDtos.Page<>(experiments.findPage(s,sym,code,size,(int)offset).stream().map(this::summary).toList(),experiments.count(s,sym,code),page,size);}
    public BacktestExperimentDtos.ExperimentSummary get(String id){return refresh(require(id));}
    public BacktestDtos.Page<BacktestExperimentDtos.CandidateResult> candidates(String id,int page,int size,String sortBy,String order){require(id);if(page<1||size<1||size>100)throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","page/pageSize invalid");String sb=sortBy==null?"CANDIDATE_INDEX":sortBy.toUpperCase(Locale.ROOT),ord=order==null?"ASC":order.toUpperCase(Locale.ROOT);if(!candidateSorts().contains(sb)||!(ord.equals("ASC")||ord.equals("DESC")))throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","sortBy/order is invalid");long offset=offset(page,size);List<BacktestExperimentCandidateRow> rows=candidates.findPageSorted(id,size,(int)offset,sortExpression(sb),ord);return new BacktestDtos.Page<>(rows.stream().map(this::candidate).toList(),candidates.count(id),page,size);}
    private BacktestExperimentDtos.ExperimentSummary refresh(BacktestExperimentRow r){BacktestExperimentDtos.ExperimentSummary result=summary(r);if(!result.status().equals(r.status))experiments.updateAggregate(r.experimentId,result.status(),result.status().equals("COMPLETED")||result.status().equals("FAILED")||result.status().equals("COMPLETED_WITH_FAILURES")?Instant.now():null,result.failedCandidates()>0?"BACKTEST_EXPERIMENT_DISPATCH_FAILED":null,result.failedCandidates()>0?"one or more candidates failed":null,Instant.now());return result;}
    private Set<String> candidateSorts(){return Set.of("CANDIDATE_INDEX","TRAIN_TOTAL_RETURN_RATIO","VALIDATION_TOTAL_RETURN_RATIO","TRAIN_MAXIMUM_DRAWDOWN_RATIO","VALIDATION_MAXIMUM_DRAWDOWN_RATIO","TRAIN_PROFIT_FACTOR","VALIDATION_PROFIT_FACTOR","TRAIN_NET_PROFIT","VALIDATION_NET_PROFIT","TRAIN_WIN_RATE","VALIDATION_WIN_RATE","TRAIN_TRADE_COUNT","VALIDATION_TRADE_COUNT");}
    private String sortExpression(String s){return switch(s){case "CANDIDATE_INDEX"->"c.CandidateIndex";case "TRAIN_TOTAL_RETURN_RATIO"->"tr.TotalReturnRatio";case "VALIDATION_TOTAL_RETURN_RATIO"->"vr.TotalReturnRatio";case "TRAIN_MAXIMUM_DRAWDOWN_RATIO"->"tr.MaximumDrawdownRatio";case "VALIDATION_MAXIMUM_DRAWDOWN_RATIO"->"vr.MaximumDrawdownRatio";case "TRAIN_PROFIT_FACTOR"->"tr.ProfitFactor";case "VALIDATION_PROFIT_FACTOR"->"vr.ProfitFactor";case "TRAIN_NET_PROFIT"->"tr.NetProfit";case "VALIDATION_NET_PROFIT"->"vr.NetProfit";case "TRAIN_WIN_RATE"->"tr.WinRate";case "VALIDATION_WIN_RATE"->"vr.WinRate";case "TRAIN_TRADE_COUNT"->"tr.TradeCount";case "VALIDATION_TRADE_COUNT"->"vr.TradeCount";default->throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","sortBy is invalid");};}
    private BacktestExperimentDtos.ExperimentSummary summary(BacktestExperimentRow r){List<BacktestExperimentCandidateRow> cs=candidates.findPage(r.experimentId,Math.max(1,r.candidateCount),0);int pending=0,active=0,complete=0,failed=0,completeLegs=0,failedLegs=0;BigDecimal totalProgress=BigDecimal.ZERO;for(BacktestExperimentCandidateRow c:cs){if("PENDING".equals(c.dispatchStatus))pending++;if("CLAIMED".equals(c.dispatchStatus))active++;BacktestRunRow t=runs.findByRunId(c.trainingRunId),v=runs.findByRunId(c.validationRunId);boolean tc=terminal(t),vc=terminal(v),tf=failed(t),vf=failed(v);if(tc)completeLegs++;if(vc)completeLegs++;if(tf)failedLegs++;if(vf)failedLegs++;totalProgress=totalProgress.add(legProgress(t)).add(legProgress(v));if("FAILED".equals(c.dispatchStatus)){failed++;totalProgress=totalProgress.add(legProgress(t).signum()==0?BigDecimal.ZERO:BigDecimal.ZERO);if(t==null)totalProgress=totalProgress.add(BigDecimal.valueOf(100));if(v==null)totalProgress=totalProgress.add(BigDecimal.valueOf(100));}else if(tf||vf)failed++;else if(tc&&vc)complete++;}BigDecimal progress=totalProgress.divide(BigDecimal.valueOf(Math.max(1,r.candidateCount*2L)),2,RoundingMode.HALF_UP).max(BigDecimal.ZERO).min(BigDecimal.valueOf(100));String status=r.status;if(pending==0&&active==0&&complete+failed==r.candidateCount){status=failed==0?"COMPLETED":complete==0?"FAILED":"COMPLETED_WITH_FAILURES";}else if(active>0||complete>0||failed>0)status="RUNNING";return new BacktestExperimentDtos.ExperimentSummary(r.experimentId,r.datasetId,r.provider,r.marketType,r.dataType,r.symbol,r.intervalCode,r.strategyCode,r.strategyVersion,readGrid(r.parameterGridJson),r.candidateCount,Instant.ofEpochMilli(r.trainingStartOpenTimeMs),Instant.ofEpochMilli(r.trainingEndOpenTimeMs),Instant.ofEpochMilli(r.validationStartOpenTimeMs),Instant.ofEpochMilli(r.validationEndOpenTimeMs),r.orderAmount,r.feeRate,r.forceCloseAtEnd,status,progress,pending,active,complete,failed,completeLegs,failedLegs,r.errorCode,r.errorMessage,r.createdAt,r.startedAt,r.finishedAt,r.updatedAt);}
    private BigDecimal legProgress(BacktestRunRow r){if(r==null)return BigDecimal.ZERO;if(terminal(r))return BigDecimal.valueOf(100);return r.progressPercent==null?BigDecimal.ZERO:r.progressPercent.max(BigDecimal.ZERO).min(BigDecimal.valueOf(100));}
    private BacktestExperimentDtos.CandidateResult candidate(BacktestExperimentCandidateRow c){return new BacktestExperimentDtos.CandidateResult(c.candidateId,c.candidateIndex,read(c.parametersJson),c.dispatchStatus,segment("TRAIN",c.trainingRunId),segment("VALIDATION",c.validationRunId));}
    private BacktestExperimentDtos.SegmentResult segment(String type,String id){BacktestRunRow r=runs.findByRunId(id);if(r==null)return new BacktestExperimentDtos.SegmentResult(type,id,"NOT_CREATED",BigDecimal.ZERO,null,null,null,null,null,null,null);BacktestDtos.Metrics m=new BacktestDtos.Metrics(r.tradeCount,r.winningTradeCount,r.losingTradeCount,r.breakEvenTradeCount,r.winRate,r.grossProfit,r.grossLoss,r.netProfit,r.totalReturnRatio,r.maximumDrawdownRatio,r.profitFactor,r.averageTradeReturnRatio,r.buyAndHoldReturnRatio,r.totalFees);return new BacktestExperimentDtos.SegmentResult(type,id,r.status,r.progressPercent,r.errorCode,r.errorMessage,r.barCount,r.tradeCount,m,r.startedAt,r.finishedAt);}
    private boolean terminal(BacktestRunRow r){return r!=null&&("COMPLETED".equals(r.status)||"FAILED".equals(r.status));}private boolean failed(BacktestRunRow r){return r!=null&&"FAILED".equals(r.status);}
    private BacktestExperimentRow require(String id){BacktestExperimentRow r=experiments.findByExperimentId(id);if(r==null)throw error("BACKTEST_EXPERIMENT_NOT_FOUND","experimentId not found");return r;}
    private LinkedHashMap<String,List<Integer>> validateGrid(Map<String,List<Integer>> input,QuantStrategyDefinition d){if(input==null||input.size()!=d.parameters().size())throw error("BACKTEST_EXPERIMENT_GRID_INVALID","parameter grid keys do not match strategy definition");LinkedHashMap<String,List<Integer>> out=new LinkedHashMap<>();for(StrategyParameterDefinition p:d.parameters()){List<Integer> v=input.get(p.name());if(v==null||v.isEmpty()||v.size()>20||new HashSet<>(v).size()!=v.size()||v.stream().anyMatch(x->x==null||x<p.minValue()||x>p.maxValue()))throw error("BACKTEST_EXPERIMENT_GRID_INVALID","invalid values for "+p.name());out.put(p.name(),List.copyOf(v));}if(!out.keySet().equals(input.keySet()))throw error("BACKTEST_EXPERIMENT_GRID_INVALID","parameter grid keys do not match strategy definition");return out;}
    private List<LinkedHashMap<String,Integer>> combine(LinkedHashMap<String,List<Integer>> grid,QuantStrategyDefinition d){long total=1;try{for(List<Integer> v:grid.values())total=Math.multiplyExact(total,v.size());}catch(ArithmeticException e){throw error("BACKTEST_EXPERIMENT_GRID_INVALID","candidate count overflow");}if(total>MAX_CANDIDATES||total*2>MAX_LEGS)throw error("BACKTEST_EXPERIMENT_GRID_INVALID","candidate count exceeds limit");List<LinkedHashMap<String,Integer>> out=new ArrayList<>();for(int i=0;i<total;i++){int n=i;LinkedHashMap<String,Integer> c=new LinkedHashMap<>();for(StrategyParameterDefinition p:d.parameters()){List<Integer> vals=grid.get(p.name());c.put(p.name(),vals.get(n%vals.size()));n/=vals.size();}try{d.minimumRequiredBars(c);}catch(StrategyException e){throw error("BACKTEST_EXPERIMENT_GRID_INVALID",e.getMessage());}out.add(c);}return out;}
    private void validateRange(MarketDataset d,BacktestExperimentCreateRequest q,List<LinkedHashMap<String,Integer>> cs,QuantStrategyDefinition def){Instant ts=q.getTrainingStartOpenTimeInclusive(),te=q.getTrainingEndOpenTimeExclusive(),vs=q.getValidationStartOpenTimeInclusive(),ve=q.getValidationEndOpenTimeExclusive();if(!ts.isBefore(te)||te.isAfter(vs)||!vs.isBefore(ve)||!aligned(d,ts)||!aligned(d,te)||!aligned(d,vs)||!aligned(d,ve)||d.getEarliestOpenTime()==null||d.getLatestOpenTime()==null||ts.isBefore(d.getEarliestOpenTime())||ve.isAfter(d.getLatestOpenTime().plusMillis(d.getInterval().durationMillis())))throw error("BACKTEST_EXPERIMENT_RANGE_INVALID","experiment range is outside contiguous dataset coverage");long train=bars(d,ts,te),valid=bars(d,vs,ve);int min=cs.stream().mapToInt(def::minimumRequiredBars).max().orElse(Integer.MAX_VALUE);if(train<min||valid<min)throw error("BACKTEST_EXPERIMENT_RANGE_INVALID","range has fewer bars than strategy minimum");}
    private boolean aligned(MarketDataset d,Instant i){return d.getInterval().isFixedDuration()&&d.getInterval().alignOpenTime(i).equals(i);}
    private long bars(MarketDataset d,Instant s,Instant e){return Math.max(0,(e.toEpochMilli()-s.toEpochMilli())/d.getInterval().durationMillis());}
    private void validateRequest(BacktestExperimentCreateRequest q){if(q==null||q.getDatasetId()<=0||blank(q.getStrategyCode())||blank(q.getStrategyVersion())||q.getParameterGrid()==null||q.getTrainingStartOpenTimeInclusive()==null||q.getTrainingEndOpenTimeExclusive()==null||q.getValidationStartOpenTimeInclusive()==null||q.getValidationEndOpenTimeExclusive()==null||q.getOrderAmount()==null||!decimal(q.getOrderAmount())||q.getOrderAmount().signum()<=0||q.getFeeRate()==null||!decimal(q.getFeeRate())||q.getFeeRate().signum()<0||q.getFeeRate().compareTo(new BigDecimal("0.01"))>0||!q.isForceCloseAtEnd())throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","invalid experiment request");}
    private boolean decimal(BigDecimal v){if(v.scale()>18||v.precision()>38)return false;BigDecimal n=v.stripTrailingZeros();return Math.max(0,n.precision()-n.scale())<=20;}private boolean blank(String s){return s==null||s.trim().isEmpty();}
    private String clean(String s,boolean upper){if(s==null||s.isBlank())return null;String v=s.trim();return upper?v.toUpperCase(Locale.ROOT):v;}private void validatePage(int p,int s){if(p<1||s<1||s>100)throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","page/pageSize invalid");}private long offset(int p,int s){try{long v=Math.multiplyExact((long)p-1,s);if(v>10_000_000)throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","page offset exceeds limit");return v;}catch(ArithmeticException e){throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","page offset overflow");}}
    private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw error("BACKTEST_EXPERIMENT_REQUEST_INVALID","JSON serialization failed");}}private Map<String,Integer> read(String v){try{return json.readValue(v,new TypeReference<LinkedHashMap<String,Integer>>(){});}catch(Exception e){throw error("BACKTEST_PERSISTENCE_FAILED","stored parameters JSON is invalid");}}private Map<String,List<Integer>> readGrid(String v){try{return json.readValue(v,new TypeReference<LinkedHashMap<String,List<Integer>>>(){});}catch(Exception e){throw error("BACKTEST_PERSISTENCE_FAILED","stored grid JSON is invalid");}}
    private BacktestTaskException error(String c,String m){return new BacktestTaskException(c,m==null?"experiment failed":m.replaceAll("[\\r\\n]"," "));}
}
