package com.aiprovider.service.quant;

import com.aiprovider.config.quant.QuantBacktestProperties;
import com.aiprovider.mapper.*; import com.aiprovider.mapper.row.*; import com.aiprovider.quant.backtest.*;
import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.Instant; import java.util.*;

@Service public class BacktestPersistenceService {
 private final BacktestRunMapper runs; private final BacktestTradeMapper trades; private final BacktestEquityMapper equity; private final ObjectMapper json; private final QuantBacktestProperties properties;
 public BacktestPersistenceService(BacktestRunMapper r,BacktestTradeMapper t,BacktestEquityMapper e,ObjectMapper j,QuantBacktestProperties p){runs=r;trades=t;equity=e;json=j;properties=p;}
 @Transactional public void persistCompleted(String runId,BacktestResult result){try{
   trades.deleteByRunId(runId); equity.deleteByRunId(runId); BacktestRunRow row=new BacktestRunRow(); row.runId=runId; row.resolvedParametersJson=json.writeValueAsString(result.getStrategyParameters()); row.barCount=result.getBarCount(); BacktestMetrics m=result.getMetrics(); row.tradeCount=m.getTradeCount();row.winningTradeCount=m.getWinningTradeCount();row.losingTradeCount=m.getLosingTradeCount();row.breakEvenTradeCount=m.getBreakEvenTradeCount();row.winRate=m.getWinRate();row.grossProfit=m.getGrossProfit();row.grossLoss=m.getGrossLoss();row.netProfit=m.getNetProfit();row.totalReturnRatio=m.getTotalReturnRatio();row.maximumDrawdownRatio=m.getMaximumDrawdownRatio();row.profitFactor=m.getProfitFactor();row.averageTradeReturnRatio=m.getAverageTradeReturnRatio();row.buyAndHoldReturnRatio=m.getBuyAndHoldReturnRatio();row.totalFees=m.getTotalFees();row.executionModel=result.getExecutionModel();row.warningsJson=json.writeValueAsString(result.getWarnings());row.equityPointCount=result.getEquityCurve().size();row.finishedAt=Instant.now();row.updatedAt=row.finishedAt;
   List<BacktestTradeRow> tradeRows=tradeRows(runId,result.getTrades());for(int i=0;i<tradeRows.size();i+=properties.getTradeInsertBatchSize())trades.insertBatch(tradeRows.subList(i,Math.min(i+properties.getTradeInsertBatchSize(),tradeRows.size())));
   List<BacktestEquityRow> equityRows=equityRows(runId,result.getEquityCurve());for(int i=0;i<equityRows.size();i+=properties.getEquityInsertBatchSize())equity.insertBatch(equityRows.subList(i,Math.min(i+properties.getEquityInsertBatchSize(),equityRows.size())));
   if(runs.complete(row)!=1)throw new BacktestTaskException("BACKTEST_STATE_CONFLICT","runId="+runId+" PERSISTING CAS failed");
 }catch(BacktestTaskException e){throw e;}catch(Exception e){throw new BacktestTaskException("BACKTEST_PERSISTENCE_FAILED","runId="+runId+" result persistence failed",e);}}
 private List<BacktestTradeRow> tradeRows(String id,List<BacktestTrade> source){List<BacktestTradeRow> out=new ArrayList<>();for(BacktestTrade t:source){BacktestTradeRow r=new BacktestTradeRow();r.runId=id;r.tradeNo=t.getTradeNo();r.entrySignalIndex=t.getEntrySignalIndex();r.entryIndex=t.getEntryIndex();r.entryTimeMs=t.getEntryTime().toEpochMilli();r.entryPrice=t.getEntryPrice();r.exitSignalIndex=t.getExitSignalIndex();r.exitIndex=t.getExitIndex();r.exitTimeMs=t.getExitTime().toEpochMilli();r.exitPrice=t.getExitPrice();r.amount=t.getAmount();r.grossProfit=t.getGrossProfit();r.fee=t.getFee();r.netProfit=t.getNetProfit();r.returnRatio=t.getReturnRatio();r.barsHeld=t.getBarsHeld();r.forcedExit=t.isForcedExit();r.exitReason=t.getExitReason();out.add(r);}return out;}
 private List<BacktestEquityRow> equityRows(String id,List<EquityPoint> source){List<BacktestEquityRow> out=new ArrayList<>();for(int i=0;i<source.size();i++){EquityPoint p=source.get(i);BacktestEquityRow r=new BacktestEquityRow();r.runId=id;r.pointIndex=i;r.openTimeMs=p.openTime().toEpochMilli();r.equityRatio=p.equityRatio();r.drawdownRatio=p.drawdownRatio();r.inPosition=p.inPosition();out.add(r);}return out;}
}
